table 'Eje TopN Otros Gerencias'
	lineageTag: 5f5a8836-730a-41ec-92b7-e37aa9861bd0

	measure 'Real Act_GT (Top9 + Otar_G)' =
			
			
			VAR TopNValue    = 9
			VAR CategoriaSel = SELECTEDVALUE( 'Eje TopN Otros Gerencias'[Categoria] )
			VAR InScopeCat   = ISINSCOPE( 'Eje TopN Otros Gerencias'[Categoria] )
			
			-- Lista de gerencias bajo los filtros actuales (respeta slicers)
			VAR GerenciasAll =
			    SUMMARIZE(
			        ALLSELECTED( gd_financiero_gasto_gerencial_base[des_gerencia] ),
			        gd_financiero_gasto_gerencial_base[des_gerencia]
			    )
			
			-- TopN por la medida de gerencias (orden descendente)
			VAR TopNTable =
			    TOPN(
			        TopNValue,
			        GerenciasAll,
			        [Real Act_GT_gerencias],
			        DESC
			    )
			
			-- "OTRAS GERENCIAS" = complemento del TopN
			VAR OthersTable =
			    EXCEPT( GerenciasAll, TopNTable )
			
			-- ¿La categoría actual es "OTRAS GERENCIAS"?
			VAR EsOtros = CategoriaSel = "OTRAS GERENCIAS"
			
			-- ¿La categoría actual pertenece al TopN?
			VAR EsGerenciaTopN =
			    CONTAINS(
			        TopNTable,
			        gd_financiero_gasto_gerencial_base[des_gerencia],
			        CategoriaSel
			    )
			
			-- Agregados para total
			VAR TopNMeasure =
			    CALCULATE( [Real Act_GT_gerencias], KEEPFILTERS( TopNTable ) )
			
			VAR OthersMeasure =
			    CALCULATE( [Real Act_GT_gerencias], KEEPFILTERS( OthersTable ) )
			
			RETURN
			IF(
			    NOT InScopeCat || ISBLANK( CategoriaSel ),
			    -- TOTAL: suma de Top9 + OTRAS GERENCIAS
			    COALESCE( TopNMeasure, 0 ) + COALESCE( OthersMeasure, 0 ),
			    -- FILA:
			    IF(
			        EsOtros,
			        -- Fila "OTRAS GERENCIAS": suma del complemento
			               OthersMeasure,
			        -- Fila por gerencia: mostrar solo si está en Top9; caso contrario BLANK para ocultarla
			        IF(
			            EsGerenciaTopN,
			            CALCULATE(
			                [Real Act_GT_gerencias],
			                TREATAS( { CategoriaSel }, gd_financiero_gasto_gerencial_base[des_gerencia] )
			            ),
			            BLANK()
			        )
			    )
			)
		formatString: #,0
		lineageTag: ed1b2476-2ae5-4891-9f46-931e405870c1

		annotation PBI_FormatHint = {"isDecimal":true}

	column Categoria
		lineageTag: a98412d3-7851-489a-8eb0-472b71cd7aed
		summarizeBy: none
		isNameInferred
		sourceColumn: [Categoria]

		annotation SummarizationSetBy = Automatic

	partition 'Eje TopN Otros Gerencias' = calculated
		mode: import
		source =
				
				UNION(
				    SELECTCOLUMNS(
				        DISTINCT( gd_financiero_gasto_gerencial_base[des_gerencia] ),
				        "Categoria", gd_financiero_gasto_gerencial_base[des_gerencia]
				    ),
				    DATATABLE( "Categoria", STRING, { { "OTRAS GERENCIAS" } } )
				)

	annotation PBI_Id = e9a5e5cc716943e28b1a192a8c12684e

