table gd_financiero_gasto_gerencial_base
	lineageTag: 8e49a7db-957e-40d8-96e8-b490a4c7b1ca

	measure 'Real Act_GT_gerencias' =
			
			VAR PeriodoSeleccionado = MAX ( Calendario[Date] )          -- usar columna de fecha
			VAR AnioActual         = YEAR ( PeriodoSeleccionado )
			VAR MesActual          = MONTH ( PeriodoSeleccionado )
			VAR MesActual_Inicio   = DATE ( AnioActual, MesActual, 1 )
			
			-- Rango acumulado desde inicio de año hasta fin del mes actual
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[Date] ),                             -- ignora filtros externos del calendario
			        Calendario[Date] >= DATE ( AnioActual, 1, 1 )
			            && Calendario[Date] <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- Calculamos la métrica base según SelectorData y SelectorValor
			VAR BaseMeasure =
			    SWITCH (
			        SELECTEDVALUE ( SelectorData[TipoData] ),
			        "Real",
			            SWITCH (
			                SELECTEDVALUE ( SelectorValor[TipoValor] ),
			                "Anualizado",   CALCULATE ( SUM ( gd_financiero_gasto_gerencial_base[saldo_mes_anualizado_miles] )),
			                "Mensualizado", CALCULATE ( SUM ( gd_financiero_gasto_gerencial_base[val_valor])),
			                "Acumulado",    CALCULATE ( SUM ( gd_financiero_gasto_gerencial_base[saldo_mes_acumulado_miles]), FiltroAcumulado )
			            ),
			        "Presupuesto",
			            SWITCH (
			                SELECTEDVALUE ( SelectorValor[TipoValor] ),
			                "Anualizado",   CALCULATE ( SUM ( gd_financiero_gasto_gerencial_base[val_presu_mes_anualizado_miles] )),
			                "Mensualizado", CALCULATE ( SUM ( gd_financiero_gasto_gerencial_base[val_presu_mes_miles] )),
			                "Acumulado",    CALCULATE ( SUM ( gd_financiero_gasto_gerencial_base[val_presu_mes_acumulado_miles]), FiltroAcumulado )
			            ),
			        "Forecast",
			            SWITCH (
			                SELECTEDVALUE ( SelectorValor[TipoValor] ),
			                "Anualizado",   CALCULATE ( SUM ( gd_financiero_gasto_gerencial_base[val_forecast_mes_anualizado_miles] )),
			                "Mensualizado", CALCULATE ( SUM ( gd_financiero_gasto_gerencial_base[val_forecast_mes_miles] )),
			                "Acumulado",    CALCULATE ( SUM ( gd_financiero_gasto_gerencial_base[val_forecast_mes_acumulado_miles]), FiltroAcumulado )
			            )
			    )
			RETURN
			IF (
			    ISBLANK ( BaseMeasure ) || BaseMeasure = 0,
			    BLANK (),                     -- oc    BLANK (),                     -- oculta en el visual cuando no hay datos o es 0
			    BaseMeasure
			)
		lineageTag: a01b1709-d9f9-4ff4-87bb-9ba10d341fac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fec_periodo
		dataType: string
		lineageTag: df0f65e8-61eb-46e9-b555-fe1fb5c92079
		summarizeBy: none
		sourceColumn: fec_periodo

		annotation SummarizationSetBy = Automatic

	column fecha_ultimo_dia
		dataType: dateTime
		formatString: Long Date
		lineageTag: b3cec807-eb34-48d8-ab4f-ed1d9546344a
		summarizeBy: none
		sourceColumn: fecha_ultimo_dia

		variation Variación
			isDefault
			relationship: 6e34b438-b381-4463-a0e2-2280d6178e98
			defaultHierarchy: LocalDateTable_df5126f3-2c89-44ae-8570-e12af3843150.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column id_empresa
		dataType: string
		lineageTag: 061ed6fe-609b-4149-a722-ffd4ae8fd744
		summarizeBy: none
		sourceColumn: id_empresa

		annotation SummarizationSetBy = Automatic

	column des_tipo_ramo
		dataType: string
		lineageTag: f4a7ea4d-bef8-467b-a845-57ebe03325b8
		summarizeBy: none
		sourceColumn: des_tipo_ramo

		annotation SummarizationSetBy = Automatic

	column id_cuenta_contable
		dataType: string
		lineageTag: 9e706d6d-2cd4-46dd-972b-ade0fbe0b35e
		summarizeBy: none
		sourceColumn: id_cuenta_contable

		annotation SummarizationSetBy = Automatic

	column des_gerencia
		dataType: string
		lineageTag: a6937dbc-1a2e-4fad-86ee-3f7bc76f5598
		summarizeBy: none
		sourceColumn: des_gerencia

		annotation SummarizationSetBy = Automatic

	column cta_des
		dataType: string
		lineageTag: a1353d9a-41f4-4ddb-8072-5a8137d97f0e
		summarizeBy: none
		sourceColumn: cta_des

		annotation SummarizationSetBy = Automatic

	column val_valor
		dataType: double
		lineageTag: a8939961-fec4-4ad5-9031-ae05eb8a0359
		summarizeBy: sum
		sourceColumn: val_valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column saldo_mes_anualizado_miles
		dataType: double
		lineageTag: d44324e9-3ef3-4813-9df9-640fc59ab3d6
		summarizeBy: sum
		sourceColumn: saldo_mes_anualizado_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column saldo_mes_acumulado_miles
		dataType: double
		lineageTag: 1797d327-8b2b-4e21-beb0-1a8d741b4c93
		summarizeBy: sum
		sourceColumn: saldo_mes_acumulado_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column saldo_mes_y_1_miles
		dataType: double
		lineageTag: edfdc0ae-0de8-4b40-a2c6-baea5eede1e5
		summarizeBy: sum
		sourceColumn: saldo_mes_y_1_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_mes_anualizado_y_1_miles
		dataType: double
		lineageTag: d11e8cef-13d9-4f6b-8724-8780e2c852d5
		summarizeBy: sum
		sourceColumn: val_mes_anualizado_y_1_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_mes_acumulado_y_1_miles
		dataType: double
		lineageTag: 467540a5-568a-4928-999e-b9438f6135dc
		summarizeBy: sum
		sourceColumn: val_mes_acumulado_y_1_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presu_mes_miles
		dataType: double
		lineageTag: 29bb07a4-0bcf-40af-a050-1540dbe3d7cf
		summarizeBy: sum
		sourceColumn: val_presu_mes_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presu_mes_anualizado_miles
		dataType: double
		lineageTag: 45bde48f-1e37-43ea-8d89-b4b1edc0c55a
		summarizeBy: sum
		sourceColumn: val_presu_mes_anualizado_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presu_mes_acumulado_miles
		dataType: double
		lineageTag: 47e1dfc1-b07d-4827-b1c3-201d716e9494
		summarizeBy: sum
		sourceColumn: val_presu_mes_acumulado_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presu_mes_y_1_miles
		dataType: double
		lineageTag: d800d731-be10-4c1e-bae2-4c25702246e7
		summarizeBy: sum
		sourceColumn: val_presu_mes_y_1_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presu_mes_anualizado_y_1_miles
		dataType: double
		lineageTag: 10a239f9-cb01-47d9-8918-e81e5e58fb0a
		summarizeBy: sum
		sourceColumn: val_presu_mes_anualizado_y_1_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presu_mes_acumulado_y_1_miles
		dataType: double
		lineageTag: 6c0c51f4-db86-4a56-8d25-7e48e81dd314
		summarizeBy: sum
		sourceColumn: val_presu_mes_acumulado_y_1_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_mes_miles
		dataType: double
		lineageTag: 79c37c09-9964-4f18-aaa6-8969cb53f2dd
		summarizeBy: sum
		sourceColumn: val_forecast_mes_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_mes_anualizado_miles
		dataType: double
		lineageTag: f1d790e7-11fe-4e1c-9918-31dd17be09f9
		summarizeBy: sum
		sourceColumn: val_forecast_mes_anualizado_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_mes_acumulado_miles
		dataType: double
		lineageTag: 40f8ff04-e921-42d8-94e1-d2af2063140c
		summarizeBy: sum
		sourceColumn: val_forecast_mes_acumulado_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_mes_y_1_miles
		dataType: double
		lineageTag: ff007e43-cdf9-4abd-8220-4eb5f8e4378b
		summarizeBy: sum
		sourceColumn: val_forecast_mes_y_1_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_mes_anualizado_y_1_miles
		dataType: double
		lineageTag: 1f31c0a8-3f9b-4479-854b-acdc2aa79346
		summarizeBy: sum
		sourceColumn: val_forecast_mes_anualizado_y_1_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_mes_acumulado_y_1_miles
		dataType: double
		lineageTag: c5ce95f4-2789-4199-8ebd-a9932b898f52
		summarizeBy: sum
		sourceColumn: val_forecast_mes_acumulado_y_1_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DIA = DAY(gd_financiero_gasto_gerencial_base[fecha_ultimo_dia])
		formatString: 0
		lineageTag: a0b5bb3c-ecbf-4364-89d6-a625c679679b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column id_tiempo = gd_financiero_gasto_gerencial_base[fec_periodo]&gd_financiero_gasto_gerencial_base[DIA]
		lineageTag: 5c0be5c0-595b-4097-afc9-e1f414219721
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition gd_financiero_gasto_gerencial_base = m
		mode: import
		source =
				let
				    Origen = Databricks.Catalogs("adb-2683128165517039.19.azuredatabricks.net", "/sql/1.0/warehouses/7d4c90cb72eed782", [Catalog="ctlfinanciero", Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null]),
				    ctlfinanciero_Database = Origen{[Name="ctlfinanciero",Kind="Database"]}[Data],
				    schgold_Schema = ctlfinanciero_Database{[Name="schgold",Kind="Schema"]}[Data],
				    gd_financiero_gasto_gerencial_base_Table = schgold_Schema{[Name="gd_financiero_gasto_gerencial_base",Kind="Table"]}[Data]
				in
				    gd_financiero_gasto_gerencial_base_Table

