table gd_financiero_inversiones
	lineageTag: 42b250e3-ef65-454e-a58b-5dd64c5a770c

	measure FechaMaxCargaTexto_IN =
			
			VAR FechaMax =
			    CALCULATE (
			        MAX ( gd_financiero_inversiones[fec_periodo_fecha_IN] ),
			        ALL ( gd_financiero_inversiones )
			    )
			VAR MesAbrevRaw = FORMAT ( FechaMax, "MMM" )         -- abreviado
			VAR MesSinPunto  = SUBSTITUTE ( MesAbrevRaw, ".", "" )
			VAR MesCap       = UPPER ( LEFT ( MesSinPunto, 1 ) ) &
			                   LOWER ( MID ( MesSinPunto, 2, LEN ( MesSinPunto ) - 1 ) )
			VAR Mes3         = LEFT ( MesCap, 3 )                 -- asegura "Dic", "Sep", etc.
			RETURN
			    IF ( ISBLANK ( FechaMax ), BLANK (), Mes3 & " " & FORMAT ( FechaMax, "yyyy" ) )
		displayFolder: Medida
		lineageTag: c952a6d6-6fae-41e3-9914-e2558e09259f

	measure InversionesObligatorias = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Inversiones Obligaciones === */
			VAR SumColumna_IversionesObligatoriasG1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroAcumulado
			                    )
			            )
			    )
			VAR SumColumna_IversionesObligatoriasG2 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroAcumulado
			                    )
			            )
			    )
			VAR SumColumna_IversionesObligatoriasG3 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroAcumulado
			                    )
			            )
			    )
			VAR SumColumna_IversionesObligatoriasG4 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_IversionesObligatoriasG1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"3101","3201","5701","5702"},
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			VAR SumColumna_IversionesObligatoriasG2_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"4801","4802"},
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			VAR SumColumna_IversionesObligatoriasG3_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"259006"},
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			VAR SumColumna_IversionesObligatoriasG4_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN {"1201"},
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_IversionesObligatoriasG1
			VAR REAL_Y_1 = SumColumna_IversionesObligatoriasG1_Y1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_IN[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: fb02ca72-ee6a-470a-bd11-8f0062c4fdfb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure InversionesAdmitidas = ```
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "11010801", "11010802", "11010803", "11010804" }
			VAR CtasG2 = {
			    "110301","3101","3201","11010102","11010202","11010302","11010402","11010101","11010201",
			    "11010301","11010401","11010501","11011001","11011101","11011002","11011102","11011003",
			    "11011103","11011004","11011104","11011005","11011105","11011006","11011106","11010601",
			    "11010602","11010603","11010701","11010702","11010703","11010805","11010905","11010806",
			    "11010906","11010103","11010203"
			}
			
			----------------------------------------------------------------------------------
			/* === Inversiones Admitidas === */
			VAR SumColumna_InversionesAdmitidasG1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_InversionesAdmitidasG2 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_InversionesAdmitidasG1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_InversionesAdmitidasG2_Y2 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = (SumColumna_InversionesAdmitidasG1 * 2) + SumColumna_InversionesAdmitidasG2
			VAR REAL_Y_1 = (SumColumna_InversionesAdmitidasG1_Y1 * 2) + SumColumna_InversionesAdmitidasG2_Y2
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE ( ROUND ( DIVIDE ( YoY, REAL_Y_1, 0 ) * 100, 2 ), 0 )
			
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_IN[TipoCalculo] ),
			    "REAL ACT", COALESCE ( DIVIDE ( REAL_ACT, 1000, 0 ), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE ( DIVIDE ( YoY, 1000, 0 ), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: 79d31735-0987-444d-9d9b-ae8a31ece9ca

		annotation PBI_FormatHint = {"isDecimal":true}

	measure COBERTURA = COALESCE(DIVIDE(gd_financiero_inversiones[InversionesAdmitidas],gd_financiero_inversiones[InversionesObligatorias],0),0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Medida
		lineageTag: 10a9d00b-2bac-44eb-8ebf-9ce9eecd47f9

	measure 'Total No Admitida' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "11010303", "11010403"}
			----------------------------------------------------------------------------------
			/* === Total No Admitida === */
			VAR SumColumna_TotalNoAdmitidaG1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_TotalNoAdmitidaG1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_TotalNoAdmitidaG1
			VAR REAL_Y_1 = SumColumna_TotalNoAdmitidaG1_Y1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE ( ROUND ( DIVIDE ( YoY, REAL_Y_1, 0 ) * 100, 2 ), 0 )
			
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_IN[TipoCalculo] ),
			    "REAL ACT", COALESCE ( DIVIDE ( REAL_ACT, 1000, 0 ), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE ( DIVIDE ( YoY, 1000, 0 ), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: d6f95b86-9dfc-4069-9d21-644e287c5a2e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Prohibiciones (IFIS Fideicomisos)' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "11010806"}
			----------------------------------------------------------------------------------
			/* === Prohibiciones (IFIS Fideicomisos) === */
			VAR SumColumna_ProhibicioneIFISFideicomisosG1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_ProhibicioneIFISFideicomisosG1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ProhibicioneIFISFideicomisosG1
			VAR REAL_Y_1 = SumColumna_ProhibicioneIFISFideicomisosG1_Y1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE ( ROUND ( DIVIDE ( YoY, REAL_Y_1, 0 ) * 100, 2 ), 0 )
			
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_IN[TipoCalculo] ),
			    "REAL ACT", COALESCE ( DIVIDE ( REAL_ACT, 1000, 0 ), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE ( DIVIDE ( YoY, 1000, 0 ), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: d3a532f1-22c7-49e1-b9c1-8864d3fa65b9

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Provisiones =
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "480302", "470301", "4704", "4705", "4806", "4805" }
			VAR CtasG2 = {"470403", "5706", "5704", "570302", "570303", "5705"}
			VAR CtasG3 = {"470204"}
			
			----------------------------------------------------------------------------------
			/* === Provisiones === */
			VAR SumColumna_ProvisionesG1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_ProvisionesG2 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_ProvisionesG3 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_ProvisionesG1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_ProvisionesG2_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_ProvisionesG3_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = (-SumColumna_ProvisionesG1) + (-SumColumna_ProvisionesG2)+ SumColumna_ProvisionesG3
			VAR REAL_Y_1 = (-SumColumna_ProvisionesG1_Y1) + (-SumColumna_ProvisionesG2_Y1)+ SumColumna_ProvisionesG3_Y1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE ( ROUND ( DIVIDE ( YoY, REAL_Y_1, 0 ) * 100, 2 ), 0 )
			
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_IN[TipoCalculo] ),
			    "REAL ACT", COALESCE ( DIVIDE ( REAL_ACT, 1000, 0 ), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE ( DIVIDE ( YoY, 1000, 0 ), 0 ),
			    "%YoY", CapitalBase3
			)
		formatString: #,0
		displayFolder: Medida
		lineageTag: 1116cbf3-784a-4e44-80e6-56c18497f8cb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Bienes Raíces' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "110301"}
			----------------------------------------------------------------------------------
			/* === Total Bienes Raíces === */
			VAR SumColumna_TotalBienesRaicesG1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_TotalBienesRaicesG1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_TotalBienesRaicesG1
			VAR REAL_Y_1 = SumColumna_TotalBienesRaicesG1_Y1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE ( ROUND ( DIVIDE ( YoY, REAL_Y_1, 0 ) * 100, 2 ), 0 )
			
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_IN[TipoCalculo] ),
			    "REAL ACT", COALESCE ( DIVIDE ( REAL_ACT, 1000, 0 ), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE ( DIVIDE ( YoY, 1000, 0 ), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: 0ae5ec5e-1a22-4385-a70e-1b314f8b4568

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Inversión Neta' = ```
			
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = {"11010806","11010103","11010203","11010303","11010403" }
			VAR CtasG2 = 
			    {"110301","11011001","11011101","11011002","11011102","11011003","11011103",
			    "11011004","11011104","11011005","11011105","11011006","11011106","11010601",
			    "11010602","11010603","11010701","11010702","11010703","11010805","11010905",
			    "11010906","11010801","11010802","11010803","11010804","11010102","11010202",
			    "11010302","11010402","11010101","11010201","11010301","11010401","11010501"
			    }
			
			----------------------------------------------------------------------------------
			/* === Total Inversiones Financieras === */
			VAR SumColumna_TotalInversionesFinancierasG1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_TotalInversionesFinancierasG2 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_TotalInversionesFinancierasG1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_TotalInversionesFinancierasG2_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = (SumColumna_TotalInversionesFinancierasG1 * 2) + SumColumna_TotalInversionesFinancierasG2
			VAR REAL_Y_1 = (SumColumna_TotalInversionesFinancierasG1_Y1 * 2) + SumColumna_TotalInversionesFinancierasG2_Y1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE ( ROUND ( DIVIDE ( YoY, REAL_Y_1, 0 ) * 100, 2 ), 0 )
			
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_IN[TipoCalculo] ),
			    "REAL ACT", COALESCE ( DIVIDE ( REAL_ACT, 1000, 0 ), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE ( DIVIDE ( YoY, 1000, 0 ), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: 5e3a5d9f-6ab1-4c17-94a3-49384ba23296

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Inversión Neta Financiera' = [Inversión Neta] - ([Total No Admitida]+[Prohibiciones (IFIS Fideicomisos)])
		formatString: #,0
		displayFolder: Medida
		lineageTag: 057a0df0-2a9e-42a6-97a1-60de0f088183

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'EXCEDENTE / DÉFICIT' = [InversionesAdmitidas]-[InversionesObligatorias]
		displayFolder: Medida
		lineageTag: bd2bd4a3-0961-4fc5-8fca-06aa72c67c2a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure FiltroAñoDinamico_IN = ```
			
			VAR SelectedMinDate = CALCULATE( MIN ( gd_financiero_inversiones[fec_periodo_fecha_IN] ), ALLSELECTED ( gd_financiero_inversiones ) )
			VAR SelectedMaxDate = CALCULATE( MAX ( gd_financiero_inversiones[fec_periodo_fecha_IN]  ), ALLSELECTED ( gd_financiero_inversiones ) )
			VAR HaySeleccion    = NOT ISBLANK ( SelectedMinDate ) && NOT ISBLANK ( SelectedMaxDate )
			
			-- Si hay selección de período: toma el año de la selección (basta con el Máx).
			-- Si no hay selección: toma el año actual.
			VAR TargetYear =
			    IF ( HaySeleccion, YEAR ( SelectedMaxDate ), YEAR ( TODAY() ) )
			
			-- Año del contexto actual del visual (barra/mes) calculado desde la fecha real
			VAR YearEnContexto = YEAR ( MAX ( gd_financiero_inversiones[fec_periodo_fecha_IN]  ) )
			
			RETURN
			    IF ( YearEnContexto = TargetYear, 1, 0 )
			
			```
		formatString: 0
		displayFolder: Medida
		lineageTag: 365de420-0193-4770-86c1-07a98d02f272

	measure 'INSTITUCIONES FINANCIERAS' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "54010202" ,"560102" , "47020102" ,"47020106" }
			----------------------------------------------------------------------------------
			/* === INSTITUCIONES FINANCIERAS === */
			VAR SumColumna_INSTITUCIONES_FINANCIERASG1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_INSTITUCIONES_FINANCIERASG1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_INSTITUCIONES_FINANCIERASG1_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_INSTITUCIONES_FINANCIERASG1
			VAR Ppto = SumColumna_INSTITUCIONES_FINANCIERASG1_ppto
			VAR REAL_Y_1 = SumColumna_INSTITUCIONES_FINANCIERASG1_Y1
			
			RETURN
			    SWITCH (
			        SELECTEDVALUE ( SelectorCalculo_IN2[TipoCalculo] ),
			        "Real Act.", COALESCE(DIVIDE(REAL_ACT,1000,0),0),
			        "Ppto",COALESCE(DIVIDE(Ppto,1000,0),0),
			        "Real Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			        "%CUMPLIMIENTO",COALESCE((DIVIDE(REAL_ACT,Ppto,0)*100),0),
			        "%VARIACIÓN VS PASADO" ,COALESCE((DIVIDE(REAL_ACT-REAL_Y_1,REAL_Y_1,0)*100),0)
			    )
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: 340c5c2c-b99a-463a-8325-81a08eee6026

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'BONOS DEL ESTADO' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "54010401", "560101", "47020101"}
			----------------------------------------------------------------------------------
			/* === BONOS DEL ESTADO === */
			VAR SumColumna_BONOS_DEL_ESTADOG1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,                        
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,                        
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,                        
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_BONOS_DEL_ESTADOG1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_BONOS_DEL_ESTADOG1_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_BONOS_DEL_ESTADOG1
			VAR Ppto = SumColumna_BONOS_DEL_ESTADOG1_ppto
			VAR REAL_Y_1 = SumColumna_BONOS_DEL_ESTADOG1_Y1
			
			RETURN
			    SWITCH (
			        SELECTEDVALUE (SelectorCalculo_IN2[TipoCalculo]),
			        "Real Act.", COALESCE(DIVIDE(REAL_ACT,1000,0),0),
			        "Ppto",COALESCE(DIVIDE(Ppto,1000,0),0),
			        "Real Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			        "%CUMPLIMIENTO",COALESCE((DIVIDE(REAL_ACT,Ppto,0)*100),0),
			        "%VARIACIÓN VS PASADO" ,COALESCE((DIVIDE(REAL_ACT-REAL_Y_1,REAL_Y_1,0)*100),0)
			    )
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: 19056460-85f6-4773-8be6-001c67704f21

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Cobertura de Inversión Obligatoria' = COALESCE(DIVIDE(gd_financiero_inversiones[InversionesAdmitidas],gd_financiero_inversiones[InversionesObligatorias],0),0)
		formatString: #,0
		displayFolder: Medida
		lineageTag: a99aa432-3f2f-4c87-be16-cdc841f078c0

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Rendimiento Portafolio' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "54010202", "54010401", "54010403", "54010701"}
			VAR CtasG2 = {"54020101"}
			----------------------------------------------------------------------------------
			/* === Rendimiento Portafolio === */
			VAR SumColumna_RendimientoPortafolioG1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,                        
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,                        
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,                        
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_RendimientoPortafolio_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[fuente_origen] = "FB",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			--------------------------------------------
			VAR SumColumna_RendimientoPortafolioG2 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,                        
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,                        
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,                        
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			-------------------------------------G2--Y-1
			VAR SumColumna_RendimientoPortafolioG2_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[fuente_origen] = "FR",
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_RendimientoPortafolioG1 + SumColumna_RendimientoPortafolioG2
			VAR REAL_Y_1 = SumColumna_RendimientoPortafolio_Y1 + SumColumna_RendimientoPortafolioG2_Y1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE ( ROUND ( DIVIDE ( YoY, REAL_Y_1, 0 ) * 100, 2 ), 0 )
			
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_IN[TipoCalculo] ),
			    "REAL ACT", COALESCE ( DIVIDE ( REAL_ACT, 1000, 0 ), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE ( DIVIDE ( YoY, 1000, 0 ), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: 026c88b9-3d31-4517-bc20-e83f9b5255bf

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'SOCIEDADES NO FINANCIERAS' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "54010701", "560103", "47020103","47020105","47020703"}
			----------------------------------------------------------------------------------
			/* === SOCIEDADES NO FINANCIERAS === */
			VAR SumColumna_SOCIEDADES_NO_FINANCIERAS_G1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,                        
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,                        
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,                        
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_SOCIEDADES_NO_FINANCIERAS_G1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_SOCIEDADES_NO_FINANCIERAS_G1_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_SOCIEDADES_NO_FINANCIERAS_G1
			VAR Ppto = SumColumna_SOCIEDADES_NO_FINANCIERAS_G1_Y1
			VAR REAL_Y_1 = SumColumna_SOCIEDADES_NO_FINANCIERAS_G1_ppto
			
			RETURN
			    SWITCH (
			        SELECTEDVALUE (SelectorCalculo_IN2[TipoCalculo]),
			        "Real Act.", COALESCE(DIVIDE(REAL_ACT,1000,0),0),
			        "Ppto",COALESCE(DIVIDE(Ppto,1000,0),0),
			        "Real Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			        "%CUMPLIMIENTO",COALESCE((DIVIDE(REAL_ACT,Ppto,0)*100),0),
			        "%VARIACIÓN VS PASADO" ,COALESCE((DIVIDE(REAL_ACT-REAL_Y_1,REAL_Y_1,0)*100),0)
			    )
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: d7ac2d57-9d1f-4bc4-8c65-1e6a5723163b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'INVERSIONES CORPORATIVAS LA FAVORITA' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "54020101", "54020501", "47020601"}
			VAR Cond1 = "021790016919001"
			----------------------------------------------------------------------------------
			/* === SOCIEDADES NO FINANCIERAS === */
			VAR SumColumna_SOCIEDADES_NO_FINANCIERAS_G1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1, 
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable]  IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_SOCIEDADES_NO_FINANCIERAS_G1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_SOCIEDADES_NO_FINANCIERAS_G1_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_SOCIEDADES_NO_FINANCIERAS_G1
			VAR Ppto = SumColumna_SOCIEDADES_NO_FINANCIERAS_G1_ppto
			VAR REAL_Y_1 =  SumColumna_SOCIEDADES_NO_FINANCIERAS_G1_Y1
			
			RETURN
			    SWITCH (
			        SELECTEDVALUE (SelectorCalculo_IN2[TipoCalculo]),
			        "Real Act.", COALESCE(DIVIDE(REAL_ACT,1000,0),0),
			        "Ppto",COALESCE(DIVIDE(Ppto,1000,0),0),
			        "Real Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			        "%CUMPLIMIENTO",COALESCE((DIVIDE(REAL_ACT,Ppto,0)*100),0),
			        "%VARIACIÓN VS PASADO" ,COALESCE((DIVIDE(REAL_ACT-REAL_Y_1,REAL_Y_1,0)*100),0)
			    )
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: ad25da06-7fa6-4a8c-b731-049729b9309e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'FONDO DE INVERSIÓN Y FIDEICOMISO' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "54020101", "54020501", "47020601"}
			VAR Cond1 = "021791305450001"
			----------------------------------------------------------------------------------
			/* === SOCIEDADES NO FINANCIERAS === */
			VAR SumColumna_SOCIEDADES_NO_FINANCIERAS_G1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1, 
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable]  IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_SOCIEDADES_NO_FINANCIERAS_G1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_SOCIEDADES_NO_FINANCIERAS_G1_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_SOCIEDADES_NO_FINANCIERAS_G1
			VAR Ppto = SumColumna_SOCIEDADES_NO_FINANCIERAS_G1_ppto
			VAR REAL_Y_1 =  SumColumna_SOCIEDADES_NO_FINANCIERAS_G1_Y1
			
			RETURN
			    SWITCH (
			        SELECTEDVALUE (SelectorCalculo_IN2[TipoCalculo]),
			        "Real Act.", COALESCE(DIVIDE(REAL_ACT,1000,0),0),
			        "Ppto",COALESCE(DIVIDE(Ppto,1000,0),0),
			        "Real Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			        "%CUMPLIMIENTO",COALESCE((DIVIDE(REAL_ACT,Ppto,0)*100),0),
			        "%VARIACIÓN VS PASADO" ,COALESCE((DIVIDE(REAL_ACT-REAL_Y_1,REAL_Y_1,0)*100),0)
			    )
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: 07ee1a43-98e0-4fa1-80c4-e70fa2d28449

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'INVERSIÓN EXTERIOR' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "11011001","11011101","11011002","11011102","11011003","11011103","11011004","11011104","11011005","11011105","11011006","11011106","11010601","11010602","11010603","11010701","11010702","11010703"
			}
			----------------------------------------------------------------------------------
			/* === INVERSIÓN EXTERIOR === */
			VAR SumColumna_INVERSION_EXTERIOR_G1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,                        
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,                        
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,                        
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_INVERSION_EXTERIOR_G1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_INVERSION_EXTERIOR_G1_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_INVERSION_EXTERIOR_G1
			VAR Ppto = SumColumna_INVERSION_EXTERIOR_G1_ppto
			VAR REAL_Y_1 = SumColumna_INVERSION_EXTERIOR_G1_Y1
			
			RETURN
			    SWITCH (
			        SELECTEDVALUE (SelectorCalculo_IN2[TipoCalculo]),
			        "Real Act.", COALESCE(DIVIDE(REAL_ACT,1000,0),0),
			        "Ppto",COALESCE(DIVIDE(Ppto,1000,0),0),
			        "Real Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			        "%CUMPLIMIENTO",COALESCE((DIVIDE(REAL_ACT,Ppto,0)*100),0),
			        "%VARIACIÓN VS PASADO" ,COALESCE((DIVIDE(REAL_ACT-REAL_Y_1,REAL_Y_1,0)*100),0)
			    )
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: 45e2a7c8-a495-48ca-93ed-a715a29ec01d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'TOTAL PORTAFOLIO' = [INSTITUCIONES FINANCIERAS] + [BONOS DEL ESTADO] + [SOCIEDADES NO FINANCIERAS] + [INVERSIÓN EXTERIOR]+ [INVERSIONES CORPORATIVAS LA FAVORITA]+[FONDO DE INVERSIÓN Y FIDEICOMISO]
		formatString: #,0
		displayFolder: Medida
		lineageTag: 815a25f5-af15-4f06-905f-65c3b5439fbf

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Real Act. INP' = CALCULATE([TOTAL PORTAFOLIO],SelectorCalculo_IN2[TipoCalculo]="Real Act.")
		formatString: #,0
		displayFolder: Medida
		lineageTag: aeeb0d32-2e96-4e28-b3bd-9a78d44c8c8d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Ppto INP' = CALCULATE([TOTAL PORTAFOLIO],SelectorCalculo_IN2[TipoCalculo]="Ppto")
		formatString: #,0
		displayFolder: Medida
		lineageTag: deb7c8a4-438e-4c84-bc25-bd22c118a67b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '%CUMPLIMIENTO INP' = CALCULATE([TOTAL PORTAFOLIO],SelectorCalculo_IN2[TipoCalculo]="%CUMPLIMIENTO")
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Medida
		lineageTag: 09d7bd35-c14a-4a8f-bd46-8b16384e34f6

	measure 'INGRESOS DE INVERSIONES' = ```
			
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "54010401","54010202","54010701","54010403","560101","560102","11011001","11011101","11011002","11011102","11011003","11011103","11011004","11011104","11011005","11011105","11011006","11011106","11010601","11010602","11010603","11010701","11010702","11010703","560103"}
			VAR CtasG2 = {"54020101"}
			VAR Cond1 = "021790016919001"
			VAR CtasG3 = {"54020501"}
			----------------------------------------------------------------------------------
			/* === INGRESOS DE INVERSIONES === */
			VAR SumColumna_INGRESOS_INVERSIONES_G1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_INGRESOS_INVERSIONES_G1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_INGRESOS_INVERSIONES_G1_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			--------------------------------
			VAR SumColumna_INGRESOS_INVERSIONES_G2 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                       gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_INGRESOS_INVERSIONES_G2_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_INGRESOS_INVERSIONES_G2_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			------------------------- G3
			VAR SumColumna_INGRESOS_INVERSIONES_G3 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id]<>Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                       gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_INGRESOS_INVERSIONES_G3_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_INGRESOS_INVERSIONES_G3_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			------------------------- G4
			VAR SumColumna_INGRESOS_INVERSIONES_G4 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                       gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_INGRESOS_INVERSIONES_G4_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_INGRESOS_INVERSIONES_G4_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			------------------------- G5
			VAR SumColumna_INGRESOS_INVERSIONES_G5 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id]<>Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                       gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_INGRESOS_INVERSIONES_G5_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_INGRESOS_INVERSIONES_G5_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			-----------------------------
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_INGRESOS_INVERSIONES_G1 + SumColumna_INGRESOS_INVERSIONES_G2 + SumColumna_INGRESOS_INVERSIONES_G3 +SumColumna_INGRESOS_INVERSIONES_G4 +SumColumna_INGRESOS_INVERSIONES_G5
			VAR Ppto = SumColumna_INGRESOS_INVERSIONES_G1_ppto + SumColumna_INGRESOS_INVERSIONES_G2_ppto + SumColumna_INGRESOS_INVERSIONES_G3_ppto+SumColumna_INGRESOS_INVERSIONES_G4_ppto+SumColumna_INGRESOS_INVERSIONES_G5_ppto
			VAR REAL_Y_1 = SumColumna_INGRESOS_INVERSIONES_G1_Y1 + SumColumna_INGRESOS_INVERSIONES_G2_Y1+SumColumna_INGRESOS_INVERSIONES_G3_Y1+SumColumna_INGRESOS_INVERSIONES_G4_Y1+SumColumna_INGRESOS_INVERSIONES_G5_Y1
			RETURN
			    SWITCH (
			        SELECTEDVALUE ( SelectorCalculo_IN2[TipoCalculo] ),
			        "Real Act.", COALESCE(DIVIDE(REAL_ACT,1000,0),0),
			        "Ppto",COALESCE(DIVIDE(Ppto,1000,0),0),
			        "Real Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			        "%CUMPLIMIENTO",COALESCE((DIVIDE(REAL_ACT,Ppto,0)*100),0),
			        "%VARIACIÓN VS PASADO" ,COALESCE((DIVIDE(REAL_ACT-REAL_Y_1,REAL_Y_1,0)*100),0)
			    )
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: eaf3c019-43a7-45b9-a2f9-0aa1e8b98643

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'EGRESOS DE INVERSIONES' = ```
			
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "47020101","47020102","47020106","47020103","47020105","47020703"}
			VAR CtasG2 = {"47020601"}
			VAR Cond1 = "021790016919001"
			----------------------------------------------------------------------------------
			/* === EGRESOS DE INVERSIONES === */
			VAR SumColumna_EGRESOS_DE_INVERSIONES_G1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_EGRESOS_DE_INVERSIONES_G1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_EGRESOS_DE_INVERSIONES_G1_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			--------------------------------
			VAR SumColumna_EGRESOS_DE_INVERSIONES_G2 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                       gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_EGRESOS_DE_INVERSIONES_G2_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_EGRESOS_DE_INVERSIONES_G2_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			------------------------- G3
			VAR SumColumna_EGRESOS_DE_INVERSIONES_G3 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id]<>Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                       gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_EGRESOS_DE_INVERSIONES_G3_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_EGRESOS_DE_INVERSIONES_G3_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			-----------------------------
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_EGRESOS_DE_INVERSIONES_G1 + SumColumna_EGRESOS_DE_INVERSIONES_G2 + SumColumna_EGRESOS_DE_INVERSIONES_G3 
			VAR Ppto = SumColumna_EGRESOS_DE_INVERSIONES_G1_ppto  + SumColumna_EGRESOS_DE_INVERSIONES_G2_ppto + SumColumna_EGRESOS_DE_INVERSIONES_G3_ppto
			VAR REAL_Y_1 = SumColumna_EGRESOS_DE_INVERSIONES_G1_Y1 + SumColumna_EGRESOS_DE_INVERSIONES_G2_Y1 +SumColumna_EGRESOS_DE_INVERSIONES_G3_Y1
			RETURN
			    SWITCH (
			        SELECTEDVALUE ( SelectorCalculo_IN2[TipoCalculo] ),
			        "Real Act.", COALESCE(DIVIDE(REAL_ACT,1000,0),0),
			        "Ppto",COALESCE(DIVIDE(Ppto,1000,0),0),
			        "Real Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			        "%CUMPLIMIENTO",COALESCE((DIVIDE(REAL_ACT,Ppto,0)*100),0),
			        "%VARIACIÓN VS PASADO" ,COALESCE((DIVIDE(REAL_ACT-REAL_Y_1,REAL_Y_1,0)*100),0)
			    )
			
			```
		formatString: #,0
		displayFolder: Medida
		lineageTag: c6c5a43b-a039-4cdc-89f2-1ca69c9e41c7

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'RESULTADO NETO INV.' = [INGRESOS DE INVERSIONES] - [EGRESOS DE INVERSIONES]
		formatString: #,0
		displayFolder: Medida
		lineageTag: 69ed8e35-cc9d-4b68-9d77-e12eb6bb2081

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Portafolio Budget' = [Inversión Neta PPTO] - ([Total No Admitida Ppto]+[Prohibiciones (IFIS Fideicomisos) ppto])
		displayFolder: Medida
		lineageTag: 613cff71-cdcc-46a4-a5af-9485e51581f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GRAFICOS INGRESOS DE INVERSIONES' = ```
			
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "54010401","54010202","54010701","54010403","560101","560102","11011001","11011101","11011002","11011102","11011003","11011103","11011004","11011104","11011005","11011105","11011006","11011106","11010601","11010602","11010603","11010701","11010702","11010703","560103"}
			VAR CtasG2 = {"54020101"}
			VAR Cond1 = "021790016919001"
			VAR CtasG3 = {"54020501"}
			----------------------------------------------------------------------------------
			/* === INGRESOS DE INVERSIONES === */
			VAR SumColumna_INGRESOS_INVERSIONES_G1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_INGRESOS_INVERSIONES_G1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_INGRESOS_INVERSIONES_G1_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			--------------------------------
			VAR SumColumna_INGRESOS_INVERSIONES_G2 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                       gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_INGRESOS_INVERSIONES_G2_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_INGRESOS_INVERSIONES_G2_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			------------------------- G3
			VAR SumColumna_INGRESOS_INVERSIONES_G3 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id]<>Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                       gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_INGRESOS_INVERSIONES_G3_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_INGRESOS_INVERSIONES_G3_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			------------------------- G4
			VAR SumColumna_INGRESOS_INVERSIONES_G4 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                       gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_INGRESOS_INVERSIONES_G4_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_INGRESOS_INVERSIONES_G4_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] = Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			------------------------- G5
			VAR SumColumna_INGRESOS_INVERSIONES_G5 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id]<>Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                       gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_INGRESOS_INVERSIONES_G5_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_saldo_balance] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_forecast] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			VAR SumColumna_INGRESOS_INVERSIONES_G5_ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado]),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <>Cond1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG3,
			                        gd_financiero_inversiones[cod_auxiliar_id] <> Cond1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			-----------------------------
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_INGRESOS_INVERSIONES_G1 + SumColumna_INGRESOS_INVERSIONES_G2 + SumColumna_INGRESOS_INVERSIONES_G3 +SumColumna_INGRESOS_INVERSIONES_G4 +SumColumna_INGRESOS_INVERSIONES_G5
			VAR Ppto = SumColumna_INGRESOS_INVERSIONES_G1_ppto + SumColumna_INGRESOS_INVERSIONES_G2_ppto + SumColumna_INGRESOS_INVERSIONES_G3_ppto+SumColumna_INGRESOS_INVERSIONES_G4_ppto+SumColumna_INGRESOS_INVERSIONES_G5_ppto
			VAR REAL_Y_1 = SumColumna_INGRESOS_INVERSIONES_G1_Y1 + SumColumna_INGRESOS_INVERSIONES_G2_Y1+SumColumna_INGRESOS_INVERSIONES_G3_Y1+SumColumna_INGRESOS_INVERSIONES_G4_Y1+SumColumna_INGRESOS_INVERSIONES_G5_Y1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE ( ROUND ( DIVIDE ( YoY, REAL_Y_1, 0 ) * 100, 2 ), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_IN[TipoCalculo] ),
			    "REAL ACT", COALESCE ( DIVIDE ( REAL_ACT, 1000, 0 ), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE ( DIVIDE ( YoY, 1000, 0 ), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		displayFolder: Medida
		lineageTag: c6e54e9c-88cc-4450-9740-b7bb7476cdf1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rendimiento Ppto' = CALCULATE([GRAFICOS INGRESOS DE INVERSIONES],SelectorCalculo_IN[TipoCalculo]="REAL ACT")/[Portafolio Budget]
		formatString: #,0
		displayFolder: Medida
		lineageTag: ba7d1f10-3346-416d-a7cc-370900a55e6a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Inversión Neta PPTO' = ```
			
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = {"11010806","11010103","11010203","11010303","11010403" }
			VAR CtasG2 = 
			    {"110301","11011001","11011101","11011002","11011102","11011003","11011103",
			    "11011004","11011104","11011005","11011105","11011006","11011106","11010601",
			    "11010602","11010603","11010701","11010702","11010703","11010805","11010905",
			    "11010906","11010801","11010802","11010803","11010804","11010102","11010202",
			    "11010302","11010402","11010101","11010201","11010301","11010401","11010501"
			    }
			
			----------------------------------------------------------------------------------
			/* === Total Inversiones Financieras === */
			VAR SumColumna_TotalInversionesFinancierasG1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_TotalInversionesFinancierasG2 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_TotalInversionesFinancierasG1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_TotalInversionesFinancierasG2_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG2,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = (SumColumna_TotalInversionesFinancierasG1 * 2) + SumColumna_TotalInversionesFinancierasG2
			VAR REAL_Y_1 = (SumColumna_TotalInversionesFinancierasG1_Y1 * 2) + SumColumna_TotalInversionesFinancierasG2_Y1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE ( ROUND ( DIVIDE ( YoY, REAL_Y_1, 0 ) * 100, 2 ), 0 )
			
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_IN[TipoCalculo] ),
			    "REAL ACT", COALESCE ( DIVIDE ( REAL_ACT, 1000, 0 ), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE ( DIVIDE ( YoY, 1000, 0 ), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		displayFolder: Medida
		lineageTag: e6d45d2b-1152-445b-adc2-7f9db7a4d79b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total No Admitida Ppto' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "11010303", "11010403"}
			----------------------------------------------------------------------------------
			/* === Total No Admitida === */
			VAR SumColumna_TotalNoAdmitidaG1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_TotalNoAdmitidaG1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_TotalNoAdmitidaG1
			VAR REAL_Y_1 = SumColumna_TotalNoAdmitidaG1_Y1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE ( ROUND ( DIVIDE ( YoY, REAL_Y_1, 0 ) * 100, 2 ), 0 )
			
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_IN[TipoCalculo] ),
			    "REAL ACT", COALESCE ( DIVIDE ( REAL_ACT, 1000, 0 ), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE ( DIVIDE ( YoY, 1000, 0 ), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		displayFolder: Medida
		lineageTag: 567ba562-6936-45e9-b3d8-1b0145c5aa17

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Prohibiciones (IFIS Fideicomisos) ppto' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX (
			        VALUES ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR ( PeriodoSeleccionado )
			VAR MesActual = MONTH ( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE ( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE ( MesActual_Inicio, -12 )
			VAR AnioAnterior = YEAR ( PeriodoAnterior )
			VAR MesAnterior = MONTH ( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesActual
			    )
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioActual, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( MesActual_Inicio, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE ( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE ( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) >= DATE ( AnioAnterior, 1, 1 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE ( Calendario[MesNombreAño] ) > EDATE ( PeriodoAnterior, -12 )
			            && DATEVALUE ( Calendario[MesNombreAño] ) <= EOMONTH ( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE ( SelectorValor[TipoValor] )
			VAR TipoData = SELECTEDVALUE ( SelectorData[TipoData] )
			
			-- Listas como TEXTO
			VAR CtasG1 = { "11010806"}
			----------------------------------------------------------------------------------
			/* === Prohibiciones (IFIS Fideicomisos) === */
			VAR SumColumna_ProhibicioneIFISFideicomisosG1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_ProhibicioneIFISFideicomisosG1_Y1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto_anualizado] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_financiero_inversiones[val_presupuesto] ),
			                        gd_financiero_inversiones[id_cuenta_contable] IN CtasG1,
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ProhibicioneIFISFideicomisosG1
			VAR REAL_Y_1 = SumColumna_ProhibicioneIFISFideicomisosG1_Y1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE ( ROUND ( DIVIDE ( YoY, REAL_Y_1, 0 ) * 100, 2 ), 0 )
			
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_IN[TipoCalculo] ),
			    "REAL ACT", COALESCE ( DIVIDE ( REAL_ACT, 1000, 0 ), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE ( DIVIDE ( YoY, 1000, 0 ), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		displayFolder: Medida
		lineageTag: 940c7fdc-3498-4ae1-bbab-d39a90463819

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fec_periodo
		dataType: string
		lineageTag: 16e30513-cc2c-46b0-863b-ee101cc91fec
		summarizeBy: none
		sourceColumn: fec_periodo

		annotation SummarizationSetBy = Automatic

	column des_tipo_ramo
		dataType: string
		lineageTag: 08eb405b-750e-4032-8131-aa0c68eeb7bb
		summarizeBy: none
		sourceColumn: des_tipo_ramo

		annotation SummarizationSetBy = Automatic

	column id_cuenta_contable
		dataType: string
		lineageTag: 8224cbf7-7391-4d57-b033-b5d5df274302
		summarizeBy: none
		sourceColumn: id_cuenta_contable

		annotation SummarizationSetBy = Automatic

	column cod_auxiliar_id
		dataType: string
		lineageTag: f8359ffb-726b-413a-ad56-db3932f89016
		summarizeBy: none
		sourceColumn: cod_auxiliar_id

		annotation SummarizationSetBy = Automatic

	column val_saldo_balance
		dataType: double
		lineageTag: b6952c9b-cea6-4911-a832-cf02c589960b
		summarizeBy: sum
		sourceColumn: val_saldo_balance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_anualizado
		dataType: double
		lineageTag: d932c33e-2ec1-42db-8104-d128119ec460
		summarizeBy: sum
		sourceColumn: val_saldo_anualizado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presupuesto
		dataType: double
		lineageTag: 8d46da65-055c-4d6d-a6a5-e3bd043ce916
		summarizeBy: sum
		sourceColumn: val_presupuesto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presupuesto_anualizado
		dataType: double
		lineageTag: 4d19d0ad-6cbb-4bd7-980a-52d725c1768d
		summarizeBy: sum
		sourceColumn: val_presupuesto_anualizado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast
		dataType: double
		lineageTag: c7826187-a84b-470e-90e5-525c267a2cd1
		summarizeBy: sum
		sourceColumn: val_forecast

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_anualizado
		dataType: double
		lineageTag: d66857b4-6423-43b0-a954-2a9c9293b2c7
		summarizeBy: sum
		sourceColumn: val_forecast_anualizado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fec_periodo_entero_IN =
			
			VALUE(gd_financiero_inversiones[fec_periodo] & "01")
		displayFolder: Columna
		lineageTag: d36c7bb7-6370-47a9-bbd7-87cca8e1bd20
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fec_periodo_fecha_IN = ```
			
			DATE(
			    LEFT(gd_financiero_inversiones[fec_periodo], 4),            
			    MID(gd_financiero_inversiones[fec_periodo], 5, 2),          
			    1                                               
			)
			```
		formatString: General Date
		displayFolder: Columna
		lineageTag: e115ce79-ff67-4d10-ab25-5ab23d87f540
		summarizeBy: none

		variation Variación
			isDefault
			relationship: b41e1d32-00f3-4c45-9462-f425bec4bbd2
			defaultHierarchy: LocalDateTable_0e71960a-1d44-4d57-a5fb-eb6d455acf8d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Ramo_IN =
			
			SWITCH(TRUE(),
			    SEARCH("GENERALES", 'gd_financiero_inversiones'[des_tipo_ramo], 1, 0) > 0, "NO VIDA",
			    SEARCH("VIDA", 'gd_financiero_inversiones'[des_tipo_ramo], 1, 0) > 0, "VIDA",
			    "Otros"
			)
		displayFolder: Columna
		lineageTag: d997efa0-cb98-41c9-84e4-992c3c69daee
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column cta_inversiones
		dataType: string
		lineageTag: 8766a135-3181-460a-9043-de34ecf293e0
		summarizeBy: none
		sourceColumn: cta_inversiones

		annotation SummarizationSetBy = Automatic

	column fuente_origen
		dataType: string
		lineageTag: 3ed04445-1816-4b0d-ada5-c8744324ce7c
		summarizeBy: none
		sourceColumn: fuente_origen

		annotation SummarizationSetBy = Automatic

	column val_saldo_balance_prev
		dataType: double
		lineageTag: 5968bdd7-9c5f-4df0-8992-1c55e0b227de
		summarizeBy: sum
		sourceColumn: val_saldo_balance_prev

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_anualizado_prev
		dataType: double
		lineageTag: 7ed464d4-e944-4d04-8cd0-d5dd37fd71f8
		summarizeBy: sum
		sourceColumn: val_saldo_anualizado_prev

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presupuesto_prev
		dataType: double
		lineageTag: 4cd0d9f1-f437-43de-8d9d-6dc38fbcaefe
		summarizeBy: sum
		sourceColumn: val_presupuesto_prev

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presupuesto_anualizado_prev
		dataType: double
		lineageTag: 4737fd0a-4287-4b8d-9499-7dda2f724e18
		summarizeBy: sum
		sourceColumn: val_presupuesto_anualizado_prev

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_prev
		dataType: double
		lineageTag: cba8a52a-b676-4c7d-b52e-3032804e5688
		summarizeBy: sum
		sourceColumn: val_forecast_prev

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_anualizado_prev
		dataType: double
		lineageTag: 4dcbee2c-1f72-4830-a22f-841255446b32
		summarizeBy: sum
		sourceColumn: val_forecast_anualizado_prev

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition gd_financiero_inversiones = m
		mode: import
		source =
				let
				    Origen = Databricks.Catalogs("adb-2683128165517039.19.azuredatabricks.net", "/sql/1.0/warehouses/7d4c90cb72eed782", [Catalog="ctlfinanciero", Database="schgold", QueryTags="vw_rt_financiero_inversiones", EnableAutomaticProxyDiscovery=null, Implementation=null]),
				    gd_financiero_inversiones_schgold_ctlfinanciero = Origen{[Item="gd_financiero_inversiones",Schema="schgold",Catalog="ctlfinanciero"]}[Data]
				in
				    gd_financiero_inversiones_schgold_ctlfinanciero

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

