table gd_financiero_general
	lineageTag: 3b489f1c-3960-46d8-9b56-0de663fdb5bb

	measure 'Real Y-1_BG' = ```
			
			VAR TipoData = SELECTEDVALUE(SelectorData[TipoData])
			VAR TipoPasivo = SELECTEDVALUE(gd_financiero_general[cta_des_bg_n2])
			VAR PeriodoSeleccionado = MAX(Calendario[MesNombreAño])
			VAR TienePeriodoSeleccionado = HASONEVALUE(Calendario[MesNombreAño])
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			
			VAR PeriodoAnterior = EDATE(PeriodoSeleccionado, -12)
			VAR AnioAnterior = YEAR(PeriodoAnterior)
			VAR MesAnterior = MONTH(PeriodoAnterior)
			
			RETURN
			SWITCH (
			    TRUE(),
			    TipoData = "Real",
			        SWITCH (
			            TRUE(),
			
			            // ---- Anualizado ----
			            TipoValor = "Anualizado",                  
			                        
			                           SUM(gd_financiero_general[val_saldo_anualizado_y_1]),
			            // ---- Mensualizado ----
			            TipoValor = "Mensualizado",          
			                        
			                           SUM(gd_financiero_general[val_saldo_balance_y_1_real])
			
			                    ,
			            // ---- Acumulado ----
			            TipoValor = "Acumulado",
			                         SUM(gd_financiero_general[val_saldo_balance_acumulado_y_1_real])
			
			            
			        ,
			    TipoData = "Presupuesto",
			        SWITCH (
			            TRUE(),
			
			            // ---- Anualizado ----
			            TipoValor = "Anualizado",
			
			                    SUM(gd_financiero_general[val_presupuesto_anualizado_y_1]),
			
			            // ---- Mensualizado ----
			            TipoValor = "Mensualizado",
			
			                    SUM(gd_financiero_general[val_presupuesto_y_1]),
			
			            // ---- Acumulado ----
			            TipoValor = "Acumulado",
			                    SUM(gd_financiero_general[val_presupuesto_acumulado_y_1])
			                   
			            
			        ),
			    TipoData = "Forecast",
			        SWITCH (
			            TRUE(),
			
			            // ---- Anualizado ----
			            TipoValor = "Anualizado",
			
			                    SUM(gd_financiero_general[val_forecast_anualizado_y_1]),
			
			
			            // ---- Mensualizado ----
			            TipoValor = "Mensualizado",
			
			                    SUM(gd_financiero_general[val_forecast_y_1]),
			
			
			            // ---- Acumulado ----
			            TipoValor = "Acumulado",
			
			                    SUM(gd_financiero_general[val_forecast_acumulado_y_1])
			
			
			
			        )
			))
			```
		displayFolder: Medidas
		lineageTag: 828ae701-c6c5-4bd3-a93e-c705d37a8c14

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YoY_BG = [Real Act_BG] - [Real Y-1_BG]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Medidas
		lineageTag: 1af888dd-3aa6-459b-885b-242f77031d99

	measure %YoY_BG = DIVIDE([YoY_BG],[Real Y-1_BG],0)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Medidas
		lineageTag: 590fa391-5980-4a8f-b887-1439a4393560

	measure Activos_BG = ```
			
			COALESCE(CALCULATE(
			    [Real Act_BG],
			     gd_financiero_general[TipoCuenta_BG] = "ACTIVOS"
			),0)/1000
			
			```
		formatString: #,0
		displayFolder: Medidas
		lineageTag: 87ac99be-9411-4552-83cf-eace775387bb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Pasivos_BG =
			
			COALESCE(CALCULATE(
			    [Real Act_BG],
			    gd_financiero_general[TipoCuenta_BG] = "PASIVOS"
			),0)/1000
		formatString: #,0
		displayFolder: Medidas
		lineageTag: 49543033-1067-4e83-bea6-5d9157071911

		annotation PBI_FormatHint = {"isDecimal":true}

	measure FechaMaxCargaTexto_BG = ```
			
			VAR FechaMax =
			    CALCULATE (
			        MAX ( gd_financiero_general[fec_periodo_fecha_BG] ),
			        ALL ( gd_financiero_general )
			    )
			VAR MesAbrevRaw = FORMAT ( FechaMax, "MMM" )         -- abreviado
			VAR MesSinPunto  = SUBSTITUTE ( MesAbrevRaw, ".", "" )
			VAR MesCap       = UPPER ( LEFT ( MesSinPunto, 1 ) ) &
			                   LOWER ( MID ( MesSinPunto, 2, LEN ( MesSinPunto ) - 1 ) )
			VAR Mes3         = LEFT ( MesCap, 3 )                 -- asegura "Dic", "Sep", etc.
			RETURN
			    IF ( ISBLANK ( FechaMax ), BLANK (), Mes3 & " " & FORMAT ( FechaMax, "yyyy" ) )
			
			
			
			```
		displayFolder: Medidas
		lineageTag: 5a1f5bb5-f987-4b1b-9073-bc0f22cd5ea4

	measure 'Real Act_BG' = ```
			
			VAR TipoPasivo = SELECTEDVALUE(gd_financiero_general[cta_desc_bg])
			VAR PeriodoSeleccionado = MAX(Calendario[MesNombreAño])
			VAR AnioActual = YEAR(PeriodoSeleccionado)
			VAR MesActual = MONTH(PeriodoSeleccionado)
			-- Normalizo a primer día del mes
			
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[Date] ),
			        Calendario[Date] >= DATE ( AnioActual, 1, 1 )
			            && Calendario[Date] <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			
			    
			RETURN
			SWITCH(
			    SELECTEDVALUE(SelectorData[TipoData]),
			    "Real",
			        SWITCH(
			            SELECTEDVALUE(SelectorValor[TipoValor]),
			
			            // Anualizado
			            "Anualizado", 
			                    SWITCH ( 
			                        SELECTEDVALUE(gd_financiero_general[cta_desc_bg]),
			                        "Otros Pasivos",
			                           1,
			                           SUM(gd_financiero_general[val_saldo_anualizado])
			                    ),
			
			            // Mensualizado
			            "Mensualizado", 
			
			                  
			                           SUM(gd_financiero_general[val_saldo_balance_real])
			                    ,
			
			            // Acumulado
			            "Acumulado",               
			
			                           SUM(gd_financiero_general[val_saldo_balance_acumulado_real])
			               
			                        
			        ),
			    "Presupuesto",
			        SWITCH(
			            SELECTEDVALUE(SelectorValor[TipoValor]),
			
			            // Anualizado
			            "Anualizado", 
			                SUM(gd_financiero_general[val_presupuesto_anualizado]),
			
			            // Mensualizado
			            "Mensualizado", 
			
			                    SUM(gd_financiero_general[val_presupuesto]),
			
			
			
			            // Acumulado
			            "Acumulado",             
			                    
			                        SUM(gd_financiero_general[val_presupuesto_acumulado])
			
			        ),
			    "Forecast",
			        SWITCH(
			            SELECTEDVALUE(SelectorValor[TipoValor]),
			
			            // Anualizado
			            "Anualizado", 
			                SUM(gd_financiero_general[val_forecast_anualizado]),
			
			            // Mensualizado
			            "Mensualizado", 
			                    SUM(gd_financiero_general[val_forecast]),
			
			            // Acumulado
			            "Acumulado", 
			                        SUM(gd_financiero_general[val_forecast_acumulado])
			        )
			)
			```
		displayFolder: Medidas
		lineageTag: adf4fb17-a34a-4d6c-96b4-40ea276a714c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Real Act Cuentas_BG' =
			
			SWITCH(
			    SELECTEDVALUE(SelectorData[TipoData]),
			    "Real",
			        SUM(gd_financiero_general[val_saldo_balance]),
			    "Presupuesto",
			        SUM(gd_financiero_general[val_presupuesto]),
			    "Forecast",
			        SUM(gd_financiero_general[val_forecast]),
			    // Default
			    SUM(gd_financiero_general[val_saldo_balance])
			)
		displayFolder: Medidas
		lineageTag: 84fac36c-2e83-4bd6-92a9-92999f97158c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Patrimonio_BG = ```
			
			COALESCE(CALCULATE(
			    [Real Act_BG],
			    gd_financiero_general[TipoCuenta_BG] = "PATRIMONIO"
			),0)/1000 
			```
		displayFolder: Medidas
		lineageTag: d3aebd79-dfa5-401d-bd67-48d532649fe8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure FiltroAñoDinamico_BG = ```
			
			VAR SelectedMinDate = CALCULATE( MIN ( gd_financiero_general[fec_periodo_fecha_BG] ), ALLSELECTED ( gd_financiero_general ) )
			VAR SelectedMaxDate = CALCULATE( MAX ( gd_financiero_general[fec_periodo_fecha_BG] ), ALLSELECTED ( gd_financiero_general ) )
			VAR HaySeleccion    = NOT ISBLANK ( SelectedMinDate ) && NOT ISBLANK ( SelectedMaxDate )
			
			-- Si hay selección de período: toma el año de la selección (basta con el Máx).
			-- Si no hay selección: toma el año actual.
			VAR TargetYear =
			    IF ( HaySeleccion, YEAR ( SelectedMaxDate ), YEAR ( TODAY() ) )
			
			-- Año del contexto actual del visual (barra/mes) calculado desde la fecha real
			VAR YearEnContexto = YEAR ( MAX ( gd_financiero_general[fec_periodo_fecha_BG] ) )
			
			RETURN
			    IF ( YearEnContexto = TargetYear, 1, 0 )
			
			
			```
		formatString: 0
		displayFolder: Medidas
		lineageTag: 59413ecf-2cb4-4b8f-be74-2e874f088c76

	measure 'ROE Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR Ingresos_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "5",
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR Gastos_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR Patrimonio_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "3",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			RETURN
			COALESCE ( DIVIDE ( Ingresos_Mes - Gastos_Mes, Patrimonio_Mes, 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: af383750-967f-4891-9521-08245ff7b275

	measure FiltroAñoDinamico_KPI_BG = ```
			
			VAR SelectedMinDate = CALCULATE( MIN ( gd_financiero_general[fec_periodo_fecha_BG] ), ALLSELECTED ( gd_financiero_general ) )
			VAR SelectedMaxDate = CALCULATE( MAX ( gd_financiero_general[fec_periodo_fecha_BG] ), ALLSELECTED ( gd_financiero_general ) )
			VAR HaySeleccion    = NOT ISBLANK ( SelectedMinDate ) && NOT ISBLANK ( SelectedMaxDate )
			
			-- Si hay selección de período: toma el año de la selección (basta con el Máx).
			-- Si no hay selección: toma el año actual.
			VAR TargetYear =
			    IF ( HaySeleccion, YEAR ( SelectedMaxDate ), YEAR ( TODAY() ) )
			
			-- Año del contexto actual del visual (barra/mes) calculado desde la fecha real
			VAR YearEnContexto = YEAR ( MAX ( gd_financiero_general[fec_periodo_fecha_BG] ) )
			
			RETURN
			    IF ( YearEnContexto = TargetYear, 1, 0 )
			
			```
		formatString: 0
		displayFolder: KPI
		lineageTag: 971260a7-b745-4cf1-8627-bc265e300af2

	measure 'ROE Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR Ingresos_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "5",
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR Gastos_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR Patrimonio_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "3",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			RETURN
			COALESCE ( DIVIDE ( Ingresos_PM - Gastos_PM, Patrimonio_PM, 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 45b73903-f84b-4fae-aa5b-1babbfcd1861

	measure 'Real Act_BG_1000' = DIVIDE([Real Act_BG], 1000,0)
		formatString: #,0
		displayFolder: Medidas
		lineageTag: f216a3c2-dda0-4895-bead-1eb7dc678965

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Real Y-1_1000' = DIVIDE([Real Y-1_BG],1000,0)
		formatString: #,0
		displayFolder: Medidas
		lineageTag: e76216c1-0290-4650-a07d-4155cdb55fea

		annotation PBI_FormatHint = {"isDecimal":true}

	measure YoY_BG_1000 = DIVIDE([YoY_BG],1000,0)
		formatString: #,0
		displayFolder: Medidas
		lineageTag: b3851d51-fc49-47a2-a5fd-118d2abac85c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'PERIODO PASADO KPI' = ```
			
			"PERIODO PASADO: "
			
			```
		displayFolder: KPI
		lineageTag: 0d4e2677-bb54-4ead-99b3-01285a966eff

	measure Filtro4MesesDinamico_KPI = ```
			
			VAR SelectedMinDate =
			    CALCULATE ( MIN ( gd_financiero_general[fec_periodo_fecha_BG] ), ALLSELECTED ( gd_financiero_general ) )
			VAR SelectedMaxDate =
			    CALCULATE ( MAX ( gd_financiero_general[fec_periodo_fecha_BG] ), ALLSELECTED ( gd_financiero_general ) )
			VAR HaySeleccion =
			    NOT ISBLANK ( SelectedMinDate ) && NOT ISBLANK ( SelectedMaxDate )
			
			VAR FechaFinRef =
			    IF (
			        HaySeleccion,
			        SelectedMaxDate,
			        CALCULATE ( MAX ( gd_financiero_general[fec_periodo_fecha_BG] ), ALL ( gd_financiero_general ) )
			    )
			
			-- Ventana de 4 meses (incluye mes fin)
			VAR FechaFinEOM    = EOMONTH ( FechaFinRef, 0 )
			VAR FechaInicioEOM = EOMONTH ( FechaFinRef, -3 )
			
			VAR EndOrd   = YEAR ( FechaFinEOM ) * 100 + MONTH ( FechaFinEOM )
			VAR StartOrd = YEAR ( FechaInicioEOM ) * 100 + MONTH ( FechaInicioEOM )
			
			VAR ThisOrd =
			    YEAR ( MAX ( gd_financiero_general[fec_periodo_fecha_BG] ) ) * 100
			        + MONTH ( MAX ( gd_financiero_general[fec_periodo_fecha_BG] ) )
			
			RETURN
			IF ( ThisOrd >= StartOrd && ThisOrd <= EndOrd, 1, 0 )
			
			```
		formatString: 0
		displayFolder: KPI
		lineageTag: ccb0096d-7b4b-411c-904a-4af9aaafda7f

	measure 'ROA Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR Ingresos_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "5",
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR Gastos_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR Activo_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "1",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			RETURN
			COALESCE ( DIVIDE ( Ingresos_Mes - Gastos_Mes, Activo_Mes, 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 37b90fe2-7880-4b75-8aeb-64b92ac1fc57

	measure 'ROA Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR Ingresos_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "5",
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR Gastos_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR Activo_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "1",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			RETURN
			COALESCE ( DIVIDE ( Ingresos_PM - Gastos_PM, Activo_PM, 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 4ce20238-62e9-43b8-8865-2e90cbae1ed0

	measure 'ROS Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR Ingresos_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "5",
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR Gastos_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR PrimaEmitida51_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "51",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR LiquidacionesRescates45_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "45",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			    VAR Coaseguro4403_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4403",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			RETURN
			COALESCE ( DIVIDE ( Ingresos_Mes - Gastos_Mes, PrimaEmitida51_Mes-LiquidacionesRescates45_Mes-Coaseguro4403_Mes , 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: cf95edea-f393-4382-95d8-6f1c3f0c0699

	measure 'ROS Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR Ingresos_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "5",
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR Gastos_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR PrimaEmitida51_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "51",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			    
			VAR Liquidaciones45_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "45",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR Coaseguro4403_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4403",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			RETURN
			COALESCE ( DIVIDE ( Ingresos_PM - Gastos_PM, PrimaEmitida51_PM-Liquidaciones45_PM-Coaseguro4403_PM, 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: ac68e23f-3308-4b1f-8c05-ad9b01ad738f

	measure 'LIQUIDEZ Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR GRUPO1_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"1101", "1102", "12", "13", "1402"} ,
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR GRUPO2_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"120102", "120202", "120203"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			VAR NUMERADOR = GRUPO1_Mes-GRUPO2_Mes
			
			VAR GRUPO3_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"2101", "2102", "2103", "2104", "2105", "2106", "22", "23", "2401", "25"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR GRUPO4_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "259006",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			VAR DENOMINADOR = GRUPO3_Mes-GRUPO4_Mes
			
			RETURN
			COALESCE ( DIVIDE ( NUMERADOR, DENOMINADOR , 0 ), 0 )
			
			```
		formatString: #,0.00
		displayFolder: KPI
		lineageTag: bda183dd-68e4-44c6-86b3-d532b0d6d025

	measure 'LIQUIDEZ Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR GRUPO1_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"1101", "1102", "12", "13", "1402"} ,
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR GRUPO2_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"120102", "120202", "120203"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			VAR NUMERADOR = GRUPO1_PM-GRUPO2_PM
			VAR GRUPO3_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"2101", "2102", "2103", "2104", "2105", "2106", "22", "23", "2401", "25"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			    
			VAR GRUPO4_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "259006",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR Coaseguro4403_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4403",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR DENOMINADOR = GRUPO3_PM-GRUPO4_PM
			
			RETURN
			COALESCE ( DIVIDE ( NUMERADOR, DENOMINADOR , 0 ), 0 )
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: ea81b738-b1b0-4fc1-bc2d-60384a440e17

	measure 'LIQUIDEZ INMEDIATA Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR GRUPO1_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"1101", "1102"} ,
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR GRUPO2_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"2101", "2102", "2103", "2104", "2105", "2106", "22", "23", "2401", "25"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR GRUPO3_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = {"259006"
			},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR DENOMINADOR = GRUPO2_Mes-GRUPO3_Mes
			
			RETURN
			COALESCE ( DIVIDE ( GRUPO1_Mes, DENOMINADOR , 0 ), 0 )
			
			```
		formatString: #,0.00
		displayFolder: KPI
		lineageTag: e745419d-8947-4f23-9797-a7ad7aa459f1

	measure 'LIQUIDEZ INMEDIATA Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR GRUPO1_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"1101", "1102"} ,
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR GRUPO2_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"2101", "2102", "2103", "2104", "2105", "2106", "22", "23", "2401", "25"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR GRUPO3_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "259006",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			 
			
			VAR DENOMINADOR = GRUPO2_PM-GRUPO3_PM
			
			RETURN
			COALESCE ( DIVIDE ( GRUPO1_PM, DENOMINADOR , 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 177ec938-6692-45e8-87ae-04168830fd8a

	measure 'GASTOS Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR Ingresos_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "5",
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR CUENTA410113_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "410113",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR PrimaEmitida51_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "51",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR LiquidacionesRescates45_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "45",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			    VAR Coaseguro4403_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4403",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			RETURN
			COALESCE ( DIVIDE ( Ingresos_Mes - CUENTA410113_Mes, PrimaEmitida51_Mes-LiquidacionesRescates45_Mes-Coaseguro4403_Mes , 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 34bf25f3-4e3d-44d1-abf2-1d9a3ce20f02

	measure 'GASTOS Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR Ingresos_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "5",
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR CUENTA410113_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "410113",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR PrimaEmitida51_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "51",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			    
			VAR Liquidaciones45_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "45",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR Coaseguro4403_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4403",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			RETURN
			COALESCE ( DIVIDE ( Ingresos_PM - CUENTA410113_PM, PrimaEmitida51_PM-Liquidaciones45_PM-Coaseguro4403_PM, 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: f159038e-46e4-4fed-a3b0-ec8f9a3ff658

	measure 'COMISIONES Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR CUENTA42_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "42",
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR CUENTA420490_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "420490",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR PrimaEmitida51_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "51",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR LiquidacionesRescates45_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "45",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			    VAR Coaseguro4403_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4403",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			RETURN
			COALESCE ( DIVIDE ( CUENTA42_Mes - CUENTA420490_Mes, PrimaEmitida51_Mes-LiquidacionesRescates45_Mes-Coaseguro4403_Mes , 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: d496d4f8-e742-4f46-83d7-e4749c77c553

	measure 'COMISIONES Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR CUENTA42_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "42",
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR CUENTA420490_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "420490",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR PrimaEmitida51_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "51",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			    
			VAR Liquidaciones45_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "45",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR Coaseguro4403_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4403",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			RETURN
			COALESCE ( DIVIDE ( CUENTA42_PM - CUENTA420490_PM, PrimaEmitida51_PM-Liquidaciones45_PM-Coaseguro4403_PM, 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 76ab4990-2bd1-44a0-ad1a-158ed94bb172

	measure 'SINIESTRALIDAD Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR GRUPO1_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"46", "4803"} ,
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR GRUPO2_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"53", "5703"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR GRUPO3_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"51","5701", "5702"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR GRUPO4_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"45", "44", "4801", "4802"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			
			RETURN
			COALESCE ( DIVIDE ( GRUPO1_Mes - GRUPO2_Mes, GRUPO3_Mes-GRUPO4_Mes , 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 77add115-90a3-47bb-9951-c2785cdeee2a

	measure 'SINIESTRALIDAD Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR GRUPO1_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"46", "4803"} ,
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR GRUPO2_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable]  IN {"53", "5703"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR GRUPO3_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable]  IN {"51","5701", "5702"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			 VAR GRUPO4_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable]  IN {"45", "44", "4801", "4802"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			RETURN
			COALESCE ( DIVIDE ( GRUPO1_PM - GRUPO2_PM, GRUPO3_PM- GRUPO4_PM , 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 69f383a1-7f99-4808-a817-2c804283b151

	measure 'SINIESTRALIDAD INCURRIDA Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR GRUPO1_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"46","480301"} ,
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR GRUPO2_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"570301","53"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR GRUPO3_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"5701","5702","51"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR GRUPO4_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"45","44","4801","4802","43"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			
			RETURN
			COALESCE ( DIVIDE ( GRUPO1_Mes - GRUPO2_Mes, GRUPO3_Mes-GRUPO4_Mes , 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: e297290f-2ad8-4f6b-ad2b-b253b3697dc8

	measure 'SINIESTRALIDAD INCURRIDA Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR GRUPO1_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"46", "480301"} ,
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR GRUPO2_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable]  IN {"570301","53"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR GRUPO3_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable]  IN  {"5701","5702","51"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			 VAR GRUPO4_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable]  IN {"45","44","4801","4802","43"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			RETURN
			COALESCE ( DIVIDE ( GRUPO1_PM - GRUPO2_PM, GRUPO3_PM- GRUPO4_PM , 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 5642dd5d-3fc5-4c69-9131-a1cc0b2ae2ac

	measure 'RAZON COMBINADA Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR GRUPO1_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"46", "4803", "41", "42"} ,
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR GRUPO2_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"53", "5703", "410113", "52", "420490"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR GRUPO3_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"51","5701", "5702", "5704", "5705", "5706"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR GRUPO4_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN { "45", "44", "4801", "4802", "4804", "4805", "4806"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			
			RETURN
			COALESCE ( DIVIDE ( GRUPO1_Mes - GRUPO2_Mes, GRUPO3_Mes-GRUPO4_Mes , 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: caabbca6-791f-4b8a-a9f5-d4f84232daa7

	measure 'RAZON COMBINADA Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR GRUPO1_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"46", "4803", "41", "42"} ,
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR GRUPO2_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable]  IN {"53", "5703", "410113", "52", "420490"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR GRUPO3_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable]  IN   {"51","5701", "5702", "5704", "5705", "5706"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			 VAR GRUPO4_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable]  IN { "45", "44", "4801", "4802", "4804", "4805", "4806"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			RETURN
			COALESCE ( DIVIDE ( GRUPO1_PM - GRUPO2_PM, GRUPO3_PM- GRUPO4_PM , 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 3665027a-9faf-4b86-a571-238014de7435

	measure 'PAT/PRIMA NETA EMITIDA Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR CUENTA1_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "3",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR CUENTA2_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "51",
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR CUENTA3_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "45",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			VAR CUENTA4_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4403",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			RETURN
			COALESCE ( DIVIDE ( CUENTA1_MES , CUENTA2_MES - CUENTA3_MES - CUENTA4_MES, 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 1a92c820-364c-479f-ba04-6da44501b1b9

	measure 'PAT/PRIMA NETA EMITIDA Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR CUENTA1_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "3",
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR CUENTA2_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "51",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR CUENTA3_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "45",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			    
			VAR CUENTA4_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4403",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			RETURN
			COALESCE ( DIVIDE ( CUENTA1_PM , CUENTA2_PM - CUENTA3_PM - CUENTA4_PM, 0 ), 0 )
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 421218dc-cbb7-4625-987c-41136b01b133

	measure 'REND FINANCIERO CONTABLE Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR G1_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] in {"54","55","470204"},
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR G2_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"4701","4702"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR G3_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "1101",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			
			RETURN
			COALESCE ( DIVIDE ( G1_Mes - G2_Mes, G3_Mes , 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: c4c3c9e0-6700-48a1-97f8-c783bf242dcf

	measure 'REND FINANCIERO CONTABLE Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR G1_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable]in {"54","55","470204"},
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR G2_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"4701","4702"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR G3_PM =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "1101",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			    
			
			
			RETURN
			COALESCE ( DIVIDE ( G1_PM - G2_PM, G3_PM , 0 ), 0 )
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: cbce7416-98c2-4048-a144-2032cb7a312e

	measure 'GASTOS/RT Max Periodo' =
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR G1_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] in {"41"},
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR G2_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"410113"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			VAR NUMERADOR = G1_Mes - G2_Mes
			VAR G3_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] in {"42010102", "42010103", "42010202", "42010203", "4201030302", "4201030303", "4201030502", "4201030503", "4201030902", "4201030903", "4201031002", "4201031003", "4201031302", "4201031303", "4201031402", "4201031403", "4201031802", "4201031803", "4201032902", "4201032903", "4201033002", "4201033003", "4202", "42049010", "42049003", "42049012", "42049030", "42049004", "42049005", "42049011"
			},
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			VAR G4_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"4201"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			VAR COMISIONESGANADAS = G4_Mes - G3_Mes
			VAR G5_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"5705","4804"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			VAR G6_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"4805","5704"},
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			VAR RESERVA = G5_Mes-G6_Mes
			VAR DENOMINADOR = COMISIONESGANADAS + RESERVA
			RETURN
			COALESCE ( DIVIDE ( NUMERADOR, DENOMINADOR, 0 ), 0 )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 4d2e19b4-ca52-4f9e-b22e-d34eded84b10

	measure 'GASTOS/RT Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR G1_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] in {"41"},
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR G2_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"410113"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			VAR NUMERADOR = G1_Mes - G2_Mes
			VAR G3_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] in {"42010102", "42010103", "42010202", "42010203", "4201030302", "4201030303", "4201030502", "4201030503", "4201030902", "4201030903", "4201031002", "4201031003", "4201031302", "4201031303", "4201031402", "4201031403", "4201031802", "4201031803", "4201032902", "4201032903", "4201033002", "4201033003", "4202", "42049010", "42049003", "42049012", "42049030", "42049004", "42049005", "42049011"
			},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			VAR G4_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] IN {"4201"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			VAR COMISIONESGANADAS = G4_Mes - G3_Mes
			VAR G5_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable]  IN {"5705","4804"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			VAR G6_Mes =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable]  IN {"4805","5704"},
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			VAR RESERVA = G5_Mes-G6_Mes
			VAR DENOMINADOR = COMISIONESGANADAS + RESERVA
			RETURN
			COALESCE ( DIVIDE ( NUMERADOR, DENOMINADOR, 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: ad4ea270-a267-4c3d-88b5-a95b0393a642

	measure '%AJUSTE RESERVA/PB Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR G1_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "51",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR G2_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "45",
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR PB = G1_MES - G2_MES
			
			VAR G3_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "5701",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			VAR G4_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "5702",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			VAR ReservaTecMas = G3_MES + G4_MES
			
			VAR G5_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4701",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			VAR G6_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4702",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			VAR ReservaTecMenos = G5_MES+G6_MES
			RETURN
			COALESCE ( DIVIDE (ReservaTecMas - ReservaTecMenos, PB , 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: d68f2e98-debc-42bb-a0f5-debd51ef9fcf

	measure '%AJUSTED RESERVA/PB Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR G1_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "51",
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR G2_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "45",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			VAR PB = G1_MES - G2_MES
			
			VAR G3_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "5701",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			VAR G4_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "5702",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			VAR ReservaTecMas = G3_MES + G4_MES
			
			VAR G5_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4701",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			VAR G6_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "4702",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			VAR ReservaTecMenos = G5_MES+G6_MES
			
			RETURN
			COALESCE ( DIVIDE (ReservaTecMas - ReservaTecMenos, PB , 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: b43a1f9c-e5fb-4d4d-bc98-4dde56d0d5a5

	measure '%COSTOS EXCESOS/PB Max Periodo' = ```
			
			VAR SelectedDate =
			    // Si hay filtro (por MesNombreAño u otro), toma la fecha máxima en contexto.
			    // Si no hay filtro, toma la última fecha disponible del Calendario.
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR SelYear  = YEAR ( SelectedDate )
			VAR SelMonth = MONTH ( SelectedDate )
			
			VAR G1_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "51",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR G2_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "45",
			        // Quitamos filtros previos de Año/Mes y fijamos el mes-año objetivo
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			VAR G3_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "43",
			        REMOVEFILTERS ( 'Calendario'[Año], 'Calendario'[Mes] ),
			        KEEPFILTERS ( 'Calendario'[Año] = SelYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = SelMonth )
			    )
			
			
			RETURN
			COALESCE ( DIVIDE ( G3_MES , G1_MES-G2_MES, 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 591620cc-ac1d-49e7-830b-30b3e93dc2f0

	measure '%COSTOS EXCESOS/PB Max Periodo Anterior' = ```
			
			VAR CurrentDate =
			    COALESCE(
			        MAX ( 'Calendario'[Date] ),
			        CALCULATE ( MAX ( 'Calendario'[Date] ), ALL ( 'Calendario' ) )
			    )
			VAR PrevDate  = EOMONTH ( CurrentDate, -1 )
			VAR PrevYear  = YEAR ( PrevDate )
			VAR PrevMonth = MONTH ( PrevDate )
			
			VAR G1_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "51",
			        REMOVEFILTERS ( 'Calendario' ),             
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR G2_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "45",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			
			VAR G3_MES =
			    CALCULATE (
			        SUM ( gd_financiero_general[val_saldo_balance] ),
			        gd_financiero_general[id_cuenta_contable] = "43",
			        REMOVEFILTERS ( 'Calendario' ),
			        KEEPFILTERS ( 'Calendario'[Año] = PrevYear ),
			        KEEPFILTERS ( 'Calendario'[Mes] = PrevMonth )
			    )
			RETURN
			COALESCE ( DIVIDE ( G3_MES , G1_MES-G2_MES, 0 ), 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI
		lineageTag: 63df3368-71ae-4c79-9c82-ecb6360cdd1b

	measure 'Última Fecha Cargada' =
			
			CALCULATE( MAX( gd_financiero_general[fec_periodo_fecha_BG] ), ALL( gd_financiero_general ) )
		formatString: General Date
		displayFolder: Medidas
		lineageTag: e429b0e3-1df4-41c6-8716-71ca2e7eacf6

	measure 'Otros Pasivos' = CALCULATE(SUM(gd_financiero_general[val_saldo_balance]),gd_financiero_general[cta_desc_bg] = "Otros Pasivos")-CALCULATE(SUM(gd_financiero_general[val_saldo_balance]),gd_financiero_general[cta_desc_bg] = "Primas anticipadas")
		displayFolder: Medidas
		lineageTag: 680db8d1-1823-480c-a7e2-bfb5c307b4d2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RE_BG = ```
			
			VAR TipoPasivo = SELECTEDVALUE(gd_financiero_general[cta_des_bg_n2])
			VAR PeriodoSeleccionado = MAX(Calendario[MesNombreAño])
			VAR AnioActual = YEAR(PeriodoSeleccionado)
			VAR MesActual = MONTH(PeriodoSeleccionado)
			-- Normalizo a primer día del mes
			
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[Date] ),
			        Calendario[Date] >= DATE ( AnioActual, 1, 1 )
			            && Calendario[Date] <= EOMONTH ( MesActual_Inicio, 0 )
			    )
			
			
			    
			RETURN
			SWITCH(
			    SELECTEDVALUE(SelectorData[TipoData]),
			    "Real",
			        SWITCH(
			            SELECTEDVALUE(SelectorValor[TipoValor]),
			
			            // Anualizado
			            "Anualizado", 
			                    SWITCH ( 
			                        TRUE(),
			                        TipoPasivo = "Otros Pasivos",
			                           SUM(gd_financiero_general[val_saldo_anualizado]) - CALCULATE(SUM(gd_financiero_general[val_saldo_anualizado]),gd_financiero_general[id_cuenta_contable] = "259006"),
			                           SUM(gd_financiero_general[val_saldo_anualizado])
			                    ),
			
			            // Mensualizado
			            "Mensualizado", 
			                       SWITCH ( TRUE(), TipoPasivo = "Otros Pasivos", SUM(gd_financiero_general[val_saldo_balance]) - CALCULATE(SUM(gd_financiero_general[val_saldo_balance]),gd_financiero_general[id_cuenta_contable] = "259006"), SUM(gd_financiero_general[val_saldo_balance]) ),
			
			            // Acumulado
			            "Acumulado",                
			                    SWITCH ( 
			                        TRUE(),
			                        TipoPasivo = "Otros Pasivos",
			                           SUM(gd_financiero_general[val_saldo_balance_acumulado]) - CALCULATE(SUM(gd_financiero_general[val_saldo_balance_acumulado]),gd_financiero_general[id_cuenta_contable] = "259006"),                           
			                           SUM(gd_financiero_general[val_saldo_balance_acumulado])
			                    ) 
			                        
			        ),
			    "Presupuesto",
			        SWITCH(
			            SELECTEDVALUE(SelectorValor[TipoValor]),
			
			            // Anualizado
			            "Anualizado", 
			                SUM(gd_financiero_general[val_presupuesto_anualizado]),
			
			            // Mensualizado
			            "Mensualizado", 
			
			                    SUM(gd_financiero_general[val_presupuesto]),
			
			
			
			            // Acumulado
			            "Acumulado",             
			                    
			                        SUM(gd_financiero_general[val_presupuesto_acumulado])
			
			        ),
			    "Forecast",
			        SWITCH(
			            SELECTEDVALUE(SelectorValor[TipoValor]),
			
			            // Anualizado
			            "Anualizado", 
			                SUM(gd_financiero_general[val_forecast_anualizado]),
			
			            // Mensualizado
			            "Mensualizado", 
			                    SUM(gd_financiero_general[val_forecast]),
			
			            // Acumulado
			            "Acumulado", 
			                        SUM(gd_financiero_general[val_forecast_acumulado])
			        )
			)
			```
		displayFolder: Medidas
		lineageTag: 86a45428-9da1-487f-aab3-69e86b172160

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Activos_BG1 =
			
			VAR MaxYear =
			    MAXX(ALL('Calendario'), 'Calendario'[Año])   -- calcula el año máximo ignorando filtros
			RETURN
			CALCULATE(
			    [Activos_BG_P],
			    'Calendario'[Año] = MaxYear                  -- aplica filtro al año máximo
			)
		displayFolder: Medidas
		lineageTag: 46ead121-faac-4e0b-8c58-bc967e78c47e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Pasivos_BG1 =
			
			VAR MaxYear =
			    MAXX(ALL('Calendario'), 'Calendario'[Año])   -- calcula el año máximo ignorando filtros
			RETURN
			CALCULATE(
			    [Pasivos_BG_P],
			    'Calendario'[Año] = MaxYear                  -- aplica filtro al año máximo
			)
		displayFolder: Medidas
		lineageTag: aed238a0-85a3-49b3-9e52-d7db720d914b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Patrimonio_BG1 =
			
			VAR MaxYear =
			    MAXX(ALL('Calendario'), 'Calendario'[Año])   -- calcula el año máximo ignorando filtros
			RETURN
			CALCULATE(
			    [Patrimonio_BG_P],
			    'Calendario'[Año] = MaxYear                  -- aplica filtro al año máximo
			)
		displayFolder: Medidas
		lineageTag: 3027dd89-ad2e-4ec4-807d-54589097713e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Activos_BG_P = ```
			
			CALCULATE(
			    [Real Act_BG],
			    gd_financiero_general[TipoCuenta_BG] = "ACTIVOS" && gd_financiero_general[id_cuenta_contable] = "1"
			)
			
			```
		formatString: #,0.00
		displayFolder: Medidas
		lineageTag: 701c6c52-203f-43b5-97a4-06d03b56eec0

	measure Pasivos_BG_P =
			
			CALCULATE(
			    [Real Act_BG],
			    gd_financiero_general[TipoCuenta_BG] = "PASIVOS" && gd_financiero_general[id_cuenta_contable] = "2"
			)
		displayFolder: Medidas
		lineageTag: cfbaccbe-fed9-47b8-8ad7-3f87ebe2801d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Patrimonio_BG_P =
			
			CALCULATE(
			    [Real Act_BG],
			    gd_financiero_general[id_cuenta_contable] IN{"31","3204","3206","3202","3201","3402","3401"}
			)
		displayFolder: Medidas
		lineageTag: dbb8ef13-bbf4-4d90-9bec-80cb71ed16f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Resultado del Ejercicio' = CALCULATE(SUM(gd_financiero_general[val_saldo_balance]),gd_financiero_general[cta_desc_bg] = "Resultado del Ejercicio")
		displayFolder: Medidas
		lineageTag: f9ebfead-211d-4044-a4fe-7d7b16e508dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fec_periodo
		dataType: string
		lineageTag: 8f40653b-96dc-409a-9064-7d8dfac7458f
		summarizeBy: none
		sourceColumn: fec_periodo

		annotation SummarizationSetBy = Automatic

	column id_empresa
		dataType: string
		lineageTag: a73810f4-f627-47f3-a39e-2a3635cae120
		summarizeBy: none
		sourceColumn: id_empresa

		annotation SummarizationSetBy = Automatic

	column des_tipo_ramo
		dataType: string
		lineageTag: bd8b12eb-583a-41d8-895c-ceea29af2b83
		summarizeBy: none
		sourceColumn: des_tipo_ramo

		annotation SummarizationSetBy = Automatic

	column id_cuenta_contable
		dataType: string
		lineageTag: e0f5d4d9-c7d3-4512-9d8a-c7ac9bf52f8c
		summarizeBy: none
		sourceColumn: id_cuenta_contable

		annotation SummarizationSetBy = Automatic

	column val_saldo_anterior
		dataType: double
		lineageTag: 2b9a9535-3f46-4311-b36c-2487bc17fb83
		summarizeBy: sum
		sourceColumn: val_saldo_anterior

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_debito
		dataType: double
		lineageTag: b552915f-ed84-4760-a721-e6542d65f1c8
		summarizeBy: sum
		sourceColumn: val_saldo_debito

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_credito
		dataType: double
		lineageTag: 75962671-af3a-4e1f-9563-515e3fac4c9f
		summarizeBy: sum
		sourceColumn: val_saldo_credito

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_balance
		dataType: double
		lineageTag: 7c5511a5-455c-4a3b-836b-be1d41728a38
		summarizeBy: sum
		sourceColumn: val_saldo_balance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_mes
		dataType: double
		lineageTag: 1955fcab-70ec-4016-aec7-15ff63b746f7
		summarizeBy: sum
		sourceColumn: val_saldo_mes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presupuesto
		dataType: double
		lineageTag: bd9122d2-5062-4be9-aea7-e474b063fcd3
		summarizeBy: sum
		sourceColumn: val_presupuesto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast
		dataType: double
		lineageTag: c405288c-c888-4181-9e40-22a28d199572
		summarizeBy: sum
		sourceColumn: val_forecast

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fec_periodo_ultimo_dia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0d916d78-cf00-462a-b1aa-d83444f530b9
		summarizeBy: none
		sourceColumn: fec_periodo_ultimo_dia

		variation Variación
			isDefault
			relationship: 6d1d0bdf-2a80-49ef-a8a3-04b7e736ccca
			defaultHierarchy: LocalDateTable_b36e8f8f-e6e6-4793-9417-12d2022d8c33.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fec_corte
		dataType: string
		lineageTag: 8e434bca-79c8-448b-9486-ec21d83fbbac
		summarizeBy: none
		sourceColumn: fec_corte

		annotation SummarizationSetBy = Automatic

	column particion
		dataType: string
		lineageTag: 358cfcea-ba96-4571-8104-45cba379143a
		summarizeBy: none
		sourceColumn: particion

		annotation SummarizationSetBy = Automatic

	column val_saldo_anualizado
		dataType: double
		lineageTag: 0aa66042-113f-497c-be26-b3b26780cf6e
		summarizeBy: sum
		sourceColumn: val_saldo_anualizado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fec_periodo_entero_BG =
			
			VALUE(gd_financiero_general[fec_periodo] & "01")
		displayFolder: Columnas
		lineageTag: 83b0ee8e-1299-4765-9140-dc86fd36fd54
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fec_periodo_fecha_BG = ```
			
			DATE(
			    LEFT(gd_financiero_general[fec_periodo], 4),            
			    MID(gd_financiero_general[fec_periodo], 5, 2),          
			    1                                               
			)
			```
		formatString: yyyy-mm
		displayFolder: Columnas
		lineageTag: 838d220d-8c36-4d46-bb08-fe453c2f1283
		summarizeBy: none

		variation Variación
			isDefault
			relationship: b4ee2312-29ac-4434-ac49-b5690565a9d3
			defaultHierarchy: LocalDateTable_0cc8de16-06dc-4055-b6e3-5a07fa60b618.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column TipoCuenta_BG = ```
			
			SWITCH(
			    LEFT(gd_financiero_general[id_cuenta_contable], 1),
			    "1", "ACTIVOS",
			    "2", "PASIVOS",
			    "3", "PATRIMONIO",
			    "Otros"
			)
			
			```
		displayFolder: Columnas
		lineageTag: c3ff167d-84fc-4526-a414-c0019ddae9ce
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column cod_nivel_cuenta
		dataType: string
		lineageTag: 45c19e35-e137-42fc-8ee4-e155590f6e41
		summarizeBy: none
		sourceColumn: cod_nivel_cuenta

		annotation SummarizationSetBy = Automatic

	column Ramo_BG = ```
			
			SWITCH(TRUE(),
			    SEARCH("GENERALES", 'gd_financiero_general'[des_tipo_ramo], 1, 0) > 0, "NO VIDA",
			    SEARCH("VIDA", 'gd_financiero_general'[des_tipo_ramo], 1, 0) > 0, "VIDA",
			    "Otros"
			)
			
			```
		displayFolder: Columnas
		lineageTag: 81ac67a5-ab3b-4e64-8f03-f34337696817
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column val_presupuesto_anualizado
		dataType: double
		lineageTag: 86c126a8-a7df-4ad2-9b26-a0b6bcacbcd4
		summarizeBy: sum
		sourceColumn: val_presupuesto_anualizado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_anualizado
		dataType: double
		lineageTag: 4a61d5b5-554e-4618-a12f-8c3e86af299a
		summarizeBy: sum
		sourceColumn: val_forecast_anualizado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_balance_acumulado
		dataType: double
		lineageTag: 37b39637-83fa-484a-9780-25679ec8a963
		summarizeBy: sum
		sourceColumn: val_saldo_balance_acumulado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presupuesto_acumulado
		dataType: double
		lineageTag: 53921ae6-b78d-4296-a91f-a68cebe880a8
		summarizeBy: sum
		sourceColumn: val_presupuesto_acumulado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_acumulado
		dataType: double
		lineageTag: fb2fb2fe-0319-4490-bfd8-4ad1efb81fa9
		summarizeBy: sum
		sourceColumn: val_forecast_acumulado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fec_periodo_y_1
		dataType: string
		lineageTag: 2b8db20a-7447-4303-9f8d-3c3fd6ebf370
		summarizeBy: none
		sourceColumn: fec_periodo_y_1

		annotation SummarizationSetBy = Automatic

	column val_saldo_balance_y_1
		dataType: double
		lineageTag: fdcae67e-3865-444d-955b-a0240bee4d9d
		summarizeBy: sum
		sourceColumn: val_saldo_balance_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_balance_acumulado_y_1
		dataType: double
		lineageTag: 0645502b-98bb-430f-ad8a-1af982ad114f
		summarizeBy: sum
		sourceColumn: val_saldo_balance_acumulado_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_acumulado_y_1
		dataType: double
		lineageTag: 4e8e2309-7ac0-48e9-8d61-99e946e7575e
		summarizeBy: sum
		sourceColumn: val_forecast_acumulado_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presupuesto_anualizado_y_1
		dataType: double
		lineageTag: 9ee236ff-8ac2-486f-bb21-bfa0b3a56dfc
		summarizeBy: sum
		sourceColumn: val_presupuesto_anualizado_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presupuesto_y_1
		dataType: double
		lineageTag: 10c14786-5ced-41ec-897c-132314696053
		summarizeBy: sum
		sourceColumn: val_presupuesto_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_y_1
		dataType: double
		lineageTag: 76082c5a-c0f5-4075-855f-39b44cd26675
		summarizeBy: sum
		sourceColumn: val_forecast_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_anualizado_y_1
		dataType: double
		lineageTag: 7bf8133a-1d47-4d5c-adee-3d31ed4d27dd
		summarizeBy: sum
		sourceColumn: val_forecast_anualizado_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_anualizado_y_1
		dataType: double
		lineageTag: b5386ace-233a-4773-bf22-d98001657d16
		summarizeBy: sum
		sourceColumn: val_saldo_anualizado_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presupuesto_acumulado_y_1
		dataType: double
		lineageTag: 41ee5a38-47dc-4a07-8f5c-24a1210c37ea
		summarizeBy: sum
		sourceColumn: val_presupuesto_acumulado_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cta_desc_bg =
			
			VAR id_cuenta_contable = FORMAT ( gd_financiero_general[id_cuenta_contable], "0" )
			RETURN
			SWITCH (
			    id_cuenta_contable,
			    "480301", "Ajuste Reserva de Siniestros",
			    "570301", "Ajuste Reserva de Siniestros",
			    "1102", "Fondos Disponibles",
			    "31", "Capital",
			    "1101", "Inversiones",
			    "44", "Cesión Primas Reaseguros",
			    "42", "Comisiones pagadas",
			    "52", "Comisiones recibidas",
			    "4704", "Contribuciones e impuestos",
			    "410113", "Contribuciones e impuestos",
			    "43", "Costo Excesos de Pérdida",
			    "23", "Cuentas por pagar",
			    "24", "Cuentas por pagar",
			    "3204", "Dividendo en Acción",
			    "1201", "Primas por cobrar",
			    "4101", "Gastos Personal",
			    "470201", "Gastos por inversiones",
			    "4102", "Gastos Varios",
			    "480302", "IBNR",
			    "570302", "IBNR",
			    "4701", "Intereses pagados",
			    "1202", "Primas por cobrar",
			    "1203", "Primas por cobrar",
			    "2104", "Otras reservas",
			    "2105", "Otras reservas",
			    "2106", "Otras reservas",
			    "4705", "Otras reservas y provisiones",
			    "4806", "Otras reservas y provisiones",
			    "5706", "Otras reservas y provisiones",
			    "470204", "Otras reservas y provisiones",
			    "470301", "Otras reservas y provisiones",
			    "13", "Reaseguros por cobrar",
			    "1103", "Bienes raices y mobiliario",
			    "55", "Otros gastos financieros",
			    "470203", "Otros gastos financieros",
			    "470303", "Otros gastos financieros",
			    "56", "Otros gastos financieros",
			    "26", "Otros Pasivos",
			    "45", "Prima neta emitida",
			    "51", "Prima neta emitida",
			    "4403", "Prima neta emitida",
			    "259006", "Primas anticipadas",
			    "1403", "Cargos Diferidos",
			    "1401", "Otros Activos",
			    "22", "Reaseguros Cedidos",
			    "1402", "Otros Activos",
			    "53", "Recuperaciones y salvamentos",
			    "3206", "Reserva Capital",
			    "4804", "Reserva de desv. Siniestralidad",
			    "5704", "Reserva de desv. Siniestralidad",
			    "3202", "Reserva Especial",
			    "4805", "Reserva insuficiencia de primas",
			    "5705", "Reserva insuficiencia de primas",
			    "3201", "Reserva Legal",
			    "4801", "Reserva Técnica Neta",
			    "4802", "Reserva Técnica Neta",
			    "5701", "Reserva Técnica Neta",
			    "5702", "Reserva Técnica Neta",
			    "2103", "Reservas Siniestros",
			    "2101", "Reservas Técnicas",
			    "2102", "Reservas Técnicas",
			    "3402", "Resultado del Ejercicio",
			    "3401", "Resultados de Ejercicios Anteriores",
			    "46", "Siniestros pagados",
			    "54", "Utilidad por inversiones",
			    "5601", "Utilidad por inversiones",
			    "25", "Otros Pasivos",
			    BLANK ()
			)
		displayFolder: Columnas
		lineageTag: 6e888d55-4709-4658-bf31-ea53b0b99e5c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column val_saldo_calculo
		dataType: double
		lineageTag: a177ead8-5f39-439b-b4dd-4709b551a869
		summarizeBy: sum
		sourceColumn: val_saldo_calculo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_mes_acumulado
		dataType: double
		lineageTag: 5d183b90-36fb-4a9d-91d1-9e8cea14195f
		summarizeBy: sum
		sourceColumn: val_saldo_mes_acumulado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_mes_y_1
		dataType: double
		lineageTag: effa47f0-9434-4db8-8cc3-8d089296976a
		summarizeBy: sum
		sourceColumn: val_saldo_mes_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_mes_acumulado_y_1
		dataType: double
		lineageTag: 49c3f820-d861-4013-9a4c-905dabc4b8b3
		summarizeBy: sum
		sourceColumn: val_saldo_mes_acumulado_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cta_des
		dataType: string
		lineageTag: 70c08fff-5e00-4cb8-9c21-b200262449bf
		summarizeBy: none
		sourceColumn: cta_des

		annotation SummarizationSetBy = Automatic

	column des_gerencia
		dataType: string
		lineageTag: a552118e-c5e0-46bf-9b7f-ea0927c59fb5
		summarizeBy: none
		sourceColumn: des_gerencia

		annotation SummarizationSetBy = Automatic

	column 'Cod 6 Dig' = ```
			
			VAR txt = TRIM ( gd_financiero_general[id_cuenta_contable] )
			RETURN
			IF (
			    ISBLANK ( txt ),
			    BLANK (),
			    IF ( LEN ( txt ) = 6, txt, "Otros" )
			)
			
			```
		displayFolder: Columnas
		lineageTag: b9a47037-bb42-4e10-8d0d-ebe431acdba8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column val_saldo_calculo_acumulado
		dataType: double
		lineageTag: a488e019-044f-4545-a987-e4f648ce2bfb
		summarizeBy: sum
		sourceColumn: val_saldo_calculo_acumulado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_calculo_y_1
		dataType: double
		lineageTag: fa697fd9-09b0-416b-98ec-270c006b5ae3
		summarizeBy: sum
		sourceColumn: val_saldo_calculo_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_calculo_acumulado_y_1
		dataType: double
		lineageTag: cdb8e91b-edee-4bcb-a841-5c7553ec838d
		summarizeBy: sum
		sourceColumn: val_saldo_calculo_acumulado_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_balance_real
		dataType: double
		lineageTag: 1bf67a2e-b3d0-4e33-919d-dc8c681f4ecb
		summarizeBy: sum
		sourceColumn: val_saldo_balance_real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_balance_acumulado_real
		dataType: double
		lineageTag: 57ec71ec-f6f3-4831-b07f-66dd8831ff75
		summarizeBy: sum
		sourceColumn: val_saldo_balance_acumulado_real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_balance_y_1_real
		dataType: double
		lineageTag: bbaa3609-aae7-4bbb-9d4f-75653e2ae659
		summarizeBy: sum
		sourceColumn: val_saldo_balance_y_1_real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_balance_acumulado_y_1_real
		dataType: double
		lineageTag: 11f35247-456c-4ac2-944d-19778080b917
		summarizeBy: sum
		sourceColumn: val_saldo_balance_acumulado_y_1_real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cta_ida_n4
		dataType: string
		lineageTag: ed77b124-8b69-4019-ba3d-4130f24dbfd4
		summarizeBy: none
		sourceColumn: cta_ida_n4

		annotation SummarizationSetBy = Automatic

	column Columna = IF(LEN(gd_financiero_general[cta_ida_n4]) = 6,"SI","NO")
		displayFolder: Columnas
		lineageTag: 8bf597b7-3eb7-4ad8-b001-ba6eea05851f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column val_saldo_calculo_anualizado
		dataType: double
		lineageTag: e7a32ed6-184f-47f9-ad37-a88791c5507f
		summarizeBy: sum
		sourceColumn: val_saldo_calculo_anualizado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cta_des_bg_n2
		dataType: string
		lineageTag: 3f34b353-f182-4620-b613-1f85fe144471
		summarizeBy: none
		sourceColumn: cta_des_bg_n2
		sortByColumn: Orden_cta_des_bg_n2

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column cta_des_bg_n1
		dataType: string
		lineageTag: 05e2c8c7-c5dd-4bdd-b20d-ce966ebfd991
		summarizeBy: none
		sourceColumn: cta_des_bg_n1

		annotation SummarizationSetBy = Automatic

	column cta_ida_n1
		dataType: string
		lineageTag: b4c6fa37-3052-4758-a714-4bfae09c53f6
		summarizeBy: none
		sourceColumn: cta_ida_n1

		annotation SummarizationSetBy = Automatic

	column cta_ida_n2
		dataType: string
		lineageTag: bfbf5e41-6d44-4959-a634-5ad4dcfd2d5a
		summarizeBy: none
		sourceColumn: cta_ida_n2

		annotation SummarizationSetBy = Automatic

	column cta_ida_n3
		dataType: string
		lineageTag: 270ebaeb-13a5-44a1-8f7c-728cad2c4539
		summarizeBy: none
		sourceColumn: cta_ida_n3

		annotation SummarizationSetBy = Automatic

	column Orden_cta_des_bg_n2
		dataType: string
		lineageTag: 7449b1c7-11b1-4b29-ae4a-466f7e133d78
		summarizeBy: none
		sourceColumn: Orden_cta_des_bg_n2

		annotation SummarizationSetBy = Automatic

	partition gd_financiero_general = m
		mode: import
		source =
				let
				    Origen = Databricks.Catalogs("adb-2683128165517039.19.azuredatabricks.net", "/sql/1.0/warehouses/7d4c90cb72eed782", [Catalog="ctlfinanciero", Database="schgold", QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null]),
				    gd_financiero_general_schgold_ctlfinanciero = Origen{[Item="vw_gd_financiero_general",Schema="schgold",Catalog="ctlfinanciero"]}[Data],
				    #"Added Conditional Column" = Table.AddColumn(gd_financiero_general_schgold_ctlfinanciero, "Orden_cta_des_bg_n2", each if [cta_des_bg_n2] = "Fondos Disponibles" then 1 else if [cta_des_bg_n2] = "Inversiones" then 2 else if [cta_des_bg_n2] = "Primas por Cobrar" then 3 else if [cta_des_bg_n2] = "Reaseguros por cobrar" then 4 else if [cta_des_bg_n2] = "Bienes raices y mobiliario" then 5 else if [cta_des_bg_n2] = "Cargos Diferidos" then 6 else if [cta_des_bg_n2] = "Otros Activos" then 7 else if [cta_des_bg_n2] = "Reservas Técnicas" then 1 else if [cta_des_bg_n2] = "Reservas Siniestros" then 2 else if [cta_des_bg_n2] = "Otras reservas" then 3 else if [cta_des_bg_n2] = "Reaseguros Cedidos" then 4 else if [cta_des_bg_n2] = "Cuentas por pagar" then 5 else if [cta_des_bg_n2] = "Otros Pasivos" then 6 else if [cta_des_bg_n2] = "Primas anticipadas" then 7 else if [cta_des_bg_n2] = "Capital" then 1 else if [cta_des_bg_n2] = "Reserva Legal" then 2 else if [cta_des_bg_n2] = "Reserva Capital" then 3 else if [cta_des_bg_n2] = "Reserva Especial" then 4 else if [cta_des_bg_n2] = "Dividendo en Acción" then 5 else if [cta_des_bg_n2] = "Resultados de Ejercicios Anteriores" then 6 else if [cta_des_bg_n2] = "Resultado del Ejercicio" then 7 else 999)
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

