table gd_grupo_contable2
	lineageTag: 37fc9dfe-f41e-4d58-ad53-125baaa8ae72

	measure '% gasto_prima_bruta_BR PG' = ```
			
			DIVIDE([Gastos Administrativos], [Primas Brutas]-[Coaseguros Cedidos], 0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MedidasPG
		lineageTag: a90cbb8d-dd3f-4199-bd67-4cf7ecd6244a

	measure '% rentabilidad_tecnica_BR PG' =
			
			DIVIDE([RESULTADO TÉCNICO], [PRIMAS DEVENGADAS],0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MedidasPG
		lineageTag: 3cdb08fa-8b1c-481c-b0ff-de53bcba59ae

	measure '% rentabilidad_financiera_BR PG' =
			
			DIVIDE([UTILIDAD NETA], [Primas Brutas], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MedidasPG
		lineageTag: 351e3709-868f-45f4-8fac-ba810b09ce19

	measure '% siniestro_inc_acum_BR PG' =
			
			DIVIDE([Costo de Siniestros], [PRIMAS DEVENGADAS], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MedidasPG
		lineageTag: c4e41b75-3d7f-4242-be5a-e56a309f197b

	measure '% Real Act PG' = ```
			
			VAR KPISeleccionado = SELECTEDVALUE('Tabla_KPI_PG'[KPI_des_PG])
			RETURN
			SWITCH (
			    TRUE(),
			
			    KPISeleccionado = "%GASTOS PRIMA BRUTA",
			        VAR Numerador =
			            CALCULATE([Gastos Administrativos], SelectorCalculo_PG[TipoCalculo] = "Real Act")
			        VAR Denominador =
			            CALCULATE([Primas Brutas], SelectorCalculo_PG[TipoCalculo] = "Real Act")
			            - CALCULATE([Coaseguros Cedidos], SelectorCalculo_PG[TipoCalculo] = "Real Act")
			        RETURN COALESCE(DIVIDE(Numerador, Denominador), 0),
			
			    KPISeleccionado = "RENTABILIDAD TÉCNICA",
			        VAR UtilidadTecnica = CALCULATE([RESULTADO TÉCNICO], SelectorCalculo_PG[TipoCalculo] = "Real Act")
			        VAR PrimaDev = CALCULATE([PRIMAS DEVENGADAS], SelectorCalculo_PG[TipoCalculo] = "Real Act")
			        RETURN COALESCE(DIVIDE(UtilidadTecnica, PrimaDev), 0),
			
			    KPISeleccionado = "RENTABILIDAD FINANCIERA",
			        VAR Rentabilidad = CALCULATE([UTILIDAD NETA], SelectorCalculo_PG[TipoCalculo] = "Real Act")
			        VAR Base = CALCULATE([Primas Brutas], SelectorCalculo_PG[TipoCalculo] = "Real Act")
			        RETURN COALESCE(DIVIDE(Rentabilidad, Base), 0),
			
			    KPISeleccionado = "SINIESTROS INC ACUM.",
			        VAR CostoSiniestro = CALCULATE([Costo de Siniestros], SelectorCalculo_PG[TipoCalculo] = "Real Act")
			        VAR PrimaDev = CALCULATE([PRIMAS DEVENGADAS], SelectorCalculo_PG[TipoCalculo] = "Real Act")
			        RETURN COALESCE(DIVIDE(CostoSiniestro, PrimaDev), 0),
			
			    KPISeleccionado = "%COSTO DE SINIESTROS",
			        VAR CostoSiniestro1 = CALCULATE([Recuperaciones siniestros], SelectorCalculo_PG[TipoCalculo] = "Real Act") - CALCULATE([Siniestros pagados], SelectorCalculo_PG[TipoCalculo] = "Real Act") - CALCULATE([Ajuste Reserva Siniestros], SelectorCalculo_PG[TipoCalculo] = "Real Act") - CALCULATE([IBNR], SelectorCalculo_PG[TipoCalculo] = "Real Act")
			        VAR PrimaNeta = CALCULATE([PRIMAS NETAS], SelectorCalculo_PG[TipoCalculo] = "Real Act")
			        RETURN COALESCE(DIVIDE(CostoSiniestro1, PrimaNeta), 0),
			
			    BLANK()
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MedidasPG
		lineageTag: 8aadc357-5d74-4ae2-8a14-36e7c91e48cf

	measure '% Real Ppto PG' = ```
			
			VAR KPISeleccionado = SELECTEDVALUE('Tabla_KPI_PG'[KPI_des_PG])
			RETURN
			SWITCH (
			    TRUE(),
			
			    KPISeleccionado = "%GASTOS PRIMA BRUTA",
			        VAR Numerador =
			            CALCULATE([Gastos Administrativos], SelectorCalculo_PG[TipoCalculo] = "Ppto")
			        VAR Denominador =
			            CALCULATE([Primas Brutas], SelectorCalculo_PG[TipoCalculo] = "Ppto")
			            - CALCULATE([Coaseguros Cedidos], SelectorCalculo_PG[TipoCalculo] = "Ppto")
			        RETURN COALESCE(DIVIDE(Numerador, Denominador), 0),
			
			    KPISeleccionado = "RENTABILIDAD TÉCNICA",
			        VAR UtilidadTecnica = CALCULATE([RESULTADO TÉCNICO], SelectorCalculo_PG[TipoCalculo] = "Ppto")
			        VAR PrimaDev = CALCULATE([PRIMAS DEVENGADAS], SelectorCalculo_PG[TipoCalculo] = "Ppto")
			        RETURN COALESCE(DIVIDE(UtilidadTecnica, PrimaDev), 0),
			
			    KPISeleccionado = "RENTABILIDAD FINANCIERA",
			        VAR Rentabilidad = CALCULATE([UTILIDAD NETA], SelectorCalculo_PG[TipoCalculo] = "Ppto")
			        VAR Base = CALCULATE([Primas Brutas], SelectorCalculo_PG[TipoCalculo] = "Ppto")
			        RETURN COALESCE(DIVIDE(Rentabilidad, Base), 0),
			
			    KPISeleccionado = "SINIESTROS INC ACUM.",
			        VAR CostoSiniestro = CALCULATE([Costo de Siniestros], SelectorCalculo_PG[TipoCalculo] = "Ppto")
			        VAR PrimaDev = CALCULATE([PRIMAS DEVENGADAS], SelectorCalculo_PG[TipoCalculo] = "Ppto")
			        RETURN COALESCE(DIVIDE(CostoSiniestro, PrimaDev), 0),
			
			    KPISeleccionado = "%COSTO DE SINIESTROS",
			        VAR CostoSiniestro1 = CALCULATE([Recuperaciones siniestros], SelectorCalculo_PG[TipoCalculo] = "Ppto") - CALCULATE([Siniestros pagados], SelectorCalculo_PG[TipoCalculo] = "Ppto") - CALCULATE([Ajuste Reserva Siniestros], SelectorCalculo_PG[TipoCalculo] = "Ppto") - CALCULATE([IBNR], SelectorCalculo_PG[TipoCalculo] = "Ppto")
			        VAR PrimaNeta = CALCULATE([PRIMAS NETAS], SelectorCalculo_PG[TipoCalculo] = "Ppto")
			        RETURN COALESCE(DIVIDE(CostoSiniestro1, PrimaNeta), 0),
			
			    BLANK()
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MedidasPG
		lineageTag: 96132eb4-5ebf-4458-be28-02c5ec87852a

	measure '% Var PG' = [% Real Act PG] - [% Real Ppto PG]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MedidasPG
		lineageTag: c626abfc-049b-4a55-8d3f-83ba004afe4d

	measure '% Real Y-1 PG' =
			
			VAR KPISeleccionado = SELECTEDVALUE('Tabla_KPI_PG'[KPI_des_PG])
			RETURN
			SWITCH (
			    TRUE(),
			
			    KPISeleccionado = "%GASTOS PRIMA BRUTA",
			        VAR Numerador =
			            CALCULATE([Gastos Administrativos], SelectorCalculo_PG[TipoCalculo] = "Real Y-1")
			        VAR Denominador =
			            CALCULATE([Primas Brutas], SelectorCalculo_PG[TipoCalculo] = "Real Y-1")
			            - CALCULATE([Coaseguros Cedidos], SelectorCalculo_PG[TipoCalculo] = "Real Y-1")
			        RETURN COALESCE(DIVIDE(Numerador, Denominador), 0),
			
			    KPISeleccionado = "RENTABILIDAD TÉCNICA",
			        VAR UtilidadTecnica = CALCULATE([RESULTADO TÉCNICO], SelectorCalculo_PG[TipoCalculo] = "Real Y-1")
			        VAR PrimaDev = CALCULATE([PRIMAS DEVENGADAS], SelectorCalculo_PG[TipoCalculo] = "Real Y-1")
			        RETURN COALESCE(DIVIDE(UtilidadTecnica, PrimaDev), 0),
			
			    KPISeleccionado = "RENTABILIDAD FINANCIERA",
			        VAR Rentabilidad = CALCULATE([UTILIDAD NETA], SelectorCalculo_PG[TipoCalculo] = "Real Y-1")
			        VAR Base = CALCULATE([Primas Brutas], SelectorCalculo_PG[TipoCalculo] = "Real Y-1")
			        RETURN COALESCE(DIVIDE(Rentabilidad, Base), 0),
			
			    KPISeleccionado = "SINIESTROS INC ACUM.",
			        VAR CostoSiniestro = CALCULATE([Costo de Siniestros], SelectorCalculo_PG[TipoCalculo] = "Real Y-1")
			        VAR PrimaDev = CALCULATE([PRIMAS DEVENGADAS], SelectorCalculo_PG[TipoCalculo] = "Real Y-1")
			        RETURN COALESCE(DIVIDE(CostoSiniestro, PrimaDev), 0),
			
			    KPISeleccionado = "%COSTO DE SINIESTROS",
			        VAR CostoSiniestro1 = CALCULATE([Recuperaciones siniestros], SelectorCalculo_PG[TipoCalculo] = "Real Y-1") - CALCULATE([Siniestros pagados], SelectorCalculo_PG[TipoCalculo] = "Real Y-1") - CALCULATE([Ajuste Reserva Siniestros], SelectorCalculo_PG[TipoCalculo] = "Real Y-1") - CALCULATE([IBNR], SelectorCalculo_PG[TipoCalculo] = "Real Y-1")
			        VAR PrimaNeta = CALCULATE([PRIMAS NETAS], SelectorCalculo_PG[TipoCalculo] = "Real Y-1")
			        RETURN COALESCE(DIVIDE(CostoSiniestro1, PrimaNeta), 0),
			
			    BLANK()
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MedidasPG
		lineageTag: 3ebeb627-2170-4ce1-9169-41f09ab5ae4e

	measure '%YoY KPI PG' =
			
			([% Real Act PG]-[% Real Y-1 PG])/[% Real Y-1 PG]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MedidasPG
		lineageTag: 1e93cf99-a187-4401-a631-5ed16bff9c92

	measure FechaMaxCargaTexto_PG =
			
			VAR FechaMax =
			    CALCULATE (
			        MAX ( gd_grupo_contable2[fec_periodo_fecha_PG] ),
			        ALL ( gd_grupo_contable2 )
			    )
			VAR MesAbrevRaw = FORMAT ( FechaMax, "MMM" )         -- abreviado
			VAR MesSinPunto  = SUBSTITUTE ( MesAbrevRaw, ".", "" )
			VAR MesCap       = UPPER ( LEFT ( MesSinPunto, 1 ) ) &
			                   LOWER ( MID ( MesSinPunto, 2, LEN ( MesSinPunto ) - 1 ) )
			VAR Mes3         = LEFT ( MesCap, 3 )                 -- asegura "Dic", "Sep", etc.
			RETURN
			    IF ( ISBLANK ( FechaMax ), BLANK (), Mes3 & " " & FORMAT ( FechaMax, "yyyy" ) )
		displayFolder: MedidasPG
		lineageTag: 4e7b3703-02cf-4763-80d9-f4dbcf53a42a

	measure FechaMaxCargaTexto_PT =
			
			VAR FechaMax =
			    CALCULATE (
			        MAX ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        ALL ( gd_grupo_contable2 )
			    )
			VAR MesAbrevRaw = FORMAT ( FechaMax, "MMM" )         -- abreviado
			VAR MesSinPunto  = SUBSTITUTE ( MesAbrevRaw, ".", "" )
			VAR MesCap       = UPPER ( LEFT ( MesSinPunto, 1 ) ) &
			                   LOWER ( MID ( MesSinPunto, 2, LEN ( MesSinPunto ) - 1 ) )
			VAR Mes3         = LEFT ( MesCap, 3 )                 -- asegura "Dic", "Sep", etc.
			RETURN
			    IF ( ISBLANK ( FechaMax ), BLANK (), Mes3 & " " & FORMAT ( FechaMax, "yyyy" ) )
		displayFolder: MedidasPT
		lineageTag: 6e9d1771-33e1-4437-83e3-9d4d2f8ca86b

	measure 'Capital Adecuado por Primas' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Primas Brutas - Coaseguros Cedidos === */
			VAR SumColumna_PrimasBrutasCedidas =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			/* === Primas Netas Vida Individual === */
			VAR SumColumna_PrimasNetasVI =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			/* === Factor de Retención cap === */
			VAR SumColumna_FactorRetencion =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			/* === Reserva Matemática 5% === */
			VAR SumColumna_ReservaMat5 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_PrimasBrutasCedidas_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Primas Netas Vida Individual === */
			VAR SumColumna_PrimasNetasVI_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Factor de Retención cap === */
			VAR SumColumna_FactorRetencion_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Reserva Matemática 5% === */
			VAR SumColumna_ReservaMat5_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT =
			    (( (SumColumna_PrimasBrutasCedidas - SumColumna_PrimasNetasVI)*0.23)
			    * SumColumna_FactorRetencion)
			    + SumColumna_ReservaMat5
			VAR REAL_Y_1 =
			    ((( SumColumna_PrimasBrutasCedidas_1 - SumColumna_PrimasNetasVI_1)*0.23)
			    * SumColumna_FactorRetencion_1)
			    + SumColumna_ReservaMat5_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 1519fbc7-60dc-4a4f-a298-c93652ede002

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Cap. Ade. Por Carga Media De Siniestralidad2' = ```
			
			VAR PeriodoSeleccionado = MAX(gd_grupo_contable2[fec_periodo_fecha_PT])
			VAR AnioActual = YEAR(PeriodoSeleccionado)
			VAR MesActual  = MONTH(PeriodoSeleccionado)
			
			-- Normalizo a primer día del mes por seguridad
			VAR MesActual_Inicio = DATE(AnioActual, MesActual, 1)
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE(MesActual_Inicio, -12)
			VAR AnioAnterior    = YEAR(PeriodoAnterior)
			VAR MesAnterior     = MONTH(PeriodoAnterior)
			
			-- Periodo anterior = 24 meses atrás (mismo día del mes)
			VAR PeriodoAnterior2 = EDATE(MesActual_Inicio, -24)
			VAR AnioAnterior2    = YEAR(PeriodoAnterior2)
			VAR MesAnterior2     = MONTH(PeriodoAnterior2)
			
			
			-- === FILTROS ACTUALES ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        YEAR ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = AnioActual
			            && MONTH ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    DATESBETWEEN(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        DATE(AnioActual, 1, 1),
			        EOMONTH(MesActual_Inicio, 0)
			    )
			
			VAR FiltroAnualizado =
			    DATESINPERIOD(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        MesActual_Inicio,   -- fin de la ventana (mes actual, incluido)
			        -12,
			        MONTH
			    )
			
			-- === FILTROS UN AÑO ANTERIOR (CORREGIDOS) ===
			
			-- 1) Mensualizado anterior: exactamente el mes 12m atrás (p.ej. 2024-03)
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        YEAR ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = AnioAnterior
			            && MONTH ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = MesAnterior
			    )
			
			-- 2) Acumulado anterior (YTD hasta el mes anterior): 01/01 del año anterior a fin de ese mes
			VAR FiltroPeriodoAnteriorAcumulado =
			    DATESBETWEEN(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        DATE(AnioAnterior, 1, 1),
			        EOMONTH(PeriodoAnterior, 0)
			    )
			
			-- 3) Anualizado anterior: últimos 12 meses terminando en PeriodoAnterior
			VAR FiltroPeriodoAnteriorAnualizado =
			    DATESINPERIOD(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        PeriodoAnterior,    -- fin de la ventana (incluido)
			        -12,
			        MONTH
			    )
			-- === FILTROS 2 AÑOS ANTERIORES (CORREGIDOS) ===
			
			-- 1) Mensualizado anterior: exactamente el mes 24m atrás (p.ej. 2023-03)
			VAR FiltroPeriodoAnteriorMensualizado2 =
			    FILTER (
			        ALL ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        YEAR ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = AnioAnterior2
			            && MONTH ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = MesAnterior2
			    )
			
			-- 2) Acumulado anterior (YTD hasta el mes anterior): 01/01 de 2 año anterior a fin de ese mes
			VAR FiltroPeriodoAnteriorAcumulado2 =
			    DATESBETWEEN(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        DATE(AnioAnterior2, 1, 1),
			        EOMONTH(PeriodoAnterior2, 0)
			    )
			
			-- 3) Anualizado anterior: últimos 24 meses terminando en PeriodoAnterior
			VAR FiltroPeriodoAnteriorAnualizado2 =
			    DATESINPERIOD(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        PeriodoAnterior2,    
			        -24,
			        MONTH
			    )
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			
			----------------------------------------------------------------------------------
			VAR SumColumna_ReservasParaObligacDeSiniestrosPendientes =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAcumulado
			                    )
			            )
			    )
			VAR SumColumna_ReservasParaObligacDeSiniestrosPendientesY_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			VAR SumColumna_ReservasParaObligacDeSiniestrosPendientesY_2 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado2
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado2
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado2
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado2
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado2
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado2
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado2
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado2
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado2
			                    )
			            )
			    )
			----------------------------------------------------------------------------------
			VAR SumColumna_Salvamentos_Seguros =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroAcumulado
			                    )
			            )
			    )
			VAR SumColumna_Salvamentos_SegurosY_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			VAR SumColumna_Salvamentos_SegurosY_2 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAnualizado2
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorMensualizado2
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAcumulado2
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAnualizado2
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorMensualizado2
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAcumulado2
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAnualizado2
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorMensualizado2
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAcumulado2
			                    )
			            )
			    )
			/* === Siniestros Pagados === */
			VAR SumColumna_SiniestrosPagados =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros Pagados",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros Pagados",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros Pagados",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros Pagados",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros Pagados",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros Pagados",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros Pagados",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros Pagados",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros Pagados",
			                        FiltroAcumulado
			                    )
			            )
			    )
			/* === Recuperaciones De Reaseguros Cedidos === */
			VAR SumColumna_RecuperacionesReasegurosCedidos =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones De Reaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones De Reaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones De Reaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones De Reaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones De Reaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones De Reaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones De Reaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones De Reaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones De Reaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            )
			    )
			/* === Reserva Vida === */
			VAR SumColumna_ReservaVida =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Vida",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Vida",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Vida",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Vida",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Vida",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Vida",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Vida",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Vida",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Vida",
			                        FiltroAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT =
			    ((((SumColumna_Salvamentos_Seguros - (SumColumna_ReservasParaObligacDeSiniestrosPendientes-SumColumna_ReservasParaObligacDeSiniestrosPendientesY_1) + SumColumna_ReservasParaObligacDeSiniestrosPendientes)+(SumColumna_Salvamentos_SegurosY_1+SumColumna_ReservasParaObligacDeSiniestrosPendientesY_1)+(SumColumna_Salvamentos_SegurosY_2+SumColumna_ReservasParaObligacDeSiniestrosPendientesY_2))/3)*0.35)*((SumColumna_SiniestrosPagados-SumColumna_RecuperacionesReasegurosCedidos)/SumColumna_SiniestrosPagados)+(SumColumna_ReservaVida*0.05)
			VAR REAL_Y_1 = REAL_ACT
			
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2)
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", DIVIDE(REAL_ACT,1000,0),
			    "REAL Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			    "YoY", DIVIDE(YoY,1000,0),
			    "%YoY", CapitalBase3
			)
			
			```
		displayFolder: MedidasPT
		lineageTag: 63fb5d52-19b0-4cce-af32-72dfd4dbe15d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cap. Ade. Riesgo De Crédito Por Reaseguro' = ```
			
			
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", 0.00,
			    "REAL Y-1", 0.00,
			    "YoY", 0.00,
			    "%YoY", 0.00
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: b9991a74-3d00-4556-a935-4a01975bff90

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Capital Pagado' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Capital Pagado === */
			VAR SumColumna_CapitalPagado =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_CapitalPagado_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Pagado",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_CapitalPagado
			VAR REAL_Y_1 = SumColumna_CapitalPagado_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 2fe25e95-ac9a-4704-8825-7ac6d000a8a8

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Capital Operativo' =
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Capital Operativo === */
			VAR SumColumna_CapitalOperativo =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_CapitalOperativo_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Capital Operativo",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_CapitalOperativo
			VAR REAL_Y_1 = SumColumna_CapitalOperativo_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 6f1c7cf5-31f7-428a-af25-b984d7a63ccc

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Reserva Legal' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Reserva Legal === */
			VAR SumColumna_ReservaLegal =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_ReservaLegal_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Legal",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ReservaLegal
			VAR REAL_Y_1 = SumColumna_ReservaLegal_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: 0
		displayFolder: MedidasPT
		lineageTag: 242e82ad-f56e-4a3a-b5ab-7fbe7780d1d6

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Aportes De Accionistas' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Aportes De Accionistas === */
			VAR SumColumna_AportesDeAccionistas =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_AportesDeAccionistas_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Aportes De Accionistas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_AportesDeAccionistas
			VAR REAL_Y_1 = SumColumna_AportesDeAccionistas_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 47687000-b4db-4a96-bbea-06668c521472

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Utilidad retenida (capacitaciones)' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Utilidad retenida (capacitaciones) === */
			VAR SumColumna_Utilidad_retenida_capacitaciones =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_Utilidad_retenida_capacitaciones_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad retenida (capacitaciones)",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_Utilidad_retenida_capacitaciones
			VAR REAL_Y_1 = SumColumna_Utilidad_retenida_capacitaciones_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: a4d00e15-22ff-4187-8eeb-8b34e9d2a55d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Dividendos Acción' =
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Dividendos Acción === */
			VAR SumColumna_DividendosAccion =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_DividendosAccion_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Dividendos Acción",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_DividendosAccion
			VAR REAL_Y_1 = SumColumna_DividendosAccion_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: a6a87356-6cb8-411a-a3ac-c2ed9b4b1ac7

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Reserva Desviación De Siniestralidad Y Catastrófica' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Reserva Desviación De Siniestralidad Y Catastrófica === */
			VAR SumColumna_ReservaDesviacionDeSiniestralidadYCatastrofica =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_ReservaDesviacionDeSiniestralidadYCatastrofica_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Desviación De Siniestralidad Y Catastrófica",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ReservaDesviacionDeSiniestralidadYCatastrofica
			VAR REAL_Y_1 = SumColumna_ReservaDesviacionDeSiniestralidadYCatastrofica_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: ff17f64a-0364-4422-9a05-0e4cdd7cdd7a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Utilidad Ret. Futuras Capitalizaciones' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Utilidad Ret. Futuras Capitalizaciones === */
			VAR SumColumna_UtilidadRetFuturasCapitalizaciones =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ), 
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_UtilidadRetFuturasCapitalizaciones_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Utilidad Ret. Futuras Capitalizaciones",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_UtilidadRetFuturasCapitalizaciones
			VAR REAL_Y_1 = SumColumna_UtilidadRetFuturasCapitalizaciones_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 198edfef-b5af-46f3-93db-0bbbb7c0df18

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Otras (Pts)' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Otras (Pts) === */
			VAR SumColumna_OtrasPts =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ), 
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_OtrasPts_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Otras (Pts)",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_OtrasPts
			VAR REAL_Y_1 = SumColumna_OtrasPts_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: a160d973-7fd8-414f-b856-ee73240faf32

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '45% Reserva Legal Pts' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === 45% Reserva Legal Pts === */
			VAR SumColumna_45ReservaLegalPts =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ), 
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_45ReservaLegalPts_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "45% Reserva Legal Pts",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_45ReservaLegalPts
			VAR REAL_Y_1 = SumColumna_45ReservaLegalPts_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: f57aacb2-25cb-4c7f-8ab0-722fc373ad33

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Resultados Acumulados Utilidades' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Resultados Acumulados Utilidades === */
			VAR SumColumna_ResultadosAcumuladosUtilidades =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ), 
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_ResultadosAcumuladosUtilidades_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Acumulados Utilidades",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ResultadosAcumuladosUtilidades
			VAR REAL_Y_1 = SumColumna_ResultadosAcumuladosUtilidades_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: fafaa6fb-5340-4153-8423-5219a5d50ffe

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Resultado Del Ejercicio Utilidades' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Resultado Del Ejercicio Utilidades === */
			VAR SumColumna_ResultadoDelEjercicioUtilidades =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ), 
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_ResultadoDelEjercicioUtilidades_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio Utilidades", 
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ResultadoDelEjercicioUtilidades
			VAR REAL_Y_1 = SumColumna_ResultadoDelEjercicioUtilidades_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 6a06d9d1-3ccb-4d52-917e-d135700406f0

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Resultados Del Ejercicio Pérdidas' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Resultados Del Ejercicio Pérdidas === */
			VAR SumColumna_ResultadosDelEjercicioPerdidas =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ), 
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_ResultadosDelEjercicioPerdidas_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio Pérdidas", 
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ResultadosDelEjercicioPerdidas
			VAR REAL_Y_1 = SumColumna_ResultadosDelEjercicioPerdidas_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 0ebfef44-8a60-4501-9746-6d47e1f308b8

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Resultado Del Ejercicio (Pts)' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === RESULTADOS DEL EJERCICIO UTILIDADES   === */ 
			VAR SumColumna_RESULTADOSDELEJERCICIOUTILIDADES =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio (Pts)",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio (Pts)",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio (Pts)",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "RESULTADOS DEL EJERCICIO UTILIDADES  ",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "RESULTADOS DEL EJERCICIO UTILIDADES  ",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "RESULTADOS DEL EJERCICIO UTILIDADES  ",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "RESULTADOS DEL EJERCICIO UTILIDADES  ",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "RESULTADOS DEL EJERCICIO UTILIDADES  ",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "RESULTADOS DEL EJERCICIO UTILIDADES  ",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			
			---------------------------------------Y-1
			VAR SumColumna_RESULTADOSDELEJERCICIOUTILIDADES_1 =  
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio (Pts)",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio (Pts)",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultado Del Ejercicio (Pts)",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "RESULTADOS DEL EJERCICIO UTILIDADES  ",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "RESULTADOS DEL EJERCICIO UTILIDADES  ",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "RESULTADOS DEL EJERCICIO UTILIDADES  ",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "RESULTADOS DEL EJERCICIO UTILIDADES  ",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "RESULTADOS DEL EJERCICIO UTILIDADES  ",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "RESULTADOS DEL EJERCICIO UTILIDADES  ",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			
			
			/* === Fórmula base === */
			VAR REAL_ACT =
			    SumColumna_RESULTADOSDELEJERCICIOUTILIDADES
			
			VAR REAL_Y_1 =
			    SumColumna_RESULTADOSDELEJERCICIOUTILIDADES_1 
			
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 0fe2482a-4913-431e-a6e4-00e996b201e3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'REQUERIMIENTO DE CAPITAL ADECUADO' = [Capital Adecuado por Primas]+[Cap. Ade. Por Carga Media De Siniestralidad2]+[Cap. Ade. Riesgo De Crédito Por Reaseguro]+[Cap. Ade. Factor De Corrección Por Concentración]
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: a4b5cecb-d178-4491-80e0-79f8ee39cdc2

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Cap. Ade. Factor De Corrección Por Concentración' = ```
			
			VAR a = [Cap. Ade. Por Carga Media De Siniestralidad]
			VAR b = [Capital Adecuado por Primas]
			VAR mayor = MAX ( a, b )
			RETURN
			IF ( ISBLANK ( mayor ), BLANK (), mayor * 0.2 )
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: fb6dcbcf-8619-4a48-adc1-e02556ebcf31

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'PATRIMONIO TÉCNICO PRIMARIO' = [Capital Pagado]+[Capital Operativo]+[Reserva Legal]+[Aportes De Accionistas]+[Utilidad retenida (capacitaciones)]+[Dividendos Acción]+[Resultados Del Ejercicio]+[Reserva Desviación De Siniestralidad Y Catastrófica]
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 61abce70-cd14-4984-a1b4-b8876236e0d3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Resultados Del Ejercicio' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Resultados Del Ejercicio === */
			VAR SumColumna_Resultados_Ejercicio =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_Resultados_Ejercicio_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Resultados Del Ejercicio",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_Resultados_Ejercicio
			VAR REAL_Y_1 = SumColumna_Resultados_Ejercicio_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: ae0dffb8-31a7-4b4e-8b8c-106e0ff5e50d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'PATRIMONIO TÉCNICO SECUNDARIO' = [Utilidad Ret. Futuras Capitalizaciones]+[Otras (Pts)]+[45% Reserva Legal Pts]+[Resultados Acumulados Utilidades]+[Resultado Del Ejercicio Utilidades]+[Resultados Del Ejercicio Pérdidas]+[Resultado Del Ejercicio (Pts)]
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: a0ced709-dafb-4a26-9079-f2e7dfa11f29

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'TOTAL PATRIMONIO TÉCNICO' = [PATRIMONIO TÉCNICO PRIMARIO] + [PATRIMONIO TÉCNICO SECUNDARIO]
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 4bbdf1ca-a375-44cc-9672-0b82a272a222

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Patrimonio Técnico Requerido' = [Cap. Ade. Factor De Corrección Por Concentración]
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 9d20af9e-947b-42cc-a87a-dd232551f242

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Patrimonio Técnico Reportado' = [TOTAL PATRIMONIO TÉCNICO]
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: cc8a1163-b7b6-49e2-959f-045dcf435957

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Excedente / Deficit' = ```
			
			VAR PeriodoSeleccionado = MAX(gd_grupo_contable2[fec_periodo_fecha_PT])
			VAR AnioActual = YEAR(PeriodoSeleccionado)
			VAR MesActual  = MONTH(PeriodoSeleccionado)
			
			-- Normalizo a primer día del mes por seguridad
			VAR MesActual_Inicio = DATE(AnioActual, MesActual, 1)
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE(MesActual_Inicio, -12)
			VAR AnioAnterior    = YEAR(PeriodoAnterior)
			VAR MesAnterior     = MONTH(PeriodoAnterior)
			
			-- === FILTROS ACTUALES ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        YEAR ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = AnioActual
			            && MONTH ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    DATESBETWEEN(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        DATE(AnioActual, 1, 1),
			        EOMONTH(MesActual_Inicio, 0)
			    )
			
			VAR FiltroAnualizado =
			    DATESINPERIOD(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        MesActual_Inicio,   -- fin de la ventana (mes actual, incluido)
			        -12,
			        MONTH
			    )
			
			-- === FILTROS ANTERIORES (CORREGIDOS) ===
			
			-- 1) Mensualizado anterior: exactamente el mes 12m atrás (p.ej. 2024-03)
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        YEAR ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = AnioAnterior
			            && MONTH ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = MesAnterior
			    )
			
			-- 2) Acumulado anterior (YTD hasta el mes anterior): 01/01 del año anterior a fin de ese mes
			VAR FiltroPeriodoAnteriorAcumulado =
			    DATESBETWEEN(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        DATE(AnioAnterior, 1, 1),
			        EOMONTH(PeriodoAnterior, 0)
			    )
			
			-- 3) Anualizado anterior: últimos 12 meses terminando en PeriodoAnterior
			VAR FiltroPeriodoAnteriorAnualizado =
			    DATESINPERIOD(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        PeriodoAnterior,    -- fin de la ventana (incluido)
			        -12,
			        MONTH
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === EXCEDENTE / DEFICIT === */
			VAR SumColumna_ExcedenteDeficit =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ), 
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_ExcedenteDeficit_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ExcedenteDeficit
			VAR REAL_Y_1 = SumColumna_ExcedenteDeficit_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2)
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", DIVIDE(REAL_ACT,1000,0),
			    "REAL Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			    "YoY", DIVIDE(YoY,1000,0),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 7cfd24c7-c035-48bf-978f-598694cece79

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'KPI Capital Adecuado por Primas' = ```
			
			VAR PeriodoSeleccionado = MAX(gd_grupo_contable2[fec_periodo_fecha_PT])
			VAR AnioActual = YEAR(PeriodoSeleccionado)
			VAR MesActual  = MONTH(PeriodoSeleccionado)
			
			-- Normalizo a primer día del mes por seguridad
			VAR MesActual_Inicio = DATE(AnioActual, MesActual, 1)
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE(MesActual_Inicio, -12)
			VAR AnioAnterior    = YEAR(PeriodoAnterior)
			VAR MesAnterior     = MONTH(PeriodoAnterior)
			
			-- === FILTROS ACTUALES ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        YEAR ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = AnioActual
			            && MONTH ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    DATESBETWEEN(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        DATE(AnioActual, 1, 1),
			        EOMONTH(MesActual_Inicio, 0)
			    )
			
			VAR FiltroAnualizado =
			    DATESINPERIOD(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        MesActual_Inicio,   -- fin de la ventana (mes actual, incluido)
			        -12,
			        MONTH
			    )
			
			-- === FILTROS ANTERIORES (CORREGIDOS) ===
			
			-- 1) Mensualizado anterior: exactamente el mes 12m atrás (p.ej. 2024-03)
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        YEAR ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = AnioAnterior
			            && MONTH ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = MesAnterior
			    )
			
			-- 2) Acumulado anterior (YTD hasta el mes anterior): 01/01 del año anterior a fin de ese mes
			VAR FiltroPeriodoAnteriorAcumulado =
			    DATESBETWEEN(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        DATE(AnioAnterior, 1, 1),
			        EOMONTH(PeriodoAnterior, 0)
			    )
			
			-- 3) Anualizado anterior: últimos 12 meses terminando en PeriodoAnterior
			VAR FiltroPeriodoAnteriorAnualizado =
			    DATESINPERIOD(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        PeriodoAnterior,    -- fin de la ventana (incluido)
			        -12,
			        MONTH
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Primas Brutas - Coaseguros Cedidos === */
			VAR SumColumna_PrimasBrutasCedidas =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			/* === Primas Netas Vida Individual === */
			VAR SumColumna_PrimasNetasVI =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			/* === Factor de Retención cap === */
			VAR SumColumna_FactorRetencion =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			/* === Reserva Matemática 5% === */
			VAR SumColumna_ReservaMat5 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_PrimasBrutasCedidas_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Primas Netas Vida Individual === */
			VAR SumColumna_PrimasNetasVI_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Netas Vida Individual",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Factor de Retención cap === */
			VAR SumColumna_FactorRetencion_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Factor de Retención cap",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Reserva Matemática 5% === */
			VAR SumColumna_ReservaMat5_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Reserva Matemática 5%",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT =
			    ( SumColumna_PrimasBrutasCedidas - SumColumna_PrimasNetasVI * 0.23 )
			    * SumColumna_FactorRetencion
			    + SumColumna_ReservaMat5
			VAR REAL_Y_1 =
			    ( SumColumna_PrimasBrutasCedidas_1 - SumColumna_PrimasNetasVI_1 * 0.23 )
			    * SumColumna_FactorRetencion_1
			    + SumColumna_ReservaMat5_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2)
			VAR TipoCalculo =
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo], "REAL ACT")
			
			RETURN
			SWITCH (
			    TipoCalculo,
			    "REAL ACT", DIVIDE(REAL_ACT,1000,0),
			    "REAL Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			    "YoY", DIVIDE(YoY,1000,0),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 47d8c05d-1a37-4117-80a2-b50dcd5b3c7f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'KPI Patrimonio Técnico Reportado' =
			
			VAR TipoCalculo =
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo], "REAL ACT")
			
			RETURN
			SWITCH (
			    TipoCalculo,
			    "REAL ACT",[Patrimonio Técnico Reportado]
			)
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 765b7986-fddc-433f-9b96-c306aec8d9da

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'KPI Excedente / Deficit' = ```
			
			VAR PeriodoSeleccionado = MAX(gd_grupo_contable2[fec_periodo_fecha_PT])
			VAR AnioActual = YEAR(PeriodoSeleccionado)
			VAR MesActual  = MONTH(PeriodoSeleccionado)
			
			-- Normalizo a primer día del mes por seguridad
			VAR MesActual_Inicio = DATE(AnioActual, MesActual, 1)
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE(MesActual_Inicio, -12)
			VAR AnioAnterior    = YEAR(PeriodoAnterior)
			VAR MesAnterior     = MONTH(PeriodoAnterior)
			
			-- === FILTROS ACTUALES ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        YEAR ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = AnioActual
			            && MONTH ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    DATESBETWEEN(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        DATE(AnioActual, 1, 1),
			        EOMONTH(MesActual_Inicio, 0)
			    )
			
			VAR FiltroAnualizado =
			    DATESINPERIOD(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        MesActual_Inicio,   -- fin de la ventana (mes actual, incluido)
			        -12,
			        MONTH
			    )
			
			-- === FILTROS ANTERIORES (CORREGIDOS) ===
			
			-- 1) Mensualizado anterior: exactamente el mes 12m atrás (p.ej. 2024-03)
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        YEAR ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = AnioAnterior
			            && MONTH ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = MesAnterior
			    )
			
			-- 2) Acumulado anterior (YTD hasta el mes anterior): 01/01 del año anterior a fin de ese mes
			VAR FiltroPeriodoAnteriorAcumulado =
			    DATESBETWEEN(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        DATE(AnioAnterior, 1, 1),
			        EOMONTH(PeriodoAnterior, 0)
			    )
			
			-- 3) Anualizado anterior: últimos 12 meses terminando en PeriodoAnterior
			VAR FiltroPeriodoAnteriorAnualizado =
			    DATESINPERIOD(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        PeriodoAnterior,    -- fin de la ventana (incluido)
			        -12,
			        MONTH
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === EXCEDENTE / DEFICIT === */
			VAR SumColumna_ExcedenteDeficit =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ), 
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_ExcedenteDeficit_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "EXCEDENTE / DEFICIT",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ExcedenteDeficit
			VAR REAL_Y_1 = SumColumna_ExcedenteDeficit_1
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2)
			VAR TipoCalculo =
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo], "REAL ACT")
			
			RETURN
			SWITCH (
			    TipoCalculo,
			    "REAL ACT", DIVIDE(REAL_ACT,1000,0),
			    "REAL Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			    "YoY", DIVIDE(YoY,1000,0),
			    "%YoY", CapitalBase3
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 696f1896-6f52-40a3-92c9-de2727e38544

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'KPI %EXCEDENTE CAP. REQ' = DIVIDE([Patrimonio Técnico Reportado]-[Patrimonio Técnico Requerido],[Patrimonio Técnico Requerido],0)
		formatString: #,0\ %;-#,0\ %;#,0\ %
		displayFolder: MedidasPT
		lineageTag: 62a936e7-c01c-4401-a0d6-b099b1eb5cf2

	measure 'PRIMAS ANUALIZADAS' = ```
			
			VAR PeriodoSeleccionado = MAX(gd_grupo_contable2[fec_periodo_fecha_PT])
			VAR AnioActual = YEAR(PeriodoSeleccionado)
			VAR MesActual  = MONTH(PeriodoSeleccionado)
			
			-- Normalizo a primer día del mes por seguridad
			VAR MesActual_Inicio = DATE(AnioActual, MesActual, 1)
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE(MesActual_Inicio, -12)
			VAR AnioAnterior    = YEAR(PeriodoAnterior)
			VAR MesAnterior     = MONTH(PeriodoAnterior)
			
			-- === FILTROS ACTUALES ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        YEAR ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = AnioActual
			            && MONTH ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    DATESBETWEEN(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        DATE(AnioActual, 1, 1),
			        EOMONTH(MesActual_Inicio, 0)
			    )
			
			VAR FiltroAnualizado =
			    DATESINPERIOD(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        MesActual_Inicio,   -- fin de la ventana (mes actual, incluido)
			        -12,
			        MONTH
			    )
			
			-- === FILTROS ANTERIORES (CORREGIDOS) ===
			
			-- 1) Mensualizado anterior: exactamente el mes 12m atrás (p.ej. 2024-03)
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        YEAR ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = AnioAnterior
			            && MONTH ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = MesAnterior
			    )
			
			-- 2) Acumulado anterior (YTD hasta el mes anterior): 01/01 del año anterior a fin de ese mes
			VAR FiltroPeriodoAnteriorAcumulado =
			    DATESBETWEEN(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        DATE(AnioAnterior, 1, 1),
			        EOMONTH(PeriodoAnterior, 0)
			    )
			
			-- 3) Anualizado anterior: últimos 12 meses terminando en PeriodoAnterior
			VAR FiltroPeriodoAnteriorAnualizado =
			    DATESINPERIOD(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        PeriodoAnterior,    -- fin de la ventana (incluido)
			        -12,
			        MONTH
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Primas Brutas - Coaseguros Cedidos === */
			VAR SumColumna_PrimasBrutasCedidas =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_PrimasBrutasCedidas_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas - Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT =
			    ( SumColumna_PrimasBrutasCedidas)
			   
			VAR REAL_Y_1 =
			    ( SumColumna_PrimasBrutasCedidas_1 )
			    
			VAR YoY = REAL_ACT - REAL_Y_1
			
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", DIVIDE(REAL_ACT,1000,0),
			    "REAL Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			    "YoY", DIVIDE(YoY,1000,0),
			    "%YoY"
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: 5a7dd546-a198-45ab-bf30-08a36373da4c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'EXCEDENTE PATRIMONIO TÉCNICO' = 1
		formatString: 0
		displayFolder: MedidasPT
		lineageTag: 47bfc891-59ec-4dcf-86f5-f86e178a5d09

	measure 'Coaseguros Cedidos' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Coaseguros Cedidos === */
			VAR SumColumna_CoasegurosCedidos =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            )
			    )
			------------------------------------------------
			VAR SumColumna_CoasegurosCedidosPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_CoasegurosCedidos_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_CoasegurosCedidos  
			VAR REAL_Y_1 = SumColumna_CoasegurosCedidos_1
			VAR Ppto = SumColumna_CoasegurosCedidosPpto
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", COALESCE (DIVIDE ( -REAL_ACT, 1000, 0 ), 0 ),
			    "Ppto",     COALESCE (DIVIDE ( -Ppto, 1000, 0 ),0 ),
			    "% Cumpl.", COALESCE (DIVIDE ( REAL_ACT, Ppto, 0 ),0 ),
			    "Real Y-1", COALESCE ( DIVIDE ( -REAL_Y_1, 1000, 0 ), 0 ),
			    "%YoY",     COALESCE (DIVIDE ( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ),0 )
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 02c7cd03-627f-47d2-b752-c5947a5c02bc

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Primas Brutas' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE( SelectorValor[TipoValor] )
			VAR TipoData  = SELECTEDVALUE( SelectorData[TipoData] )
			
			/* === Primas Brutas === */
			VAR SumColumna_PrimasBrutas =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_PrimasBrutas_Ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			VAR SumColumna_PrimasBrutas_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			VAR REAL_ACT = SumColumna_PrimasBrutas
			VAR REAL_Y_1 = SumColumna_PrimasBrutas_1
			VAR Ppto     = SumColumna_PrimasBrutas_Ppto
			
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", ROUND( COALESCE( DIVIDE( REAL_ACT, 1000, 0 ), 0 ), 0 ),
			    "Ppto",     ROUND( COALESCE( DIVIDE( Ppto, 1000, 0 ), 0 ), 0 ),
			    "% Cumpl.", ROUND( COALESCE( DIVIDE( REAL_ACT, Ppto, 0 ), 0 ), 2 ),
			    "Real Y-1", ROUND( COALESCE( DIVIDE( REAL_Y_1, 1000, 0 ), 0 ), 0 ),
			    "%YoY",     ROUND( COALESCE( DIVIDE( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ), 0 ), 2 )
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 0130b130-76fb-48f4-9db9-08a5b6e74702

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Cesión de Reaseguros' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Cesión de Reaseguros === */
			VAR SumColumna_CesiondeReaseguros =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroAcumulado
			                    )
			            )
			    )
			------------------------------------------
			VAR SumColumna_CesiondeReasegurosPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_CesiondeReaseguros_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Cesión de Reaseguros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_CesiondeReaseguros 
			   
			VAR REAL_Y_1 = SumColumna_CesiondeReaseguros_1
			VAR Ppto = SumColumna_CesiondeReasegurosPpto
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", COALESCE (DIVIDE ( -REAL_ACT, 1000, 0 ), 0 ),
			    "Ppto",     COALESCE (DIVIDE ( -Ppto, 1000, 0 ),0 ),
			    "% Cumpl.", COALESCE (DIVIDE ( REAL_ACT, Ppto, 0 ),0 ),
			    "Real Y-1", COALESCE ( DIVIDE ( -REAL_Y_1, 1000, 0 ), 0 ),
			    "%YoY",     COALESCE (DIVIDE ( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ),0 )
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: bf10fbec-608d-4fc4-829d-5ef91ac9074f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Excesos de Pérdida' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Excesos de Pérdida === */
			VAR SumColumna_ExcesosdePerdida =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------------
			VAR SumColumna_ExcesosdePerdidaPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_ExcesosdePerdida_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Excesos de Pérdida",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ExcesosdePerdida
			   
			VAR REAL_Y_1 = SumColumna_ExcesosdePerdida_1
			VAR Ppto = SumColumna_ExcesosdePerdidaPpto
				
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", COALESCE (DIVIDE ( -REAL_ACT, 1000, 0 ), 0 ),
			    "Ppto",     COALESCE (DIVIDE ( -Ppto, 1000, 0 ),0 ),
			    "% Cumpl.", COALESCE (DIVIDE ( REAL_ACT, Ppto, 0 ),0 ),
			    "Real Y-1", COALESCE ( DIVIDE ( -REAL_Y_1, 1000, 0 ), 0 ),
			    "%YoY",     COALESCE (DIVIDE ( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ),0 )
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: fbee0279-5929-4393-8d35-77ec5a6b0a5e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Constitución RRC' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Constitución RRC === */
			VAR SumColumna_ConstitucionRRC =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroAcumulado
			                    )
			            )
			    )
			-----------
			VAR SumColumna_ConstitucionRRCPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroAcumulado
			                    )
			            )
			    )
			
			---------------------------------------Y-1
			VAR SumColumna_ConstitucionRRC_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Constitución RRC",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ConstitucionRRC
			VAR REAL_Y_1 = SumColumna_ConstitucionRRC_1
			VAR Ppto = SumColumna_ConstitucionRRCPpto
				
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", ROUND( COALESCE( DIVIDE( -REAL_ACT, 1000, 0 ), 0 ), 0 ),
			    "Ppto",     ROUND( COALESCE( DIVIDE( -Ppto, 1000, 0 ), 0 ), 0 ),
			    "% Cumpl.", ROUND( COALESCE( DIVIDE( REAL_ACT, Ppto, 0 ), 0 ), 2 ),
			    "Real Y-1", ROUND( COALESCE( DIVIDE( -REAL_Y_1, 1000, 0 ), 0 ), 0 ),
			    "%YoY",     ROUND( COALESCE( DIVIDE( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ), 0 ), 2 )
			)
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 2475e45d-6b53-44c2-89e7-b3a61227ba29

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Siniestros pagados' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Siniestros pagados === */
			VAR SumColumna_Siniestrospagados =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroAcumulado
			                    )
			            )
			    )
			-----------
			VAR SumColumna_SiniestrospagadosPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_Siniestrospagados_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Siniestros pagados",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_Siniestrospagados 
			   
			VAR REAL_Y_1 = SumColumna_Siniestrospagados_1
			   
			VAR Ppto = SumColumna_SiniestrospagadosPpto
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", COALESCE (DIVIDE ( -REAL_ACT, 1000, 0 ), 0 ),
			    "Ppto",     COALESCE (DIVIDE ( -Ppto, 1000, 0 ),0 ),
			    "% Cumpl.", COALESCE (DIVIDE ( REAL_ACT, Ppto, 0 ),0 ),
			    "Real Y-1", COALESCE ( DIVIDE ( -REAL_Y_1, 1000, 0 ), 0 ),
			    "%YoY",     COALESCE (DIVIDE ( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ),0 )
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: be6c4a35-e8ef-4bc9-a0d3-418596b04f3e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Recuperaciones siniestros' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Recuperaciones siniestros === */
			VAR SumColumna_RecuperacionesSiniestros =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroAcumulado
			                    )
			            )
			    )
			-------------
			VAR SumColumna_RecuperacionesSiniestrosPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_RecuperacionesSiniestros_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Recuperaciones siniestros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_RecuperacionesSiniestros
			   
			VAR REAL_Y_1 = SumColumna_RecuperacionesSiniestros_1
			VAR Ppto = SumColumna_RecuperacionesSiniestrosPpto
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", ROUND( COALESCE( DIVIDE( REAL_ACT, 1000, 0 ), 0 ), 0 ),
			    "Ppto",     ROUND( COALESCE( DIVIDE( Ppto, 1000, 0 ), 0 ), 0 ),
			    "% Cumpl.", ROUND( COALESCE( DIVIDE( REAL_ACT, Ppto, 0 ), 0 ), 2 ),
			    "Real Y-1", ROUND( COALESCE( DIVIDE( REAL_Y_1, 1000, 0 ), 0 ), 0 ),
			    "%YoY",     ROUND( COALESCE( DIVIDE( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ), 0 ), 2 )
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 20c08f3c-8fd9-44b5-96c8-9ff6e302b9ad

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Ajuste Reserva Siniestros' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Ajuste Reserva Siniestros === */
			VAR SumColumna_AjusteReservaSiniestros =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroAcumulado
			                    )
			            )
			    )
			----------------------
			VAR SumColumna_AjusteReservaSiniestrosPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_AjusteReservaSiniestros_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Ajuste Reserva Siniestros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_AjusteReservaSiniestros
			   
			VAR REAL_Y_1 = SumColumna_AjusteReservaSiniestros_1
			VAR Ppto = SumColumna_AjusteReservaSiniestrosPpto
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", COALESCE (DIVIDE ( REAL_ACT, 1000, 0 ), 0 ),
			    "Ppto",     COALESCE (DIVIDE ( Ppto, 1000, 0 ),0 ),
			    "% Cumpl.", COALESCE (DIVIDE ( REAL_ACT, Ppto, 0 ),0 ),
			    "Real Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "%YoY",     COALESCE (DIVIDE ( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ),0 )
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 5c697042-7405-4244-8dcd-8e7f258b40e0

		annotation PBI_FormatHint = {"isDecimal":true}

	measure IBNR = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === IBNR === */
			VAR SumColumna_IBNR =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroAcumulado
			                    )
			            )
			    )
			VAR SumColumna_IBNRPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_IBNR_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "IBNR",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_IBNR
			   
			VAR REAL_Y_1 = SumColumna_IBNR_1
			VAR Ppto = SumColumna_IBNRPpto
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", COALESCE (DIVIDE ( REAL_ACT, 1000, 0 ), 0 ),
			    "Ppto",     COALESCE (DIVIDE ( Ppto, 1000, 0 ),0 ),
			    "% Cumpl.", COALESCE (DIVIDE ( REAL_ACT, Ppto, 0 ),0 ),
			    "Real Y-1", COALESCE (DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "%YoY",     COALESCE (DIVIDE ( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ),0 )
			)
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 261942e6-b1e6-48c0-b293-3fb93d9f253f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Comisiones Pagadas' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Comisiones Pagadas === */
			VAR SumColumna_ComisionesPagadas =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------
			VAR SumColumna_ComisionesPagadasPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_ComisionesPagadas_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Pagadas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ComisionesPagadas
			   
			VAR REAL_Y_1 = SumColumna_ComisionesPagadas_1
			VAR Ppto = SumColumna_ComisionesPagadasPpto
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", COALESCE (DIVIDE ( -REAL_ACT, 1000, 0 ), 0 ),
			    "Ppto",     COALESCE (DIVIDE ( -Ppto, 1000, 0 ),0 ),
			    "% Cumpl.", COALESCE (DIVIDE ( REAL_ACT, Ppto, 0 ),0 ),
			    "Real Y-1", COALESCE ( DIVIDE ( -REAL_Y_1, 1000, 0 ), 0 ),
			    "%YoY",     COALESCE (DIVIDE ( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ),0 )
			)
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 769ba88c-eba0-419b-a0b1-6b6a28d21abd

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Comisiones Ganadas' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Comisiones Ganadas === */
			VAR SumColumna_ComisionesGanadas =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroAcumulado
			                    )
			            )
			    )
			----------------------
			VAR SumColumna_ComisionesGanadasPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_ComisionesGanadas_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Comisiones Ganadas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ComisionesGanadas
			   
			VAR REAL_Y_1 = SumColumna_ComisionesGanadas_1
			VAR Ppto = SumColumna_ComisionesGanadasPpto
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", ROUND( COALESCE( DIVIDE( REAL_ACT, 1000, 0 ), 0 ), 0 ),
			    "Ppto",     ROUND( COALESCE( DIVIDE( Ppto, 1000, 0 ), 0 ), 0 ),
			    "% Cumpl.", ROUND( COALESCE( DIVIDE( REAL_ACT, Ppto, 0 ), 0 ), 2 ),
			    "Real Y-1", ROUND( COALESCE( DIVIDE( REAL_Y_1, 1000, 0 ), 0 ), 0 ),
			    "%YoY",     ROUND( COALESCE( DIVIDE( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ), 0 ), 2 )
			)
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: f9783a89-570d-4ac4-a59a-97b7d60a583d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Costo de Siniestros' = [Siniestros pagados]+[Recuperaciones siniestros]+[Ajuste Reserva Siniestros]+[IBNR]
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 625a72ce-77f6-4522-9a6d-87dad3278e20

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'NETO COMISIONES' = [Comisiones Ganadas]+[Comisiones Pagadas]
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: b239e8c1-2c19-4231-808c-14eadbb082f0

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Ingresos Financieros' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Ingresos Financieros === */
			VAR SumColumna_IngresosFinancieros =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroAcumulado
			                    )
			            )
			    )
			-----
			VAR SumColumna_IngresosFinancierosPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_IngresosFinancieros_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Ingresos Financieros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_IngresosFinancieros
			VAR REAL_Y_1 = SumColumna_IngresosFinancieros_1
			VAR Ppto = SumColumna_IngresosFinancierosPpto
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act",COALESCE( DIVIDE( REAL_ACT, 1000, 0 ), 0 ),
			    "Ppto",    COALESCE( DIVIDE( Ppto, 1000, 0 ), 0 ), 
			    "% Cumpl.", COALESCE( DIVIDE( REAL_ACT, Ppto, 0 ), 0 ),
			    "Real Y-1",COALESCE( DIVIDE( REAL_Y_1, 1000, 0 ), 0 ),
			    "%YoY",     COALESCE( DIVIDE( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ), 0 )
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: e60254ce-8500-49c7-9464-4a1b80c1fc6a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Gastos Administrativos' =
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Gastos Administrativos === */
			VAR SumColumna_GastosAdministrativos =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAcumulado
			                    )
			            )
			    )
			-------------
			VAR SumColumna_GastosAdministrativosPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_GastosAdministrativos_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_GastosAdministrativos
			VAR REAL_Y_1 = SumColumna_GastosAdministrativos_1
			VAR Ppto = SumColumna_GastosAdministrativosPpto
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", COALESCE (DIVIDE ( -REAL_ACT, 1000, 0 ), 0 ),
			    "Ppto",     COALESCE (DIVIDE ( -Ppto, 1000, 0 ),0 ),
			    "% Cumpl.", COALESCE (DIVIDE ( REAL_ACT, Ppto, 0 ),0 ),
			    "Real Y-1", COALESCE ( DIVIDE ( -REAL_Y_1, 1000, 0 ), 0 ),
			    "%YoY",     COALESCE (DIVIDE ( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ),0 )
			)
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 67be0533-0135-4a3d-bc1e-1c3f586b8c4c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Provisiones y Otros Imp.' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Provisiones y Otros Imp. === */
			VAR SumColumna_rovisionesyOtrosImp =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------
			VAR SumColumna_rovisionesyOtrosImpPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_rovisionesyOtrosImp_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Provisiones y Otros Imp.",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_rovisionesyOtrosImp
			   
			VAR REAL_Y_1 = SumColumna_rovisionesyOtrosImp_1
			VAR Ppto = SumColumna_rovisionesyOtrosImpPpto
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", COALESCE (DIVIDE ( -REAL_ACT, 1000, 0 ), 0 ),
			    "Ppto",     COALESCE (DIVIDE ( -Ppto, 1000, 0 ),0 ),
			    "% Cumpl.", COALESCE (DIVIDE ( REAL_ACT, Ppto, 0 ),0 ),
			    "Real Y-1", COALESCE ( DIVIDE ( -REAL_Y_1, 1000, 0 ), 0 ),
			    "%YoY",     COALESCE (DIVIDE ( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ),0 )
			)
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: bab67e8b-a38f-4438-8059-20cf227dd1a0

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Participación Trabajadores' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Participación Trabajadores === */
			VAR SumColumna_ParticipacionTrabajadores =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroAcumulado
			                    )
			            )
			    )
			-----------
			VAR SumColumna_ParticipacionTrabajadoresPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_ParticipacionTrabajadores_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Participación Trabajadores",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ParticipacionTrabajadores
			   
			VAR REAL_Y_1 = SumColumna_ParticipacionTrabajadores_1
			VAR Ppto = SumColumna_ParticipacionTrabajadoresPpto
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", COALESCE (DIVIDE ( -REAL_ACT, 1000, 0 ), 0 ),
			    "Ppto",     COALESCE (DIVIDE ( -Ppto, 1000, 0 ),0 ),
			    "% Cumpl.", COALESCE (DIVIDE ( REAL_ACT, Ppto, 0 ),0 ),
			    "Real Y-1", COALESCE ( DIVIDE ( -REAL_Y_1, 1000, 0 ), 0 ),
			    "%YoY",     COALESCE (DIVIDE ( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ),0 )
			)
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 735aea09-4ed5-40a4-9f9b-c4a18deda811

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Impuesto a la Renta' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Impuesto a la Renta === */
			VAR SumColumna_ImpuestoalaRenta =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroAcumulado
			                    )
			            )
			    )
			-----
			VAR SumColumna_ImpuestoalaRentaPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_ImpuestoalaRenta_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_mes] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Impuesto a la Renta",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			
			/* === Fórmula base === */
			VAR REAL_ACT = SumColumna_ImpuestoalaRenta
			   
			VAR REAL_Y_1 = SumColumna_ImpuestoalaRenta_1
			VAR Ppto = SumColumna_ImpuestoalaRentaPpto
			RETURN
			SWITCH (
			    SELECTEDVALUE ( SelectorCalculo_PG[TipoCalculo] ),
			    "Real Act", COALESCE (DIVIDE ( -REAL_ACT, 1000, 0 ), 0 ),
			    "Ppto",     COALESCE (DIVIDE ( -Ppto, 1000, 0 ),0 ),
			    "% Cumpl.", COALESCE (DIVIDE ( REAL_ACT, Ppto, 0 ),0 ),
			    "Real Y-1", COALESCE ( DIVIDE ( -REAL_Y_1, 1000, 0 ), 0 ),
			    "%YoY",     COALESCE (DIVIDE ( REAL_ACT - REAL_Y_1, REAL_Y_1, 0 ),0 )
			)
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 04255677-430f-4604-984a-0f649150f2c3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure EBIT = [RESULTADO TÉCNICO]+[Ingresos Financieros]+[Gastos Administrativos]+[Provisiones y Otros Imp.]
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 231077d5-3a00-4af2-bf7b-47a132306650

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'UTILIDAD NETA' = [EBIT]+ [Participación Trabajadores]+[Impuesto a la Renta]
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 44e17ab2-6564-4e04-8926-5bb819e2e57c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'PRIMAS NETAS' = [Primas Brutas]+[Coaseguros Cedidos]+[Cesión de Reaseguros]
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: f7936871-b962-4537-9111-ea0252cba9d3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'PRIMAS DEVENGADAS' = ```
			+[PRIMAS NETAS]+[Excesos de Pérdida]+[Constitución RRC]
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 53c9313c-9054-41e2-87ab-b3ddf89cf3b7

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'RESULTADO TÉCNICO' = ```
			[PRIMAS DEVENGADAS]+[Costo de Siniestros]+[NETO COMISIONES]
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: e0b05042-497e-416e-a8f5-156ef424b053

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '%GASTOS PRIMA BRUTA' = ```
			
			VAR PeriodoSeleccionado = MAX(gd_grupo_contable2[fec_periodo_fecha_PT])
			VAR AnioActual = YEAR(PeriodoSeleccionado)
			VAR MesActual  = MONTH(PeriodoSeleccionado)
			
			-- Normalizo a primer día del mes por seguridad
			VAR MesActual_Inicio = DATE(AnioActual, MesActual, 1)
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE(MesActual_Inicio, -12)
			VAR AnioAnterior    = YEAR(PeriodoAnterior)
			VAR MesAnterior     = MONTH(PeriodoAnterior)
			
			-- === FILTROS ACTUALES ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        YEAR ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = AnioActual
			            && MONTH ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    DATESBETWEEN(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        DATE(AnioActual, 1, 1),
			        EOMONTH(MesActual_Inicio, 0)
			    )
			
			VAR FiltroAnualizado =
			    DATESINPERIOD(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        MesActual_Inicio,   -- fin de la ventana (mes actual, incluido)
			        -12,
			        MONTH
			    )
			
			-- === FILTROS ANTERIORES (CORREGIDOS) ===
			
			-- 1) Mensualizado anterior: exactamente el mes 12m atrás
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( gd_grupo_contable2[fec_periodo_fecha_PT] ),
			        YEAR ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = AnioAnterior
			            && MONTH ( gd_grupo_contable2[fec_periodo_fecha_PT] ) = MesAnterior
			    )
			
			-- 2) Acumulado anterior (YTD hasta el mes anterior): 
			VAR FiltroPeriodoAnteriorAcumulado =
			    DATESBETWEEN(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        DATE(AnioAnterior, 1, 1),
			        EOMONTH(PeriodoAnterior, 0)
			    )
			
			-- 3) Anualizado anterior: últimos 12 meses terminando en PeriodoAnterior
			VAR FiltroPeriodoAnteriorAnualizado =
			    DATESINPERIOD(
			        gd_grupo_contable2[fec_periodo_fecha_PT],
			        PeriodoAnterior,    -- fin de la ventana (incluido)
			        -12,
			        MONTH
			    )
			
			
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			----------------------------------------------------------------------------------
			/* === Primas Brutas === */
			VAR SumColumna_PrimasBrutas =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAcumulado
			                    )
			            )
			    )
			------------------------------------
			VAR SumColumna_PrimasBrutas_Ppto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_PrimasBrutas_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Primas Brutas",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			--------------------------
			/* === Gastos Administrativos === */
			VAR SumColumna_GastosAdministrativos =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAcumulado
			                    )
			            )
			    )
			-------------
			VAR SumColumna_GastosAdministrativosPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_GastosAdministrativos_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Gastos Administrativos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			---------------
			/* === Coaseguros Cedidos === */
			VAR SumColumna_CoasegurosCedidos =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            )
			    )
			------------------------------------------------
			VAR SumColumna_CoasegurosCedidosPpto =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroAcumulado
			                    )
			            )
			    )
			---------------------------------------Y-1
			VAR SumColumna_CoasegurosCedidos_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_presupuesto] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_forecast] ),
			                        gd_grupo_contable2[des_cuenta] = "Coaseguros Cedidos",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT = (DIVIDE(-SumColumna_GastosAdministrativos,SumColumna_PrimasBrutas-SumColumna_CoasegurosCedidos,0)*100) 
			VAR REAL_Y_1 = (DIVIDE(-SumColumna_GastosAdministrativos_1,SumColumna_PrimasBrutas_1-SumColumna_CoasegurosCedidos_1,0)*100)  
			VAR Ppto = (DIVIDE(-SumColumna_GastosAdministrativosPpto,SumColumna_PrimasBrutas_Ppto-SumColumna_CoasegurosCedidosPpto,0)*100)  
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PG_KPI[TipoCalculo]),
			    "Real Act", REAL_ACT,
			    "Ppto",Ppto,
			    "Var",(REAL_ACT-Ppto),
			    "Real Y-1", REAL_Y_1,
			    "%YoY" ,((REAL_ACT-REAL_Y_1)/REAL_Y_1)*100
			)
			```
		displayFolder: MedidasPG
		lineageTag: 871a7d2c-576f-4311-a56c-d74c4548e74c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Desviaciones del P&G' = ```
			
			VAR KPISeleccionado = SELECTEDVALUE('SelectorDesviaciones_PG'[Concepto])
			RETURN
			SWITCH (
			    TRUE(),
			    KPISeleccionado = "PPTO",
			        0,
			    KPISeleccionado = "PRIMAS BRUTAS",
			        CALCULATE([Primas Brutas], SelectorCalculo_PG[TipoCalculo] = "Real Act"),
			    KPISeleccionado = "CESIÓN",
			        CALCULATE([Cesión de Reaseguros], SelectorCalculo_PG[TipoCalculo] = "Real Act"),
			    KPISeleccionado = "DEVENGO",
			        CALCULATE([Constitución RRC], SelectorCalculo_PG[TipoCalculo] = "Real Act"),
			    KPISeleccionado = "SINIESTROS",
			        CALCULATE([Costo de Siniestros], SelectorCalculo_PG[TipoCalculo] = "Real Act"),
			    KPISeleccionado = "COMISIONES",
			        CALCULATE([NETO COMISIONES], SelectorCalculo_PG[TipoCalculo] = "Real Act"),
			    KPISeleccionado = "OTROS",
			        CALCULATE([RESULTADO TÉCNICO], SelectorCalculo_PG[TipoCalculo] = "Real Act"),
			    KPISeleccionado = "FINANCIEROS",
			        CALCULATE([Ingresos Financieros], SelectorCalculo_PG[TipoCalculo] = "Real Act"),
			    KPISeleccionado = "GASTOS",
			        CALCULATE([Gastos Administrativos], SelectorCalculo_PG[TipoCalculo] = "Real Act"),
			    KPISeleccionado = "PROV",
			        CALCULATE([Provisiones y Otros Imp.], SelectorCalculo_PG[TipoCalculo] = "Real Act"),
			    KPISeleccionado = "PROYECTADO",
			        CALCULATE([UTILIDAD NETA], SelectorCalculo_PG[TipoCalculo] = "Real Act"),
			        
			        
			
			    
			
			    BLANK()
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 639c6281-e14e-4541-9128-579e1b21e3bd

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'VAR 21.03 actual' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- Periodo anterior = 24 meses atrás (mismo día del mes)
			VAR PeriodoAnterior2 = EDATE(MesActual_Inicio, -24)
			VAR AnioAnterior2    = YEAR(PeriodoAnterior2)
			VAR MesAnterior2     = MONTH(PeriodoAnterior2)
			
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			-- === FILTROS 2 AÑOS ANTERIORES (CORREGIDOS) ===
			
			-- 1) Mensualizado anterior: exactamente el mes 24m atrás (p.ej. 2023-03)
			VAR FiltroPeriodoAnteriorMensualizado2 =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( Calendario[MesNombreAño] ) = AnioAnterior2
			            && MONTH ( Calendario[MesNombreAño] ) = MesAnterior2
			    )
			
			-- 2) Acumulado anterior (YTD hasta el mes anterior): 01/01 de 2 año anterior a fin de ese mes
			VAR FiltroPeriodoAnteriorAcumulado2 =   
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior2, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior2, 0 )
			    )
			
			-- 3) Anualizado anterior: últimos 24 meses terminando en PeriodoAnterior
			VAR FiltroPeriodoAnteriorAnualizado2 =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior2, -24 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior2, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			
			----------------------------------------------------------------------------------
			VAR SumColumna_ReservasParaObligacDeSiniestrosPendientes =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAcumulado
			                    )
			            )
			    )
			VAR SumColumna_ReservasParaObligacDeSiniestrosPendientesY_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			VAR SumColumna_ReservasParaObligacDeSiniestrosPendientesY_2 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado2
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado2
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado2
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado2
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado2
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado2
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado2
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado2
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado2
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT =
			     SumColumna_ReservasParaObligacDeSiniestrosPendientes-SumColumna_ReservasParaObligacDeSiniestrosPendientesY_1
			VAR REAL_Y_1 = SumColumna_ReservasParaObligacDeSiniestrosPendientesY_1 - SumColumna_ReservasParaObligacDeSiniestrosPendientesY_2
			
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		displayFolder: MedidasPT
		lineageTag: 30c1bab8-d890-4417-af49-2e7ab083ad25

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOTAL actual SINIESTRO' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- Periodo anterior = 24 meses atrás (mismo día del mes)
			VAR PeriodoAnterior2 = EDATE(MesActual_Inicio, -24)
			VAR AnioAnterior2    = YEAR(PeriodoAnterior2)
			VAR MesAnterior2     = MONTH(PeriodoAnterior2)
			
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			-- === FILTROS 2 AÑOS ANTERIORES (CORREGIDOS) ===
			
			-- 1) Mensualizado anterior: exactamente el mes 24m atrás (p.ej. 2023-03)
			VAR FiltroPeriodoAnteriorMensualizado2 =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( Calendario[MesNombreAño] ) = AnioAnterior2
			            && MONTH ( Calendario[MesNombreAño] ) = MesAnterior2
			    )
			
			-- 2) Acumulado anterior (YTD hasta el mes anterior): 01/01 de 2 año anterior a fin de ese mes
			VAR FiltroPeriodoAnteriorAcumulado2 =   
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior2, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior2, 0 )
			    )
			
			-- 3) Anualizado anterior: últimos 24 meses terminando en PeriodoAnterior
			VAR FiltroPeriodoAnteriorAnualizado2 =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior2, -24 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior2, 0 )
			    )
			
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			
			----------------------------------------------------------------------------------
			VAR SumColumna_ReservasParaObligacDeSiniestrosPendientes =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroAcumulado
			                    )
			            )
			    )
			VAR SumColumna_ReservasParaObligacDeSiniestrosPendientesY_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "Reservas Para Obligac.De Siniestros Pendientes",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			----------------------------------------------------------------------------------
			VAR SumColumna_Salvamentos_Seguros =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroAcumulado
			                    )
			            )
			    )
			VAR SumColumna_Salvamentos_SegurosY_1 =
			    SWITCH (
			        TipoData,
			        "Real",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Presupuesto",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            ),
			        "Forecast",
			            SWITCH (
			                TipoValor,
			                "Anualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_anualizado] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAnualizado
			                    ),
			                "Mensualizado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorMensualizado
			                    ),
			                "Acumulado",
			                    CALCULATE (
			                        SUM ( gd_grupo_contable2[val_saldo_balance] ),
			                        gd_grupo_contable2[des_cuenta] = "SumColumna_Salvamentos_Seguros",
			                        FiltroPeriodoAnteriorAcumulado
			                    )
			            )
			    )
			/* === Fórmula base === */
			VAR REAL_ACT =
			    SumColumna_Salvamentos_Seguros - (CALCULATE([VAR 21.03 actual],SelectorCalculo_PT[TipoCalculo] = "REAL ACT") + SumColumna_ReservasParaObligacDeSiniestrosPendientes)
			VAR REAL_Y_1 = SumColumna_Salvamentos_SegurosY_1 - (CALCULATE([VAR 21.03 actual],SelectorCalculo_PT[TipoCalculo] = "REAL Y-1") + SumColumna_ReservasParaObligacDeSiniestrosPendientesY_1)
			
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			
			```
		displayFolder: MedidasPT
		lineageTag: cc336a14-8012-493d-8c2a-01844c07f6fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YEAR(-1) AJUSTADO' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- Periodo anterior = 24 meses atrás (mismo día del mes)
			VAR PeriodoAnterior2 = EDATE(MesActual_Inicio, -24)
			VAR AnioAnterior2    = YEAR(PeriodoAnterior2)
			VAR MesAnterior2     = MONTH(PeriodoAnterior2)
			
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			-- === FILTROS 2 AÑOS ANTERIORES (CORREGIDOS) ===
			
			-- 1) Mensualizado anterior: exactamente el mes 24m atrás (p.ej. 2023-03)
			VAR FiltroPeriodoAnteriorMensualizado2 =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( Calendario[MesNombreAño] ) = AnioAnterior2
			            && MONTH ( Calendario[MesNombreAño] ) = MesAnterior2
			    )
			
			-- 2) Acumulado anterior (YTD hasta el mes anterior): 01/01 de 2 año anterior a fin de ese mes
			VAR FiltroPeriodoAnteriorAcumulado2 =   
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior2, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior2, 0 )
			    )
			
			-- 3) Anualizado anterior: últimos 24 meses terminando en PeriodoAnterior
			VAR FiltroPeriodoAnteriorAnualizado2 =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior2, -24 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior2, 0 )
			    )
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			
			VAR REAL_ACT =
			    CALCULATE([TOTAL actual SINIESTRO],SelectorCalculo_PT[TipoCalculo] = "REAL Y-1") *0.35
			VAR REAL_Y_1 = CALCULATE([TOTAL actual SINIESTRO],SelectorCalculo_PT[TipoCalculo] = "REAL Y-1",FiltroPeriodoAnteriorMensualizado2)*0.35
			
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = COALESCE(ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2), 0 )
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", COALESCE (DIVIDE( REAL_ACT,1000,0), 0 ),
			    "REAL Y-1", COALESCE ( DIVIDE ( REAL_Y_1, 1000, 0 ), 0 ),
			    "YoY", COALESCE (DIVIDE(YoY,1000,0), 0 ),
			    "%YoY", CapitalBase3
			)
			```
		formatString: 0
		displayFolder: MedidasPT
		lineageTag: 3e8e53f1-f01b-4487-b4e6-5f6fac1aa5bb

	measure 'YEAR(-2) AJUSTADO' = ```
			
			VAR PeriodoSeleccionado =
			    MAXX(
			        VALUES( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] )
			    )
			VAR AnioActual = YEAR( PeriodoSeleccionado )
			VAR MesActual  = MONTH( PeriodoSeleccionado )
			
			-- Normalizo a primer día del mes
			VAR MesActual_Inicio = DATE( AnioActual, MesActual, 1 )
			
			-- Periodo anterior = 12 meses atrás (mismo día del mes)
			VAR PeriodoAnterior = EDATE( MesActual_Inicio, -12 )
			VAR AnioAnterior    = YEAR( PeriodoAnterior )
			VAR MesAnterior     = MONTH( PeriodoAnterior )
			
			-- Periodo anterior = 24 meses atrás (mismo día del mes)
			VAR PeriodoAnterior2 = EDATE(MesActual_Inicio, -24)
			VAR AnioAnterior2    = YEAR(PeriodoAnterior2)
			VAR MesAnterior2     = MONTH(PeriodoAnterior2)
			
			-- Periodo anterior = 36 meses atrás (mismo día del mes)
			VAR PeriodoAnterior3 = EDATE(MesActual_Inicio, -36)
			VAR AnioAnterior3    = YEAR(PeriodoAnterior3)
			VAR MesAnterior3     = MONTH(PeriodoAnterior3)
			
			-- === FILTROS ACTUALES (solo FILTER + DATEVALUE) ===
			VAR FiltroPeriodoMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioActual
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesActual
			    )
			
			VAR FiltroAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioActual, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			VAR FiltroAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( MesActual_Inicio, -12 )   -- últimos 12 meses
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( MesActual_Inicio, 0 )
			    )
			
			-- === FILTROS ANTERIORES ===
			VAR FiltroPeriodoAnteriorMensualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( DATEVALUE( Calendario[MesNombreAño] ) ) = AnioAnterior
			            && MONTH ( DATEVALUE( Calendario[MesNombreAño] ) ) = MesAnterior
			    )
			
			VAR FiltroPeriodoAnteriorAcumulado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			
			VAR FiltroPeriodoAnteriorAnualizado =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior, -12 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior, 0 )
			    )
			-- === FILTROS 2 AÑOS ANTERIORES (CORREGIDOS) ===
			
			-- 1) Mensualizado anterior: exactamente el mes 24m atrás (p.ej. 2023-03)
			VAR FiltroPeriodoAnteriorMensualizado2 =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        YEAR ( Calendario[MesNombreAño] ) = AnioAnterior2
			            && MONTH ( Calendario[MesNombreAño] ) = MesAnterior2
			    )
			
			-- 2) Acumulado anterior (YTD hasta el mes anterior): 01/01 de 2 año anterior a fin de ese mes
			VAR FiltroPeriodoAnteriorAcumulado2 =   
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior2, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior2, 0 )
			    )
			
			-- 3) Anualizado anterior: últimos 24 meses terminando en PeriodoAnterior
			VAR FiltroPeriodoAnteriorAnualizado2 =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior2, -24 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior2, 0 )
			    )
			-- === FILTROS 3 AÑOS ANTERIORES (CORREGIDOS) ===
			
			-- 1) Mensualizado anterior: exactamente el mes 36m atrás (p.ej. 2023-03)
			VAR FiltroPeriodoAnteriorMensualizado3 =
			    FILTER (
			        ALL ( Calendario[MesNombreAño]  ),
			        YEAR ( Calendario[MesNombreAño]  ) = AnioAnterior3
			            && MONTH ( Calendario[MesNombreAño]  ) = MesAnterior3
			    )
			
			-- 2) Acumulado anterior (YTD hasta el mes anterior): 01/01 de 2 año anterior a fin de ese mes
			VAR FiltroPeriodoAnteriorAcumulado3 =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >= DATE( AnioAnterior3, 1, 1 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior3, 0 )
			    )
			-- 3) Anualizado anterior: últimos 24 meses terminando en PeriodoAnterior
			VAR FiltroPeriodoAnteriorAnualizado3 =
			    FILTER (
			        ALL ( Calendario[MesNombreAño] ),
			        DATEVALUE( Calendario[MesNombreAño] ) >  EDATE( PeriodoAnterior3, -36 )
			            && DATEVALUE( Calendario[MesNombreAño] ) <= EOMONTH( PeriodoAnterior3, 0 )
			    )
			VAR TipoValor = SELECTEDVALUE(SelectorValor[TipoValor])
			VAR TipoData  = SELECTEDVALUE(SelectorData[TipoData])
			
			VAR REAL_ACT =
			    CALCULATE([TOTAL actual SINIESTRO],SelectorCalculo_PT[TipoCalculo] = "REAL Y-1",FiltroPeriodoAnteriorMensualizado2) *0.35
			VAR REAL_Y_1 = CALCULATE([TOTAL actual SINIESTRO],SelectorCalculo_PT[TipoCalculo] = "REAL Y-1",FiltroPeriodoAnteriorMensualizado3)*0.35
			
			VAR YoY = REAL_ACT - REAL_Y_1
			VAR CapitalBase3 = ROUND(DIVIDE(YoY,REAL_Y_1,0)*100,2)
			RETURN
			SWITCH (
			    SELECTEDVALUE(SelectorCalculo_PT[TipoCalculo]),
			    "REAL ACT", DIVIDE(REAL_ACT,1000,0),
			    "REAL Y-1", COALESCE(DIVIDE(REAL_Y_1,1000,0), 0 ),
			    "YoY", DIVIDE(YoY,1000,0),
			    "%YoY", CapitalBase3
			)
			```
		displayFolder: MedidasPT
		lineageTag: d7f7e7e8-6fb8-4f94-af2f-74c33ee68a10

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cap. Ade. Por Carga Media De Siniestralidad' = ```
			
			([TOTAL actual SINIESTRO]+[YEAR(-1) AJUSTADO]+[YEAR(-2) AJUSTADO])/3
			
			```
		formatString: #,0
		displayFolder: MedidasPT
		lineageTag: d8dd6b56-4874-451f-90fc-7ef8f3d9d216

		annotation PBI_FormatHint = {"isDecimal":true}

	measure FiltroAñoDinamico_PT = ```
			
			VAR SelectedMinDate = CALCULATE( MIN ( gd_grupo_contable2[fec_periodo_fecha_PT] ), ALLSELECTED ( gd_grupo_contable2 ) )
			VAR SelectedMaxDate = CALCULATE( MAX ( gd_grupo_contable2[fec_periodo_fecha_PT] ), ALLSELECTED ( gd_grupo_contable2 ) )
			VAR HaySeleccion    = NOT ISBLANK ( SelectedMinDate ) && NOT ISBLANK ( SelectedMaxDate )
			
			-- Si hay selección de período: toma el año de la selección (basta con el Máx).
			-- Si no hay selección: toma el año actual.
			VAR TargetYear =
			    IF ( HaySeleccion, YEAR ( SelectedMaxDate ), YEAR ( TODAY() ) )
			
			-- Año del contexto actual del visual (barra/mes) calculado desde la fecha real
			VAR YearEnContexto = YEAR ( MAX ( gd_grupo_contable2[fec_periodo_fecha_PT] ) )
			
			RETURN
			    IF ( YearEnContexto = TargetYear, 1, 0 )
			
			
			```
		formatString: 0
		displayFolder: MedidasPT
		lineageTag: fd13c5bc-6290-4bdc-b86e-1e7cec7fb7ab

	measure CalculosReal-Y1_Tabla_PG = ```
			
			VAR dar  = SELECTEDVALUE ( SelectorCuentas_PG[Descripción] )
			VAR Tipo = "Real Y-1"
			RETURN
			SWITCH (
			    TRUE (),
			
			    dar = "Primas Brutas",
			        CALCULATE ( [Primas Brutas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Coaseguros Cedidos",
			        CALCULATE ( [Coaseguros Cedidos], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Cesión de Reaseguros",
			        CALCULATE ( [Cesión de Reaseguros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) PRIMAS NETAS",
			        CALCULATE ( [PRIMAS NETAS], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Excesos de Pérdida",
			        CALCULATE ( [Excesos de Pérdida], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Constitución RRC",
			        CALCULATE ( [Constitución RRC], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) PRIMAS DEVENGADAS",
			        CALCULATE ( [PRIMAS DEVENGADAS], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Costo de Siniestros",
			        CALCULATE ( [Costo de Siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Siniestros pagados",
			        CALCULATE ( [Siniestros pagados], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "Recuperaciones siniestros",
			        CALCULATE ( [Recuperaciones siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Ajuste Reserva Siniestros",
			        CALCULATE ( [Ajuste Reserva Siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) IBNR",
			        CALCULATE ( [IBNR], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) NETO COMISIONES",
			        CALCULATE ( [NETO COMISIONES], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Comisiones Pagadas",
			        CALCULATE ( [Comisiones Pagadas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "Comisiones Ganadas",
			        CALCULATE ( [Comisiones Ganadas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) RESULTADO TECNICO",
			        CALCULATE ( [RESULTADO TÉCNICO], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "Ingresos Financieros",
			        CALCULATE ( [Ingresos Financieros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Gastos Administrativos",
			        CALCULATE ( [Gastos Administrativos], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Provisiones y Otros Imp.",
			        CALCULATE ( [Provisiones y Otros Imp.], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) EBIT",
			        CALCULATE ( [EBIT], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Participación Trabajadores",
			        CALCULATE ( [Participación Trabajadores], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Impuesto a la Renta",
			        CALCULATE ( [Impuesto a la Renta], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) UTILIDAD NETA",
			        CALCULATE ( [UTILIDAD NETA], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    BLANK ()
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 1c376f6e-7620-47f0-a7cd-b8467307dea1

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CalculosPpto_Tabla_PG = ```
			
			VAR dar  = SELECTEDVALUE ( SelectorCuentas_PG[Descripción] )
			VAR Tipo = "Ppto"
			RETURN
			SWITCH (
			    TRUE (),
			
			    dar = "Primas Brutas",
			        CALCULATE ( [Primas Brutas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Coaseguros Cedidos",
			        CALCULATE ( [Coaseguros Cedidos], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Cesión de Reaseguros",
			        CALCULATE ( [Cesión de Reaseguros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) PRIMAS NETAS",
			        CALCULATE ( [PRIMAS NETAS], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Excesos de Pérdida",
			        CALCULATE ( [Excesos de Pérdida], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(+) Constitución RRC",
			        CALCULATE ( [Constitución RRC], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) PRIMAS DEVENGADAS",
			        CALCULATE ( [PRIMAS DEVENGADAS], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Costo de Siniestros",
			        CALCULATE ( [Costo de Siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Siniestros pagados",
			        CALCULATE ( [Siniestros pagados], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(+) Recuperaciones siniestros",
			        CALCULATE ( [Recuperaciones siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(+) Ajuste Reserva Siniestros",
			        CALCULATE ( [Ajuste Reserva Siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(+) IBNR",
			        CALCULATE ( [IBNR], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) NETO COMISIONES",
			        CALCULATE ( [NETO COMISIONES], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Comisiones Pagadas",
			        CALCULATE ( [Comisiones Pagadas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "Comisiones Ganadas",
			        CALCULATE ( [Comisiones Ganadas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) RESULTADO TECNICO",
			        CALCULATE ( [RESULTADO TÉCNICO], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(+) Ingresos Financieros",
			        CALCULATE ( [Ingresos Financieros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Gastos Administrativos",
			        CALCULATE ( [Gastos Administrativos], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Provisiones y Otros Imp.",
			        CALCULATE ( [Provisiones y Otros Imp.], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) EBIT",
			        CALCULATE ( [EBIT], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Participación Trabajadores",
			        CALCULATE ( [Participación Trabajadores], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Impuesto a la Renta",
			        CALCULATE ( [Impuesto a la Renta], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) UTILIDAD NETA",
			        CALCULATE ( [UTILIDAD NETA], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    BLANK ()
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: 658c5b88-b337-484c-aad4-8af028ce229a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CalculosCumpli_Tabla_PG = ```
			
			VAR dar  = SELECTEDVALUE ( SelectorCuentas_PG[Descripción] )
			VAR Tipo = "% Cumpl."
			RETURN
			SWITCH (
			    TRUE (),
			
			    dar = "Primas Brutas",
			        CALCULATE ( [Primas Brutas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Coaseguros Cedidos",
			        CALCULATE ( [Coaseguros Cedidos], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Cesión de Reaseguros",
			        CALCULATE ( [Cesión de Reaseguros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) PRIMAS NETAS",
			        CALCULATE ( [PRIMAS NETAS], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Excesos de Pérdida",
			        CALCULATE ( [Excesos de Pérdida], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Constitución RRC",
			        CALCULATE ( [Constitución RRC], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) PRIMAS DEVENGADAS",
			        CALCULATE ( [PRIMAS DEVENGADAS], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Costo de Siniestros",
			        CALCULATE ( [Costo de Siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Siniestros pagados",
			        CALCULATE ( [Siniestros pagados], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "Recuperaciones siniestros",
			        CALCULATE ( [Recuperaciones siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Ajuste Reserva Siniestros",
			        CALCULATE ( [Ajuste Reserva Siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) IBNR",
			        CALCULATE ( [IBNR], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) NETO COMISIONES",
			        CALCULATE ( [NETO COMISIONES], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Comisiones Pagadas",
			        CALCULATE ( [Comisiones Pagadas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "Comisiones Ganadas",
			        CALCULATE ( [Comisiones Ganadas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) RESULTADO TECNICO",
			        CALCULATE ( [RESULTADO TÉCNICO], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "Ingresos Financieros",
			        CALCULATE ( [Ingresos Financieros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Gastos Administrativos",
			        CALCULATE ( [Gastos Administrativos], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Provisiones y Otros Imp.",
			        CALCULATE ( [Provisiones y Otros Imp.], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) EBIT",
			        CALCULATE ( [EBIT], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Participación Trabajadores",
			        CALCULATE ( [Participación Trabajadores], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Impuesto a la Renta",
			        CALCULATE ( [Impuesto a la Renta], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) UTILIDAD NETA",
			        CALCULATE ( [UTILIDAD NETA], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    BLANK ()
			)
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: MedidasPG
		lineageTag: 9ebee410-8be3-4d12-9586-41da6ebe3941

	measure CalculosRealActual_Tabla_PG = ```
			
			VAR dar  = SELECTEDVALUE ( SelectorCuentas_PG[Descripción] )
			VAR Tipo = "Real Act"
			RETURN
			SWITCH (
			    TRUE (),
			
			    dar = "Primas Brutas",
			        CALCULATE ( [Primas Brutas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Coaseguros Cedidos",
			        CALCULATE ( [Coaseguros Cedidos], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Cesión de Reaseguros",
			        CALCULATE ( [Cesión de Reaseguros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) PRIMAS NETAS",
			        CALCULATE ( [PRIMAS NETAS], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Excesos de Pérdida",
			        CALCULATE ( [Excesos de Pérdida], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Constitución RRC",
			        CALCULATE ( [Constitución RRC], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) PRIMAS DEVENGADAS",
			        CALCULATE ( [PRIMAS DEVENGADAS], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Costo de Siniestros",
			        CALCULATE ( [Costo de Siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Siniestros pagados",
			        CALCULATE ( [Siniestros pagados], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "Recuperaciones siniestros",
			        CALCULATE ( [Recuperaciones siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Ajuste Reserva Siniestros",
			        CALCULATE ( [Ajuste Reserva Siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) IBNR",
			        CALCULATE ( [IBNR], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) NETO COMISIONES",
			        CALCULATE ( [NETO COMISIONES], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Comisiones Pagadas",
			        CALCULATE ( [Comisiones Pagadas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "Comisiones Ganadas",
			        CALCULATE ( [Comisiones Ganadas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) RESULTADO TECNICO",
			        CALCULATE ( [RESULTADO TÉCNICO], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "Ingresos Financieros",
			        CALCULATE ( [Ingresos Financieros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Gastos Administrativos",
			        CALCULATE ( [Gastos Administrativos], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Provisiones y Otros Imp.",
			        CALCULATE ( [Provisiones y Otros Imp.], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) EBIT",
			        CALCULATE ( [EBIT], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Participación Trabajadores",
			        CALCULATE ( [Participación Trabajadores], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Impuesto a la Renta",
			        CALCULATE ( [Impuesto a la Renta], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) UTILIDAD NETA",
			        CALCULATE ( [UTILIDAD NETA], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    BLANK ()
			)
			
			```
		formatString: #,0
		displayFolder: MedidasPG
		lineageTag: cb2bebd1-7b1e-457a-90d6-274ddb8a8bbc

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CalculosYoY_Tabla_PG = ```
			
			VAR dar  = SELECTEDVALUE ( SelectorCuentas_PG[Descripción] )
			VAR Tipo = "%YoY"
			RETURN
			SWITCH (
			    TRUE (),
			
			    dar = "Primas Brutas",
			        CALCULATE ( [Primas Brutas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Coaseguros Cedidos",
			        CALCULATE ( [Coaseguros Cedidos], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Cesión de Reaseguros",
			        CALCULATE ( [Cesión de Reaseguros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) PRIMAS NETAS",
			        CALCULATE ( [PRIMAS NETAS], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Excesos de Pérdida",
			        CALCULATE ( [Excesos de Pérdida], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Constitución RRC",
			        CALCULATE ( [Constitución RRC], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) PRIMAS DEVENGADAS",
			        CALCULATE ( [PRIMAS DEVENGADAS], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Costo de Siniestros",
			        CALCULATE ( [Costo de Siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Siniestros pagados",
			        CALCULATE ( [Siniestros pagados], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "Recuperaciones siniestros",
			        CALCULATE ( [Recuperaciones siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Ajuste Reserva Siniestros",
			        CALCULATE ( [Ajuste Reserva Siniestros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) IBNR",
			        CALCULATE ( [IBNR], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) NETO COMISIONES",
			        CALCULATE ( [NETO COMISIONES], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Comisiones Pagadas",
			        CALCULATE ( [Comisiones Pagadas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "Comisiones Ganadas",
			        CALCULATE ( [Comisiones Ganadas], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) RESULTADO TECNICO",
			        CALCULATE ( [RESULTADO TÉCNICO], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "Ingresos Financieros",
			        CALCULATE ( [Ingresos Financieros], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Gastos Administrativos",
			        CALCULATE ( [Gastos Administrativos], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Provisiones y Otros Imp.",
			        CALCULATE ( [Provisiones y Otros Imp.], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) EBIT",
			        CALCULATE ( [EBIT], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Participación Trabajadores",
			        CALCULATE ( [Participación Trabajadores], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(-) Impuesto a la Renta",
			        CALCULATE ( [Impuesto a la Renta], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    dar = "(=) UTILIDAD NETA",
			        CALCULATE ( [UTILIDAD NETA], SelectorCalculo_PG[TipoCalculo] = Tipo ),
			
			    BLANK ()
			)
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: MedidasPG
		lineageTag: 02429ab6-eb5c-44e3-b612-8f5b81781ab8

	measure CalculosPpto_Tabla_PG2 = ```
			
			VAR dar  = SELECTEDVALUE ( SelectorCuentas_PG[Descripción] )
			VAR Tipo = "Ppto"
			RETURN
			SWITCH (
			    TRUE (),
			
			    dar = "Primas Brutas",
			       0,
			
			    dar = "(-) Coaseguros Cedidos",
			      0,
			
			    dar = "(-) Cesión de Reaseguros",
			        0,
			
			    dar = "(=) PRIMAS NETAS",
			        0,
			
			    dar = "(-) Excesos de Pérdida",
			        0,
			
			    dar = "(-) Constitución RRC",
			       0,
			
			    dar = "(=) PRIMAS DEVENGADAS",
			        0,
			
			    dar = "(-) Costo de Siniestros",
			        0,
			
			    dar = "(-) Siniestros pagados",
			        0,
			
			    dar = "Recuperaciones siniestros",
			        0,
			
			    dar = "(-) Ajuste Reserva Siniestros",
			        0,
			
			    dar = "(-) IBNR",
			        0,
			
			    dar = "(-) NETO COMISIONES",
			       0,
			
			    dar = "(-) Comisiones Pagadas",
			       0,
			
			    dar = "Comisiones Ganadas",
			        0,
			
			    dar = "(=) RESULTADO TECNICO",
			        0,
			
			    dar = "Ingresos Financieros",
			       0,
			
			    dar = "(-) Gastos Administrativos",
			       0,
			
			    dar = "(-) Provisiones y Otros Imp.",
			       0,
			
			    dar = "(=) EBIT",
			        0,
			
			    dar = "(-) Participación Trabajadores",
			        0,
			
			    dar = "(-) Impuesto a la Renta",
			        0,
			
			    dar = "(=) UTILIDAD NETA",
			        0,
			    BLANK ()
			)
			
			```
		formatString: 0
		displayFolder: MedidasPG
		lineageTag: 2330ba33-5410-43ec-a250-7c178ed568fd

	measure 'Color Fila (BG)' = ```
			
			VAR cuenta =
			    SELECTEDVALUE ( 'SelectorCuentas_PG'[Descripción] )
			RETURN
			SWITCH (
			    TRUE(),
			    NOT ISINSCOPE ('SelectorCuentas_PG'[Descripción]), BLANK(),      
			    CONTAINSSTRING ( cuenta, "PRIMAS NETAS" ), "#FFF2CC",               
			    BLANK()                                                              
			)
			```
		displayFolder: MedidasPG
		lineageTag: 5ff7415a-1522-420b-9627-6a446584d1e2

	measure CalculosRealActual_Tabla_PT = ```
			
			VAR dar  = SELECTEDVALUE ( SelectorCuentas_PT[Descripción] )
			VAR Tipo = "REAL ACT"
			RETURN
			SWITCH (
			    TRUE (),
			
			    -- REQUERIMIENTO DE CAPITAL ADECUADO
			    dar = "Capital Adecuado por Primas",
			        CALCULATE ( [Capital Adecuado por Primas], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Cap. Ade. Por Carga Media De Siniestralidad",
			        CALCULATE ( [Cap. Ade. Por Carga Media De Siniestralidad], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Cap. Ade. Factor De Corrección Por Concentración",
			        CALCULATE ( [Cap. Ade. Factor De Corrección Por Concentración], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Cap. Ade. Riesgo De Crédito Por Reaseguro",
			        CALCULATE ( [Cap. Ade. Riesgo De Crédito Por Reaseguro], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "REQUERIMIENTO DE CAPITAL ADECUADO", CALCULATE ( [REQUERIMIENTO DE CAPITAL ADECUADO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    -- PATRIMONIO TÉCNICO PRIMARIO
			    dar = "Capital Pagado",
			        CALCULATE ( [Capital Pagado], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Capital Operativo",
			        CALCULATE ( [Capital Operativo], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Reserva Legal",
			        CALCULATE ( [Reserva Legal], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Aportes De Accionistas",
			        CALCULATE ( [Aportes De Accionistas], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultados Del Ejercicio",
			        CALCULATE ( [Resultados Del Ejercicio], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Utilidad retenida (capacitaciones)",
			        CALCULATE ( [Utilidad retenida (capacitaciones)], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Dividendos Acción",
			        CALCULATE ( [Dividendos Acción], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Reserva Desviación De Siniestralidad Y Catastrófica",
			        CALCULATE ( [Reserva Desviación De Siniestralidad Y Catastrófica], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "PATRIMONIO TÉCNICO PRIMARIO", CALCULATE ( [PATRIMONIO TÉCNICO PRIMARIO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    -- PATRIMONIO TÉCNICO SECUNDARIO
			    dar = "Utilidad Ret. Futuras Capitalizaciones",
			        CALCULATE ( [Utilidad Ret. Futuras Capitalizaciones], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Otras (Pts)",
			        CALCULATE ( [Otras (Pts)], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "45% Reserva Legal Pts",
			        CALCULATE ( [45% Reserva Legal Pts], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultados Acumulados Utilidades",
			        CALCULATE ( [Resultados Acumulados Utilidades], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultado Del Ejercicio Utilidades",
			        CALCULATE ( [Resultado Del Ejercicio Utilidades], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultados Del Ejercicio Pérdidas",
			        CALCULATE ( [Resultados Del Ejercicio Pérdidas], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultado Del Ejercicio (Pts)",
			        CALCULATE ( [Resultado Del Ejercicio (Pts)], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "PATRIMONIO TÉCNICO SECUNDARIO",CALCULATE ( [PATRIMONIO TÉCNICO SECUNDARIO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    -- TOTAL
			    dar = "TOTAL PATRIMONIO TÉCNICO",
			        CALCULATE ( [TOTAL PATRIMONIO TÉCNICO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    BLANK ()
			)
			
			```
		displayFolder: MedidasPT
		lineageTag: d4f1582a-c825-408e-936d-fe9f99d791d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CalculosREAL_Y-1_Tabla_PT =
			
			VAR dar  = SELECTEDVALUE ( SelectorCuentas_PT[Descripción] )
			VAR Tipo = "REAL Y-1"
			RETURN
			SWITCH (
			    TRUE (),
			
			    -- REQUERIMIENTO DE CAPITAL ADECUADO
			    dar = "Capital Adecuado por Primas",
			        CALCULATE ( [Capital Adecuado por Primas], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Cap. Ade. Por Carga Media De Siniestralidad",
			        CALCULATE ( [Cap. Ade. Por Carga Media De Siniestralidad], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Cap. Ade. Factor De Corrección Por Concentración",
			        CALCULATE ( [Cap. Ade. Factor De Corrección Por Concentración], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Cap. Ade. Riesgo De Crédito Por Reaseguro",
			        CALCULATE ( [Cap. Ade. Riesgo De Crédito Por Reaseguro], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "REQUERIMIENTO DE CAPITAL ADECUADO", CALCULATE ( [REQUERIMIENTO DE CAPITAL ADECUADO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    -- PATRIMONIO TÉCNICO PRIMARIO
			    dar = "Capital Pagado",
			        CALCULATE ( [Capital Pagado], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Capital Operativo",
			        CALCULATE ( [Capital Operativo], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Reserva Legal",
			        CALCULATE ( [Reserva Legal], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Aportes De Accionistas",
			        CALCULATE ( [Aportes De Accionistas], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultados Del Ejercicio",
			        CALCULATE ( [Resultados Del Ejercicio], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Utilidad retenida (capacitaciones)",
			        CALCULATE ( [Utilidad retenida (capacitaciones)], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Dividendos Acción",
			        CALCULATE ( [Dividendos Acción], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Reserva Desviación De Siniestralidad Y Catastrófica",
			        CALCULATE ( [Reserva Desviación De Siniestralidad Y Catastrófica], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "PATRIMONIO TÉCNICO PRIMARIO", CALCULATE ( [PATRIMONIO TÉCNICO PRIMARIO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    -- PATRIMONIO TÉCNICO SECUNDARIO
			    dar = "Utilidad Ret. Futuras Capitalizaciones",
			        CALCULATE ( [Utilidad Ret. Futuras Capitalizaciones], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Otras (Pts)",
			        CALCULATE ( [Otras (Pts)], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "45% Reserva Legal Pts",
			        CALCULATE ( [45% Reserva Legal Pts], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultados Acumulados Utilidades",
			        CALCULATE ( [Resultados Acumulados Utilidades], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultado Del Ejercicio Utilidades",
			        CALCULATE ( [Resultado Del Ejercicio Utilidades], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultados Del Ejercicio Pérdidas",
			        CALCULATE ( [Resultados Del Ejercicio Pérdidas], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultado Del Ejercicio (Pts)",
			        CALCULATE ( [Resultado Del Ejercicio (Pts)], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "PATRIMONIO TÉCNICO SECUNDARIO",CALCULATE ( [PATRIMONIO TÉCNICO SECUNDARIO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    -- TOTAL
			    dar = "TOTAL PATRIMONIO TÉCNICO",
			        CALCULATE ( [TOTAL PATRIMONIO TÉCNICO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    BLANK ()
			)
		displayFolder: MedidasPT
		lineageTag: 9a1f59a9-4c24-4acb-9e77-07381d9e59c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CalculosYoY_Tabla_PT =
			
			VAR dar  = SELECTEDVALUE ( SelectorCuentas_PT[Descripción] )
			VAR Tipo = "YoY"
			RETURN
			SWITCH (
			    TRUE (),
			
			    -- REQUERIMIENTO DE CAPITAL ADECUADO
			    dar = "Capital Adecuado por Primas",
			        CALCULATE ( [Capital Adecuado por Primas], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Cap. Ade. Por Carga Media De Siniestralidad",
			        CALCULATE ( [Cap. Ade. Por Carga Media De Siniestralidad], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Cap. Ade. Factor De Corrección Por Concentración",
			        CALCULATE ( [Cap. Ade. Factor De Corrección Por Concentración], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Cap. Ade. Riesgo De Crédito Por Reaseguro",
			        CALCULATE ( [Cap. Ade. Riesgo De Crédito Por Reaseguro], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "REQUERIMIENTO DE CAPITAL ADECUADO", CALCULATE ( [REQUERIMIENTO DE CAPITAL ADECUADO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    -- PATRIMONIO TÉCNICO PRIMARIO
			    dar = "Capital Pagado",
			        CALCULATE ( [Capital Pagado], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Capital Operativo",
			        CALCULATE ( [Capital Operativo], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Reserva Legal",
			        CALCULATE ( [Reserva Legal], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Aportes De Accionistas",
			        CALCULATE ( [Aportes De Accionistas], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultados Del Ejercicio",
			        CALCULATE ( [Resultados Del Ejercicio], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Utilidad retenida (capacitaciones)",
			        CALCULATE ( [Utilidad retenida (capacitaciones)], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Dividendos Acción",
			        CALCULATE ( [Dividendos Acción], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Reserva Desviación De Siniestralidad Y Catastrófica",
			        CALCULATE ( [Reserva Desviación De Siniestralidad Y Catastrófica], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "PATRIMONIO TÉCNICO PRIMARIO", CALCULATE ( [PATRIMONIO TÉCNICO PRIMARIO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    -- PATRIMONIO TÉCNICO SECUNDARIO
			    dar = "Utilidad Ret. Futuras Capitalizaciones",
			        CALCULATE ( [Utilidad Ret. Futuras Capitalizaciones], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Otras (Pts)",
			        CALCULATE ( [Otras (Pts)], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "45% Reserva Legal Pts",
			        CALCULATE ( [45% Reserva Legal Pts], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultados Acumulados Utilidades",
			        CALCULATE ( [Resultados Acumulados Utilidades], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultado Del Ejercicio Utilidades",
			        CALCULATE ( [Resultado Del Ejercicio Utilidades], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultados Del Ejercicio Pérdidas",
			        CALCULATE ( [Resultados Del Ejercicio Pérdidas], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultado Del Ejercicio (Pts)",
			        CALCULATE ( [Resultado Del Ejercicio (Pts)], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "PATRIMONIO TÉCNICO SECUNDARIO",CALCULATE ( [PATRIMONIO TÉCNICO SECUNDARIO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    -- TOTAL
			    dar = "TOTAL PATRIMONIO TÉCNICO",
			        CALCULATE ( [TOTAL PATRIMONIO TÉCNICO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    BLANK ()
			)
		displayFolder: MedidasPT
		lineageTag: 8a3dcef6-f27f-4e11-b2a5-31d72ed08f75

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Calculos%YoY_Tabla_PT = ```
			
			VAR dar  = SELECTEDVALUE ( SelectorCuentas_PT[Descripción] )
			VAR Tipo = "%YoY"
			RETURN
			SWITCH (
			    TRUE (),
			
			    -- REQUERIMIENTO DE CAPITAL ADECUADO
			    dar = "Capital Adecuado por Primas",
			        CALCULATE ( [Capital Adecuado por Primas], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Cap. Ade. Por Carga Media De Siniestralidad",
			        CALCULATE ( [Cap. Ade. Por Carga Media De Siniestralidad], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Cap. Ade. Factor De Corrección Por Concentración",
			        CALCULATE ( [Cap. Ade. Factor De Corrección Por Concentración], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Cap. Ade. Riesgo De Crédito Por Reaseguro",
			        CALCULATE ( [Cap. Ade. Riesgo De Crédito Por Reaseguro], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "REQUERIMIENTO DE CAPITAL ADECUADO", CALCULATE ( [REQUERIMIENTO DE CAPITAL ADECUADO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    -- PATRIMONIO TÉCNICO PRIMARIO
			    dar = "Capital Pagado",
			        CALCULATE ( [Capital Pagado], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Capital Operativo",
			        CALCULATE ( [Capital Operativo], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Reserva Legal",
			        CALCULATE ( [Reserva Legal], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Aportes De Accionistas",
			        CALCULATE ( [Aportes De Accionistas], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultados Del Ejercicio",
			        CALCULATE ( [Resultados Del Ejercicio], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Utilidad retenida (capacitaciones)",
			        CALCULATE ( [Utilidad retenida (capacitaciones)], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Dividendos Acción",
			        CALCULATE ( [Dividendos Acción], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Reserva Desviación De Siniestralidad Y Catastrófica",
			        CALCULATE ( [Reserva Desviación De Siniestralidad Y Catastrófica], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "PATRIMONIO TÉCNICO PRIMARIO", CALCULATE ( [PATRIMONIO TÉCNICO PRIMARIO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    -- PATRIMONIO TÉCNICO SECUNDARIO
			    dar = "Utilidad Ret. Futuras Capitalizaciones",
			        CALCULATE ( [Utilidad Ret. Futuras Capitalizaciones], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Otras (Pts)",
			        CALCULATE ( [Otras (Pts)], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "45% Reserva Legal Pts",
			        CALCULATE ( [45% Reserva Legal Pts], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultados Acumulados Utilidades",
			        CALCULATE ( [Resultados Acumulados Utilidades], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultado Del Ejercicio Utilidades",
			        CALCULATE ( [Resultado Del Ejercicio Utilidades], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultados Del Ejercicio Pérdidas",
			        CALCULATE ( [Resultados Del Ejercicio Pérdidas], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "Resultado Del Ejercicio (Pts)",
			        CALCULATE ( [Resultado Del Ejercicio (Pts)], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    dar = "PATRIMONIO TÉCNICO SECUNDARIO",CALCULATE ( [PATRIMONIO TÉCNICO SECUNDARIO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    -- TOTAL
			    dar = "TOTAL PATRIMONIO TÉCNICO",
			        CALCULATE ( [TOTAL PATRIMONIO TÉCNICO], SelectorCalculo_PT[TipoCalculo] = Tipo ),
			
			    BLANK ()
			)
			
			```
		displayFolder: MedidasPT
		lineageTag: 5c8a8d56-640f-4421-8ed6-865750914c3f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column id_nivel1
		dataType: int64
		formatString: 0
		lineageTag: c613cf5f-ac3f-47da-85b7-1ec1928f831e
		summarizeBy: sum
		sourceColumn: id_nivel1

		annotation SummarizationSetBy = Automatic

	column id_nivel2
		dataType: int64
		formatString: 0
		lineageTag: 690dae1b-16fb-45ac-9a92-6582c5f33d8e
		summarizeBy: sum
		sourceColumn: id_nivel2

		annotation SummarizationSetBy = Automatic

	column des_grupo
		dataType: string
		lineageTag: c35fc925-034a-4ec9-8798-17f5a06029ff
		summarizeBy: none
		sourceColumn: des_grupo

		annotation SummarizationSetBy = Automatic

	column fec_periodo
		dataType: string
		lineageTag: 9d164a35-9aae-405d-bc13-0134155b3dbb
		summarizeBy: none
		sourceColumn: fec_periodo

		annotation SummarizationSetBy = Automatic

	column des_cuenta
		dataType: string
		lineageTag: ac1ceb75-5248-4550-b9f4-bed8f1d985c0
		summarizeBy: none
		sourceColumn: des_cuenta
		sortByColumn: id_nivel2

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column fec_periodo_ultimo_dia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 094975b6-5d77-401c-adfe-e52e406c97d5
		summarizeBy: none
		sourceColumn: fec_periodo_ultimo_dia

		variation Variación
			isDefault
			relationship: 76435388-a6f6-4336-89ce-9dabe6c75fa9
			defaultHierarchy: LocalDateTable_8af44c74-d325-41af-b922-ebc0fbfdaff8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fec_corte
		dataType: string
		lineageTag: 84dd29d3-56f1-4819-a98f-c373c7f146f0
		summarizeBy: none
		sourceColumn: fec_corte

		annotation SummarizationSetBy = Automatic

	column particion
		dataType: string
		lineageTag: df929390-1012-4443-975e-2c3ca1963d2d
		summarizeBy: none
		sourceColumn: particion

		annotation SummarizationSetBy = Automatic

	column fec_periodo_fecha_PG = ```
			
			DATE(
			    LEFT(gd_grupo_contable2[fec_periodo], 4),            
			    MID(gd_grupo_contable2[fec_periodo], 5, 2),          
			    1                                               
			)
			```
		formatString: yyyy-mm
		displayFolder: ColumnasPG
		lineageTag: 48707500-bcbe-430b-a4a6-c84d8021e839
		summarizeBy: none

		variation Variación
			isDefault
			relationship: 30e70f6f-e0a8-40cf-ab2d-579647ff4c79
			defaultHierarchy: LocalDateTable_87bcafc8-6724-4679-a310-7076cb316635.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column fec_periodo_fecha_PT = ```
			
			DATE(
			    LEFT(gd_grupo_contable2[fec_periodo], 4),            
			    MID(gd_grupo_contable2[fec_periodo], 5, 2),          
			    1                                               
			)
			```
		formatString: yyyy-mm
		displayFolder: ColumnasPT
		lineageTag: 7255e545-0728-45e6-9922-62bdbf9a851c
		summarizeBy: none

		variation Variación
			isDefault
			relationship: 6067b17f-8fdb-405a-a564-74a9edcd75c3
			defaultHierarchy: LocalDateTable_997d7fee-68e5-4875-90d5-1479118cef3e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column id_nivel3
		dataType: int64
		formatString: 0
		lineageTag: c86a1d78-68ca-435f-a614-149f5b99ce9f
		summarizeBy: sum
		sourceColumn: id_nivel3

		annotation SummarizationSetBy = Automatic

	column des_tipo_ramo
		dataType: string
		lineageTag: d8c66268-7bbe-4d0e-8a30-84e62755c57d
		summarizeBy: none
		sourceColumn: des_tipo_ramo

		annotation SummarizationSetBy = Automatic

	column val_saldo_balance
		dataType: double
		lineageTag: f345ff00-120a-4ddf-854f-4ec420ae9ebd
		summarizeBy: sum
		sourceColumn: val_saldo_balance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_anualizado
		dataType: double
		lineageTag: ac73c2f9-a82e-4c44-a33e-36739ac3bf68
		summarizeBy: sum
		sourceColumn: val_saldo_anualizado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presupuesto
		dataType: double
		lineageTag: 14459ebf-1e9f-4ca0-9d9a-2f0a732ddff9
		summarizeBy: sum
		sourceColumn: val_presupuesto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast
		dataType: double
		lineageTag: be0e3540-ef83-41d4-a949-0acc06dc37da
		summarizeBy: sum
		sourceColumn: val_forecast

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_presupuesto_anualizado
		dataType: double
		lineageTag: b1c34fe6-766b-4646-8cb1-8c1a2d364098
		summarizeBy: sum
		sourceColumn: val_presupuesto_anualizado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_forecast_anualizado
		dataType: double
		lineageTag: 2ac0dad6-2470-48b8-8ceb-19e9b7cac1ff
		summarizeBy: sum
		sourceColumn: val_forecast_anualizado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ramo_PG =
			
			SWITCH(TRUE(),
			    SEARCH("GENERALES", 'gd_grupo_contable2'[des_tipo_ramo], 1, 0) > 0, "NO VIDA",
			    SEARCH("VIDA", 'gd_grupo_contable2'[des_tipo_ramo], 1, 0) > 0, "VIDA",
			    "Otros"
			)
		displayFolder: ColumnasPG
		lineageTag: 2e1db1ca-c10d-45ef-bae9-2cb501b36ed5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Ramo_PT =
			
			SWITCH(TRUE(),
			    SEARCH("GENERALES", 'gd_grupo_contable2'[des_tipo_ramo], 1, 0) > 0, "NO VIDA",
			    SEARCH("VIDA", 'gd_grupo_contable2'[des_tipo_ramo], 1, 0) > 0, "VIDA",
			    "Otros"
			)
		displayFolder: ColumnasPT
		lineageTag: cd329f50-5298-4ab5-9cb3-1cfa251de5c4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column fec_periodo_entero_PT =
			
			VALUE(gd_grupo_contable2[fec_periodo] & "01")
		displayFolder: ColumnasPT
		lineageTag: e171dfe6-db2f-4234-a14d-d4f3df06e827
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val_saldo_mes
		dataType: double
		lineageTag: 59bd8dac-9f83-4f05-9b61-b70fab5417e2
		summarizeBy: sum
		sourceColumn: val_saldo_mes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition gd_grupo_contable2 = m
		mode: import
		source =
				let
				    Origen = Databricks.Catalogs("adb-2683128165517039.19.azuredatabricks.net", "/sql/1.0/warehouses/7d4c90cb72eed782", [Catalog="ctlfinanciero", Database="schgold", QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null]),
				    gd_grupo_contable2_schgold_ctlfinanciero = Origen{[Item="gd_grupo_contable2",Schema="schgold",Catalog="ctlfinanciero"]}[Data]
				in
				    gd_grupo_contable2_schgold_ctlfinanciero

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

