table gd_patrimonio_tecnico_unificado
	lineageTag: 9095a7ce-321a-4cb3-a062-5f22a4c308af

	measure IPC_actual = DIVIDE(SUM(gd_patrimonio_tecnico_unificado[valor]),SUM(gd_patrimonio_tecnico_unificado[valor_y_1]),0)
		lineageTag: 538f29ab-ce5a-4f91-bba0-efe03dc8513e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IPC_y_1 = DIVIDE(SUM(gd_patrimonio_tecnico_unificado[valor_y_1]),SUM(gd_patrimonio_tecnico_unificado[valor_y_2]),0)
		lineageTag: 74bf354b-7ddb-4a85-9f48-d8b363ff1dd2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anio
		dataType: int64
		formatString: 0
		lineageTag: bc21d912-5995-4ee7-b690-cbabb8805b5d
		summarizeBy: sum
		sourceColumn: anio

		annotation SummarizationSetBy = Automatic

	column mes
		dataType: int64
		formatString: 0
		lineageTag: 6b46214d-4f16-4361-84e3-7baeb2063b79
		summarizeBy: sum
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	column id_fecha
		dataType: string
		lineageTag: a0129b4f-775c-4840-aab4-7e77ae6a634f
		summarizeBy: none
		sourceColumn: id_fecha

		annotation SummarizationSetBy = Automatic

	column valor
		dataType: double
		lineageTag: 2619df1e-646d-4b35-9883-a530f17bfb22
		summarizeBy: sum
		sourceColumn: valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column valor_y_1
		dataType: double
		lineageTag: 37c65d49-ed64-4d32-bc86-12ee6cade21c
		summarizeBy: sum
		sourceColumn: valor_y_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'anio -2' = gd_patrimonio_tecnico_unificado[anio]-2
		formatString: 0
		lineageTag: f85e8e6f-44b4-4306-9bb1-2bf1375df829
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column valor_y_2 = LOOKUPVALUE(gd_patrimonio_tecnico_unificado[valor],gd_patrimonio_tecnico_unificado[anio],gd_patrimonio_tecnico_unificado[anio -2],gd_patrimonio_tecnico_unificado[mes],gd_patrimonio_tecnico_unificado[mes])
		lineageTag: 9aea3917-e480-4439-b760-218d5c378dd4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition gd_patrimonio_tecnico_unificado = m
		mode: import
		source =
				let
				    Origen = Databricks.Catalogs("adb-2683128165517039.19.azuredatabricks.net", "/sql/1.0/warehouses/7d4c90cb72eed782", [Catalog="ctlfinanciero", Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null]),
				    ctlfinanciero_Database = Origen{[Name="ctlfinanciero",Kind="Database"]}[Data],
				    schgold_Schema = ctlfinanciero_Database{[Name="schgold",Kind="Schema"]}[Data],
				    gd_patrimonio_tecnico_unificado_Table = schgold_Schema{[Name="gd_patrimonio_tecnico_unificado",Kind="Table"]}[Data]
				in
				    gd_patrimonio_tecnico_unificado_Table

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

